typography/scania-fonts-selectors.scss
typography/scania-fonts-vars.scss
typography/scania-fonts.scss

* Added typography files
Note: still need to be made into a package.

chore(typography): move typography files

---

.storybook/main.js
package-lock.json
package.json

created "storybook" npm script for building project and starting storybook

chore: created script for starting

---

.storybook/main.js
.storybook/preview.js
package.json

Fixes: https://tegel.atlassian.net/browse/DTS-1606

fix: storybook build

---

core/src/global/global.scss

Updated import to include popover-menu-item

fix(popover-menu-item): updated import to include popover-menu-item

---

core/src/global/_utility-classes.scss
core/src/stories/utility/color/background-color.stories.tsx
core/src/stories/utility/color/text-color.stories.tsx
core/src/stories/utility/utility-classes/display.stories.mdx
core/src/stories/utility/utility-classes/float.stories.mdx
core/src/stories/utility/utility-classes/height.stories.mdx
core/src/stories/utility/utility-classes/margin.stories.mdx
core/src/stories/utility/utility-classes/opacity.stories.mdx
core/src/stories/utility/utility-classes/overflow.stories.mdx
core/src/stories/utility/utility-classes/padding.stories.mdx
core/src/stories/utility/utility-classes/placement.stories.mdx
core/src/stories/utility/utility-classes/position.stories.mdx
core/src/stories/utility/utility-classes/text-alignment.stories.mdx
core/src/stories/utility/utility-classes/visibility.stories.mdx
core/src/stories/utility/utility-classes/width.stories.mdx
core/src/stories/utility/utility-classes/z-index.stories.mdx

Changed the prefix for all utility-classes and updated the story files.
Fixes: https://tegel.atlassian.net/browse/DTS-1692
1. Go to stoybook
2. Check in Utilities -> Utility Classes
3. Run branch locally and try out the utility classes

feat(utility classes): prefix change

---

.github/CODE_STYLE.md

Adding convention on branching 
1. Please check what is written
2. If something if off or can be improved, feel free to add suggestion ;)

docs(code-style): branching section

---

.storybook/ScaniaThemeDark.js
.storybook/ScaniaThemeLight.js
.storybook/preview.js

Updated the prefix on the class controlling the theming in storybook.
Fixes: https://tegel.atlassian.net/browse/DTS-1691
2. Toggle light/dark mode and check the class being toggled on the body element

docs(prefix change): changed prefix for the mode change in storybook

---

core/src/components/accordion/accordion-item/accordion-item.scss
core/src/components/accordion/accordion-item/accordion-item.tsx
core/src/components/accordion/accordion-item/readme.md
core/src/components/accordion/accordion-vars.scss
core/src/components/accordion/accordion.scss
core/src/components/accordion/accordion.spec.ts
core/src/components/accordion/accordion.stories.tsx
core/src/components/accordion/accordion.tsx
core/src/components/accordion/readme.md
core/src/components/icon/readme.md
core/src/stories/Migration/Migration.stories.mdx

Updates the prefix for the accordion component.
Fixes: https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1623
2. Check in Components -> Accordion
3. Check the that the styling is correct
4. Check the API and make sure it alignes with the new prefix

feat(accordion): prefix change

---

core/src/components/badge/badge.scss
core/src/components/badge/badge.stories.tsx
core/src/components/badge/badge.tsx
core/src/components/badge/readme.md
core/src/components/data-table/table-header-cell/readme.md
core/src/stories/Migration/Migration.stories.mdx

Updated comments, docs and component to use singular capital case.
Solving issue
How to test

chore(badge): use singular Capital Case where possible

---

core/src/components/toast/readme.md
core/src/components/toast/sdds-toast.tsx

Updated comments and docs to use singular capital case.
Part of: https://tegel.atlassian.net/browse/DTS-1329
2. Check in Components -> Toast
3. Make sure it is always referenced with singular capital case (Toast)

chore(toast): use singular Capital Case where possible

---

core/src/components/spinner/readme.md
core/src/components/spinner/spinner.stories.tsx
core/src/components/spinner/spinner.tsx

Updated comments and docs to use singular capital case.
Part of: https://tegel.atlassian.net/browse/DTS-1329
2. Check in Components -> Spinner
3. Make sure it is always referenced with singular capital case (Spinner)

chore(spinner): use singular Capital Case where possible

---

core/src/components/header/webcomponent/header-hamburger/readme.md
core/src/components/side-menu/readme.md
core/src/components/side-menu/webcomponent/readme.md
core/src/components/side-menu/webcomponent/side-menu-close-button/readme.md
core/src/components/side-menu/webcomponent/side-menu-collapse-button/readme.md
core/src/components/side-menu/webcomponent/side-menu-collapse-button/side-menu-collapse-button.tsx
core/src/components/side-menu/webcomponent/side-menu-dropdown/readme.md
core/src/components/side-menu/webcomponent/side-menu-overlay/readme.md
core/src/components/side-menu/webcomponent/side-menu-user/readme.md
core/src/components/side-menu/webcomponent/side-menu-webcomponent.stories.tsx
core/src/components/side-menu/webcomponent/side-menu.tsx

Updated comments, docs and component to use singular capital case.
Solving issue
How to test

chore(side menu): use singular Capital Case where possible

---

core/src/components/divider/divider-webcomponent.stories.tsx

Updated comments to use singular capital case.
Part of: https://tegel.atlassian.net/browse/DTS-1329
_Go to storybook
Check in Components -> Divider
Make sure it is always referenced with singular capital case (Divider)

chore(divider): use singular Capital case where possible

---

core/src/components/radio-button/radio-button.scss
core/src/components/radio-button/radio-button.stories.tsx
core/src/components/radio-button/radio-button.tsx
core/src/components/radio-button/readme.md

Updated comments, docs and component to use singular capital case. Also renamed the stories and scss file to conform with convention.
Solving issue
How to test

chore(radio button): use singular Capital Case where possible & file renaming

---

core/src/components/popover-canvas/documentation.txt
core/src/components/popover-menu/documentation.txt

Updated comments, docs and component to use singular capital case.
Solving issue
How to test

 chore(popover): use singular Capital Case where possible

---

core/src/components/datetime/datetime.scss
core/src/components/datetime/datetime.tsx

Updated comments, docs and component to use singular capital case.
Solving issue
How to test

chore(datetime): use singular Capital Case where possible

---

core/README.md

Added a copy of the readme to the core package.
Fixes: https://tegel.atlassian.net/browse/DTS-1751
1. Check here: https://github.com/scania-digital-design-system/tegel/tree/docs/DTS-1751-relocate-readme/core

docs(readme): added readme to the core package

---

core/src/components/card/card-vars.scss
core/src/components/card/card.scss
core/src/components/card/card.stories.tsx
core/src/components/card/card.tsx
core/src/components/card/readme.md
core/src/components/divider/readme.md

Prefix change in Card component
Fixes: DTS-1629
1. Go to the Storybook link below.
2. Open the Card component
3. It needs to be visually the same as the one in the main branch.
4. Prefix is removed from file names
5. sdds prefix is replaced with tds in the files
A small change was done to the story file in the slot area by adding an attribute slot to the icon component. Icon uses size prop instead of inline style.

feat(card): prefix change

---

core/src/components/icon/readme.md
core/src/components/slider/documentation.txt
core/src/components/slider/readme.md
core/src/components/slider/slider-vars.scss
core/src/components/slider/slider.scss
core/src/components/slider/slider.stories.tsx
core/src/components/slider/slider.tsx

Updated prefix for slider component.
Fixes: https://tegel.atlassian.net/browse/DTS-1646
2. Check in Components -> Slider
3. Check the component API and style.

feat(slider): prefix change

---

core/src/components/data-table/table-header-cell/readme.md
core/src/components/datetime/datetime-vars.scss
core/src/components/datetime/datetime.scss
core/src/components/datetime/datetime.stories.tsx
core/src/components/datetime/datetime.tsx
core/src/components/datetime/readme.md
core/src/components/icon/readme.md
core/src/stories/Migration/Migration.stories.mdx

Updated the prefix for the datetime component.
Fixes: https://tegel.atlassian.net/browse/DTS-1634
1. Go to storybook.
2. Check in Components -> Datetime
3. Check the component API and the style.

feat(datepicker): prefix change

---

core/src/components/toggle/readme.md
core/src/components/toggle/toggle-vars.scss
core/src/components/toggle/toggle.scss
core/src/components/toggle/toggle.stories.tsx
core/src/components/toggle/toggle.tsx

Updated prefix on toggle component.
Fixes: https://tegel.atlassian.net/browse/DTS-1652
2. Check in Components -> Toggle
3. Check the component API and styles.

feat(toggle): prefix change

---

core/src/components/icon/icon.tsx
core/src/components/icon/readme.md
core/src/components/popover-canvas/documentation.txt
core/src/components/popover-canvas/popover-canvas.stories.tsx
core/src/components/popover-menu/documentation.txt
core/src/components/popover-menu/popover-menu.stories.tsx

Updated links pointing to digitaldesign.scania.com to tegel.scania.com
Fixes: https://tegel.atlassian.net/browse/DTS-1750
2. Search for digitaldesign in repo
3. Make sure all hits are only cdn links.

docs(web links): updated web links pointing to digitaldesign -> tegel

---

core/src/stories/Tegel.stories.mdx

Updated link to correct repo and teams channel.
Fixes: 
2. Check the links in the announcement.

docs(repo): updated link to correct repo and teams channel

---

.npmrc
core/package-lock.json
core/package.json
core/stencil.config.ts

* Set stencil to v 3.3.0 (latest)
* Strict on node -v (16 - 17)
* enableImportInjection
2. Make sure it still works.

build(stecil version): stencil v 3.3.0, node and enableImportInjection

---

package.json

Adding build command to root
Too many times I need to build a command so the suggestion is to have it on the root level.
If new packages come during that time, we can add Lerna...
1. Branch out of this branch
2. Try running build on the root level, it should build stencil...

build: adding build command to root

---

core/src/components/breadcrumbs/breadcrumbs.tsx

Fixes incorrect class name.
Fixes: -

fix(breadcrumbs): class naming

---

core/src/components/card/readme.md
core/src/components/divider/readme.md
core/src/components/dropdown-v2/dropdown-option-v2/readme.md
core/src/components/dropdown/dropdown-filter/readme.md
core/src/components/dropdown/dropdown-option/readme.md
core/src/components/icon/readme.md

Readme updates
Readme updates after running the npm run build command

docs: readme update

---

core/src/components/spinner/spinner-vars.scss
core/src/components/spinner/spinner.scss
core/src/components/spinner/spinner.stories.tsx
core/src/components/spinner/spinner.tsx
core/src/components/table/table-component-basic.stories.tsx

Change prefix for spinner
Fixes: [DTS-1647](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1647)
1. Go to Storybook link
2. Check in Components -> Spinner
3. Check the components APIs and styles.
[DTS-1647]: https://tegel.atlassian.net/browse/DTS-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(spinner): prefix change

---

core/src/components/modal/modal-vars.scss
core/src/components/modal/modal.scss
core/src/components/modal/modal.stories.tsx
core/src/components/modal/modal.tsx
core/src/components/modal/readme.md

Prefix change for modal component
Fixes: [DTS-1641](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1641)
2. Check in Components -> Modal
3. Check the components APIs and styles.
[DTS-1641]: https://tegel.atlassian.net/browse/DTS-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(modal): prefix change

---

core/src/components/link/link-vars.scss
core/src/components/link/link.scss
core/src/components/link/link.stories.tsx
core/src/components/link/link.tsx
core/src/components/link/readme.md

Link component prefix change
Fixes: DTS-1639
1. Go to the Storybook link below
2. Check if the Link component looks good and API works as intended

feat(link): prefix change

---

core/src/components/radio-button/radio-button-vars.scss
core/src/components/radio-button/radio-button.scss
core/src/components/radio-button/radio-button.stories.tsx
core/src/components/radio-button/radio-button.tsx
core/src/components/radio-button/readme.md

Change prefix for radio button component
Fixes: [DTS-1644](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1644)
2. Check in Components -> Radio Button
3. Check if the Radio Button component looks good and API works as intended
[DTS-1644]: https://tegel.atlassian.net/browse/DTS-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(radiobutton): prefix change

---

core/src/components/tooltip/readme.md
core/src/components/tooltip/tooltip-vars.scss
core/src/components/tooltip/tooltip.scss
core/src/components/tooltip/tooltip.stories.tsx
core/src/components/tooltip/tooltip.tsx

Update the component name and updated the prefix.
Fixes: https://tegel.atlassian.net/browse/DTS-1653
2. Check in Components -> Tooltip
3. Check the component API and styles.

feat(tooltip): prefix change

---

core/src/components/checkbox/readme.md
core/src/components/dropdown-v2/dropdown-button.scss
core/src/components/dropdown-v2/dropdown-filter.scss
core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.scss
core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.tsx
core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-vars.scss
core/src/components/dropdown-v2/dropdown-option-v2/readme.md
core/src/components/dropdown-v2/dropdown-v2.scss
core/src/components/dropdown-v2/dropdown-v2.stories.tsx
core/src/components/dropdown-v2/dropdown-v2.tsx
core/src/components/dropdown-v2/dropdown-vars.scss
core/src/components/dropdown-v2/readme.md
core/src/components/dropdown/_dropdown-core.scss
core/src/components/dropdown/dropdown-filter/dropdown-filter.tsx
core/src/components/dropdown/dropdown-filter/readme.md
core/src/components/dropdown/dropdown-option/dropdown-option.tsx
core/src/components/dropdown/dropdown-option/readme.md
core/src/components/dropdown/dropdown-select.scss
core/src/components/dropdown/dropdown-vars.scss
core/src/components/dropdown/dropdown.scss
core/src/components/dropdown/dropdown.stories.tsx
core/src/components/dropdown/dropdown.tsx
core/src/components/dropdown/readme.md
core/src/components/icon/readme.md
core/src/components/table/table-header-cell/readme.md

Prefix change for Dropdown and DropdownV2 component
Fixes: DTS-1636
1. Go to the Storybook link below
2. Check if both Dropdown and DropdownV2 look and behave as versions in main branch
3. Check if the prefix is changed in all relevant places
:root selector is added for dropdown-v2

feat(dropdown): prefix change

---

core/src/components/toggle/toggle.scss

Added a css polyfill for pseudo elements on input[type="checkbox"]
Fixes: -
1. Go to storybook in safari or firefox
2. Check in Components -> Toggle
3. Make sure it looks good.

fix(toggle): browser support

---

core/src/global/global.scss
logotype/_logotype.scss

Moved the logotype folder to root.
Fixes: https://tegel.atlassian.net/browse/DTS-1777

feat(logotype): package structure

---

core/src/stories/Migration/Migration.stories.mdx

Inform about the new prefix change and some grammar checks to the migration document.
Fixes: [DTS-1764](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1764)
2. Check in Migration document
[DTS-1764]: https://tegel.atlassian.net/browse/DTS-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(prefix info): add prefix info in migration docs

---

core/package-lock.json
core/package.json

Removing prettier from the core package as it is installed on the root level
Fixes: DTS-1562
1. Check if prettier work in different folders/packages by being installed on the root level

fix: prettier under devDepenencies

---

core/src/components/card/card.scss
core/src/components/card/card.stories.tsx

Removed the width of the card.
Fixes: https://tegel.atlassian.net/browse/DTS-1781
2. Check in Components -> Card
3. Check that the card has no width css.

feat(card): remove max width

---

core/src/components/icon/icon.stories.tsx

Updated icons story name.
Fixes: -
2. Check in Foundation -> Icons

docs(icons): updated icons story name

---

core/src/components/badge/badge.tsx

Fixing reported issued in [Sonarcloud](https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=scania-digital-design-system_tegel&open=AYf7uLJvIXaIn54uCaao)
Fixes: [DTS-1970](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1970)
[DTS-1970]: https://tegel.atlassian.net/browse/DTS-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(badge): fixing reported issue in Sonarcloud

---

core/src/components/textarea/textarea-vars.scss

Corrected root selector.
Fixes: -

fix(textarea): corrected root selector

---

core/src/components/button/button.tsx
core/src/components/button/readme.md

Added docs for the icon slot.
1. Go to Components -> Button

docs(button): docs for icon slot

---

core/src/components/toggle/readme.md
core/src/components/toggle/toggle.tsx

Fixes: https://tegel.atlassian.net/browse/DTS-2027
1. Go to Components -> Toggle

docs(toggle): docs for the label slot

---

core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/readme.md

1. Go to Components -> Checkbox

docs(checkbox): docs for the label slot

---

core/src/components/radio-button/radio-button.tsx
core/src/components/radio-button/readme.md

1. Go to Components -> Radio Button

docs(radio button): docs for label slot

---

core/src/components/chip/chip.tsx
core/src/components/chip/readme.md

docs(chip): docs for label slot

---

core/src/components/stepper/step/readme.md
core/src/components/stepper/step/step.tsx

1. Go to Components -> Stepper
2. Check under Notes -> Step 
3. Check the slot section.

docs(stepper): docs for label slot

---

core/src/stories/Events/Events.stories.mdx

document removal of event listener in react example

docs(events): document removal of event listener in react example

---

core/src/components/slider/slider.tsx

Small improvements for the slider component
- Keeping component aligned with [PR done in SDDS repo from Gökberg](https://github.com/scania-digital-design-system/sdds/pull/1049)
- Small improvement from SonarCloud (Arrow function should not return assignment. (no-return-assign))
- Simplifying conditional logic 
1. Open PR link below
2. Check Slider component
3. Test changing value 
4. Test +/- button controls (needs to be enabled in Storybook controls)
5. Test disabled state
If needed, compare behaviour with main branch version of Storybook

fix(slider): disabled state and code hygiene 

---

core/src/components/text-field/readme.md
core/src/components/text-field/text-field.tsx
core/src/utils/utils.ts

- Updated conditional rendering for slots
- Added docs for slots
Fixes: https://tegel.atlassian.net/browse/DTS-2026
1. Go to Text Field
2. Check in Notes
3. Check the documentation of the slots.
4. Try the controls for the prefix/suffix
5. Make sure they work as intended.

fix(text-field): align slots

---

core/src/components/toast/readme.md
core/src/components/toast/toast.scss
core/src/components/toast/toast.stories.tsx
core/src/components/toast/toast.tsx
core/src/utils/utils.ts

- Alignes slot names
- Simplifies logic for conditional rendering of slots vs props.
Fixes: https://tegel.atlassian.net/browse/DTS-1952
2. Check in Components -> Toast
3. Test the controls and check the styles.

feat(toast): align slots

---

core/src/components/dropdown/dropdown.scss

Corrected the font (detail-02) in the dropdown.
Fixes: https://tegel.atlassian.net/browse/DTS-2046
2. Check the fonts used in different parts of the Dropdown

fix(dropdown): corrected font

---

core/src/components/card/card.tsx
core/src/components/card/readme.md

Updated missspelled @slto -> @slot
1. Go to Card
2. Check in Notes -> Slots -> header

docs(card): updated slot docs

---

core/src/components/modal/modal.tsx
core/src/components/radio-button/radio-button-vars.scss

Corrected color on the border of the radio button in disabled state.
Fixes: https://tegel.atlassian.net/browse/DTS-2034
1. Go to Radio Button
2. Set it to disabled.
3. Make sure the ring is grey-500.

fix(radio button): wrong color disabled state

---

core/src/components/message/message.scss

Corrected text color on minimal message in error state.
Fixes: https://tegel.atlassian.net/browse/DTS-2049
1. Go to Message -> Minimal -> Error
2. Check the the message follows design.

fix(message): corrected text color on minimal message in error state

---

core/src/components/banner/banner.tsx

Updated the hide/showBanner methods to not emit tdsClose/tdsShow event.
Fixes: https://tegel.atlassian.net/browse/DTS-1961
1. Check out branch.
2. Prevent default on tdsClose/Show event.
3. Hide/show the banner programatically and make sure it works.

fix(banner): closing programatically without emitting event

---

core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
core/src/components/tabs/folder-tabs/folder-tab/folder-tab.tsx
core/src/components/tabs/folder-tabs/folder-tabs-vars.scss
core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
core/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx

Corrected the color for the disabled tabs.
Fixes: -
1. Go to Tabs -> Folder
2. Check in check the styling for the disabled tab.

fix(tabs): correct the text color of disabled tabs

---

core/src/components/button/button.scss
core/src/components/button/button.tsx

Corrected the padding for buttons with icons.
Fixes: https://tegel.atlassian.net/browse/DTS-2094
1. Go to Button
2. Check the padding of the button with an icon

fix(button): padding for button with icon

---

core/src/components/table/table-component-event-listeners.stories.tsx
core/src/components/table/table-component-pagination.stories.tsx
core/src/components/table/table-footer/readme.md
core/src/components/table/table-footer/table-footer.tsx

- Renamed maxPages -> pages
- Renamed paginationValue -> defaultPage
- If pages is used, all pagination logic needs to be handled by the user.
- Added example of pagination logic in story 
- Deprecation notice the rowsPerPage prop
Fixes: https://tegel.atlassian.net/browse/DTS-2076
1. Go to Table -> Pagination
2. Check the API of the table-footer
3. Test the pagination in the pagination story

feat(table-footer): refactored pagination logic and implementation

---

core/package-lock.json
core/src/components/chip/chip.scss
core/src/components/chip/chip.stories.tsx
core/src/components/chip/chip.tsx
core/src/components/chip/readme.md
core/src/components/table/table-header-cell/readme.md
package-lock.json

Fixing issues with padding and slots in the Chip component.
Fixes: [DTS-2074](https://tegel.atlassian.net/browse/DTS-2074)
1. Go to Netlify preview link
2. Check that component has all slots mentioned under Notes tab
3. Check that component padding is correct for all states of component: large, small, without icons, with prefix, with suffix...
I had to introduce slots for prefixes and suffixes in order to assign correct padding to the label as it changes if icons are present or not. 
[DTS-2074]: https://tegel.atlassian.net/browse/DTS-2074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(chip): spacing & slots

---

core/package-lock.json
core/package.json

Release of @scania/tegel: 0.0.10

chore: release 0.0.10

---

core/src/stories/tegel.stories.ts

fix: prefix change banner slot name

---

.eslintignore
README.md
commitlint.config.js
core/src/components/table/table-header-cell/readme.md
package.json

Adding additional release tags to commitlint and commitizen

ci: extended list of commitlint & commitizen tags

---

README.md

Node version correction in shield

build: node shield correction

---

README.md

Adding additional shields:
- weekly downloads
- yearly downloads
- last commit
- netlify status
- PRs welcome

build: additional shields

---

.github/PULL_REQUEST_TEMPLATE.md

Update of PR template to ease adding tickets number

ci: update of pr template

---

core/.storybook/main.js
core/.storybook/preview.js
core/package-lock.json
core/package.json

Adding a Chip "like" indicator of version in the toolbar of Storybook.
More here: https://www.npmjs.com/package/storybook-version

feat(storybook): show package version

---

core/package-lock.json
core/package.json
package-lock.json
package.json

Release of tegel package 0.0.11

Release/release 0.0.11

---

core/src/stories/css-reset.stories.mdx

Slimmed down our CSS reset to not impact out components.
Fixes: [DTS-2055](https://tegel.atlassian.net/browse/DTS-2055)
2. Check in CSS Reset
[DTS-2055]: https://tegel.atlassian.net/browse/DTS-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(css reset): slimmed down css reset

---

.github/CODE_STYLE.md
.github/PULL_REQUEST_TEMPLATE.md

Changed DTS- to CDEP- to conform with name change.

chore(code styles and pr template): changed DTS- to CDEP-

---

core/src/global/_utility-classes.scss
core/src/stories/utility/utility-classes/flex.stories.mdx

Adding additional utility classes related to flex. 
Those are copied over from react demo environment.
Fixes: [CDEP-2180](https://tegel.atlassian.net/browse/CDEP-2180)
1. Check _utility-classes file
2. Check if the same content is under Storybook story for utility classes under "Flex"
3. Feel free to suggest more if you feel is needed in this point of time
[CDEP-2180]: https://tegel.atlassian.net/browse/CDEP-2180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(utility-classes): flex section

---

core/package-lock.json
core/package.json
core/src/components/dropdown/readme.md

Release 0.0.12
Fixes: [CDEP-1904](https://tegel.atlassian.net/browse/CDEP-1904)
[CDEP-1904]: https://tegel.atlassian.net/browse/CDEP-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release: tegel 0.0.12

---

.github/CODE_STYLE.md

Adding updates regarding new branches and their purpose (develop/main)
Fixes: [CDEP-2224](https://tegel.atlassian.net/browse/CDEP-2224)
1. Check if added text in code styles makes sense regarding the purpose of main and develop branch
[CDEP-2224]: https://tegel.atlassian.net/browse/CDEP-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(code_style): branching update

---

core/package-lock.json
core/package.json

Installing version 4 of the Stencil compiler. So far we used 3.3.
I have not found any breaking change for us.
[More about version 4.](https://stenciljs.com/docs/introduction/upgrading-to-stencil-four)
1. Run the `npm i`, `npm build` and `npm start` on this branch. 
2. Check if the system works as before,

build(stencil): v4

---

core/src/components/slider/readme.md
core/src/components/slider/slider.scss
core/src/components/slider/slider.stories.tsx
core/src/components/slider/slider.tsx
core/src/stories/Migration/Migration.stories.mdx

Renamed all instances of "scrubber" to "thumb" to align with documentation and design.
Fixes: [CDEP-2107](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2107)
2. Check in Slider
3. Test that it still looks and works as it should

refactor(slider): rename scrubber to thumb

---

core/stencil.config.ts

Enables tagNameTransform to allow for teams to use multiple versions of tegel in one project.
Fixes: [CDEP-2452](https://tegel.atlassian.net/browse/CDEP-2452)
Not testable by us. Will be tested by IASC team.
[CDEP-2452]: https://tegel.atlassian.net/browse/CDEP-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build(tagNameTransform): enable tagNameTransform

---

core/src/components/stepper/step/step.scss

Corrected the css selector: listItem -> listitem
Fixes: -
1. Go to Stepper
2. Check that it looks as expected.

fix(step): corrected css selector

---

core/src/global/_utility-classes.scss
core/src/stories/utility/utility-classes/align.stories.mdx
core/src/stories/utility/utility-classes/flex.stories.mdx
core/src/stories/utility/utility-classes/gap.stories.mdx
core/src/stories/utility/utility-classes/justify.stories.mdx

Added and updated utility classes
Fixes: -
1. Go to Utility classes
2. Check the naming and value of each

feat: utility classes

---

core/src/components/table/table-header/table-header.tsx

- Reflected the allSelected prop to keep it in sync with the attribute.
Fixes: -

fix(table): reflect all-selected attribute

---

core/src/mixins/_z-index.scss

side-menu has higher z-index then Banner

fix(z-index): side-menu over banner

---

README.md
core/README.md
core/src/stories/tegel.stories.ts

Switched all instances of pre-beta to beta.
Fixes: [CDEP-2484](https://tegel.atlassian.net/browse/CDEP-2484) [CDEP-2484](https://tegel.atlassian.net/browse/CDEP-2586)
1. Go to this branch and check the readme
[CDEP-2484]: https://tegel.atlassian.net/browse/CDEP-2484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: switched all instances of pre-beta to beta

---

core/package-lock.json
core/package.json

Release of @scania/tegel@1.0.1 beta

release: 1.0.1

---

core/package-lock.json
core/package.json

This release only includes a updated build config. Switched the `customElementsExportBehavior` from `auto-define-custom-elements` to `single-export-module`. This is to allow us to build standalone Angular components.

release: 1.0.2

---

packages/angular/package.json

Removed privacy flag in the package.json for @scania/tegel-angular

fix: removed the privacy flag in package.json

---

packages/angular/README.md

Updated README for @scania/tegel-angular
**Solving issue**
Fixes: -
1. Check the README here: https://github.com/scania-digital-design-system/tegel/tree/docs/update-readme-for-angular-package/packages/angular

docs(tegel-angular): updated README

---

.github/workflows/chromatic.yml

Create github action for chromatic
Fixes: -

feat/create chromatic.yml

---

packages/angular/package-lock.json
packages/angular/package.json
packages/angular/projects/components/package-lock.json
packages/angular/projects/components/package.json

Switched the build of our wrappers to use Angular v14 over 16. This to have some backwards compatibility support.
Fixes: -
1. Checkout branch
2. Run `npm i` in root, packages/angular and packages/angular/projects/components
3. Build and pack a version of @scania/tegel-angular
4. Test it locally in the angular demo.

build(angular): switched angular version to 14

---

packages/core/package-lock.json
packages/core/package.json

release(1.0.3): updated package.json

---

packages/angular/package-lock.json
packages/angular/package.json
packages/angular/projects/components/package.json

Release of @scania/tegel-angular@0.0.2

release(@scania/tegel-angular): 0.0.2

---

packages/core/src/components/dropdown/dropdown.tsx

Removed TODO comment and added link to jira issue.
Fixes: -

docs(dropdown): removed TODOs and added link to future issue

---

packages/core/package-lock.json
packages/core/package.json

Bumped stencil version.
Fixes: -
2. Run `npm run build`
3. Make sure everything builds fine

build(stencil): bumped stencil version

---

packages/core/src/components/button/button-vars.scss
packages/core/src/components/button/button.scss

Corrected the icon colors in the button component.
Fixes: [CDEP-2674](https://tegel.atlassian.net/browse/CDEP-2674)
1. Go to Button
2. Add an icon
3. Check the computed color of the icon and make sure it aligns with design
[CDEP-2674]: https://tegel.atlassian.net/browse/CDEP-2674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): icon color correction

---

.github/workflows/chromatic.yml

This PR adds a github action that publishes our storybook to Chromatic on each push on the **develop** branch.
Fixes: [CDEP-2659](https://tegel.atlassian.net/browse/CDEP-2659)
[CDEP-2659]: https://tegel.atlassian.net/browse/CDEP-2659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chromatic: added chromatic workflow

---

.github/workflows/chromatic.yml

Added --exit-once-uploaded flag
Fixes: -

fix(chromatic): added --exit-once-uploaded flag

---

packages/core/src/components/toast/toast.stories.tsx
packages/core/src/components/toast/toast.tsx

This PR enables for runtime updates of the `hidden` prop present on the tds-toast.
Fixes: -
1. Update the `hidden` prop of the Toast in runtime
2. Make sure it hides/shows

fix(toast): enable for runtime updates of the hidden prop

---

packages/core/.storybook/manager-head.html

Updating Plausible domain for **main branch (prod)**
Fixes: [CDEP-2890](https://tegel.atlassian.net/browse/CDEP-2890)
1. Check if the domain in code changes is updated to new one (tds-storybook.tegel.scania.com)
[CDEP-2890]: https://tegel.atlassian.net/browse/CDEP-2890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plausible): domain update

---

packages/core/src/components/datetime/datetime.stories.tsx

Updated the setting of max prop in the story.
1. Go to Datetime
2. Test and validate the max prop

docs(datetime): correct the setting of max prop

---

packages/angular/README.md
packages/react/README.md

Update React package readme. Also did a minor change to the Angular readme.

chore: update package readmes

---

packages/angular/package.json

Updates angular package description.
Fixes: [CDEP-2838](https://tegel.atlassian.net/browse/CDEP-2838)
Look at the code.
[CDEP-2838]: https://tegel.atlassian.net/browse/CDEP-2838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update angular package description

---

packages/react/package-lock.json
packages/react/package.json

chore: update react package version

---

README.md

Update docs readme for development install after trying to install it by myself for the first time.
1. Check PR
2. Should have updated readme with a bigger understanding of how to start a development server after first cloning the repo.

docs(tegel): update readme to start development enviroment

---

packages/angular/package-lock.json
packages/angular/package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/components/table/table-header-cell/readme.md
packages/react/package-lock.json
packages/react/package.json

preparing code for the release of 1.2.0 version.

release: 1.2.0

---

packages/angular/package-lock.json
packages/angular/package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/components/table/table-header-cell/readme.md
packages/react/package-lock.json
packages/react/package.json

Release of 1.3.0:
- @scania/tegel 
- @scania/tegel-angular
- @scania/react

release: 1.3.0

---

.github/workflows/bump-npm-version.yml
.github/workflows/chromatic.yml
.github/workflows/create-release-pr.yml
.github/workflows/playwright.yml
.github/workflows/release-angular.yml
.github/workflows/release-core.yml
.github/workflows/release-react.yml
.prettierignore
package.json

This PR updates the release pipeline so it works (please work 🙏).
**Solving issue** 
Fixes: [CDEP-2970](https://tegel.atlassian.net/browse/CDEP-2970)
Not really possible to test. 
Maybe just read through the files and check if something looks off to you.
Our last release with these workflows failed miserably - hence the update.
[CDEP-2970]: https://tegel.atlassian.net/browse/CDEP-2970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update create-release-pr job

---

.github/workflows/create-release-pr.yml

chore(pipeline fixes): try again

---

.github/workflows/release-angular.yml
.github/workflows/release-core.yml
.github/workflows/release-react.yml

chore(release pipe): change how release from main is forced

---

packages/angular/package-lock.json
packages/angular/package.json
packages/core/package-lock.json
packages/core/package.json
packages/react/package-lock.json
packages/react/package.json

_Describe what the pull-request is about_
_In case of GitHub issue add # plus the number of the issue (for example #123) OR if it is Azure then AB# and number of ticket_
Fixes: [CDEP-](https://tegel.atlassian.net/browse/CDEP-)
1. Go to...
2. Check in...
3. Run ...
_If applicable, add screenshots to help explain_
_Add any other context about the pull-request here._

release:@scania/tegel@1.3.1

---

.github/workflows/create-release-pr.yml
packages/core/package.json

run build two times due to bug in stencil
[Stencil BUG](https://github.com/ionic-team/stencil/issues/2769)

fix(release): run build two times due to bug in stencil

---

packages/angular/package-lock.json
packages/angular/package.json
packages/core/package-lock.json
packages/core/package.json
packages/react/package-lock.json
packages/react/package.json

release: @scania/tegel@1.3.3

---

.github/workflows/release-angular.yml

fix(release-angular): added working directory
fix(release-angular): added working directory

fix(release-angular): added working directory

---

packages/core/package-lock.json
packages/core/package.json
packages/core/src/components/dropdown/dropdown-option/readme.md
packages/core/src/components/dropdown/readme.md
packages/core/src/components/tabs/folder-tabs/readme.md
packages/core/src/components/tabs/inline-tabs/readme.md
packages/core/src/components/tabs/navigation-tabs/readme.md

Upgrading Stenil version
1. Run build on your local
2. No differences should be noticed
There is update in readme files of some components that came after upgrading Stencil version.

build(stencil): upgrade to 4.9.0

---

packages/angular/package-lock.json
packages/angular/package.json
packages/core/package-lock.json
packages/core/package.json
packages/react/package-lock.json
packages/react/package.json

Missing commit for develop branch after the release

release: 1.4.0.

---

.github/PULL_REQUEST_TEMPLATE.md

Updating the PR template to reflect unit test and documentation needs
1. Check changes in commit

ci: pr template update

---

packages/core/src/components/tooltip/tooltip.stories.tsx

Adds props to set the offset skidding and distance for the `<tds-tooltip>`
#509 
**Todo**
1. Go to Tooltip
2. Try out the offsetSkidding and offsetDistance controls.

feat(tooltip): Adds offsetSkidding and offsetDistance props for the tooltip

---

.github/CODE_STYLE.md
README.md
packages/angular/README.md
packages/core/README.md
packages/core/src/stories/announcements/announce-tegel.stories.ts
packages/react/README.md

Removes links to netlify in readme and stories.

docs: remove netlify links in readmes and stories

---

.github/CODE_STYLE.md
README.md

Updating documentation on code conventions and contributing
Fixes: [CDEP-3185](https://tegel.atlassian.net/browse/CDEP-3185)
Have a look at the README and check for inconsistencies and spelling errors. 
[CDEP-3185]: https://tegel.atlassian.net/browse/CDEP-3185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: update to conventions and contribution

---

.github/workflows/create-release-pr.yml

Test of main as reference in release script

ci: main as reference

---

.github/workflows/create-release-pr.yml

Testing out usage of release branch instead

ci: use release branch

---

.github/workflows/release-all.yml

Fix for release script 
Fixing issues in the release "all script"
1. Check if the code makes sense it is hard to test it without testing in prod

ci: release all script improvement

---

packages/core/package-lock.json
packages/core/package.json

Bumping Stencil to v4.12.6
Fixes: [CDEP-3207](https://tegel.atlassian.net/browse/CDEP-3207)
Issue from GitHub: https://github.com/scania-digital-design-system/tegel/issues/536
1. Check if build and localhost works as expected
[CDEP-3207]: https://tegel.atlassian.net/browse/CDEP-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build(stencil): v4.12.6

---

.github/workflows/create-release-pr.yml

fix: adjust create pr part of release script

---

packages/core/src/components/banner/banner.scss
packages/core/src/components/modal/modal.scss
packages/core/src/components/radio-button/radio-button.scss
packages/core/src/components/tooltip/tooltip.scss

Vars imports should only be in the global.scss file. 
Fixes: There were some duplicate imports.

fix(vars): removing duplicate vars imports

---

.github/workflows/create-release-pr.yml
.github/workflows/release-angular-17.yml

Added release script for @scania/tegel-angular-17 package and adjusted the "create-release-pr" script.
[CDEP-3326](https://tegel.atlassian.net/browse/CDEP-3326)
[CDEP-3326]: https://tegel.atlassian.net/browse/CDEP-3326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(angular-17): add angular-17 release script

---

.github/workflows/release-angular-17.yml

Correcting Angular-17 release script.

ci(angular-17): correct angular-17 release script

---

packages/core/src/stories/Installation/angular-17.stories.ts

Adding angular-17 installation guide to Storybook
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3334](https://tegel.atlassian.net/browse/CDEP-3334)    
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/639 
1. Go to the preview link
2. Check if Angular-17 installation guide looks good
[CDEP-3334]: https://tegel.atlassian.net/browse/CDEP-3334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: added angular-17 installation guide

---

.github/workflows/release-all.yml

Fix for committing and merging steps of release-all script
- **No issue:** Fix for committing and merging steps of release-all script. We noticed it during the last release.
Hard to test, just check if update makes sense. It will be tested in next release.

ci(release-script): commit and merge improvement

---

.github/workflows/playwright.yml
.gitignore
packages/core/playwright.config.ts
packages/core/results.json

Adding a feature to see Playwright results as a comment on PR.
Added rule for Playwright to run on pull-request. So far it was only on push.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3405](https://tegel.atlassian.net/browse/CDEP-3405)    
1. Check if Playwright runs on the pull request.
2. Check if the Playwright posts a comment on PR with scan results.
[CDEP-3405]: https://tegel.atlassian.net/browse/CDEP-3405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(playwright): report as comment on pr

---

packages/core/src/components/slider/slider.tsx

Fixing errors caught in the console during runtime, when switching pages etc.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3035](https://tegel.atlassian.net/browse/CDEP-3035)    
- **GitHub:** [Include issue link  ](https://github.com/scania-digital-design-system/tegel/issues/410)
1. Check Storybook and see if the component renders and works as expected.
2. Check the demo page where the component and fixes are implemented: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/101
[CDEP-3035]: https://tegel.atlassian.net/browse/CDEP-3035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(slider): runtime issue

---

.github/workflows/release-all.yml

In the last run script has failed due to missing GitHub user.
- **No issue:** Adding the step to use Tegel-Scania as a user when merging develop to main.
1. We will have to wait for another release

ci(release-all): setup github user

---

packages/styles/scss/ag-grid/ag-grid-styles.scss

Some CSS variables needed prefixes, some were moved in separate :root as they are mode/theme agnostic, and some did not exist in Tegel code.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3441](https://tegel.atlassian.net/browse/CDEP-3441)    
1. Build CSS of tegel styles and test it in tegel and non tegel environment
Non tegel environment in [CodeSandbox](https://codesandbox.io/p/sandbox/quick-start-example-forked-29gdwh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentT …

fix(tegel-styles): ag-grid-overwrites clean up

---

packages/core/src/components/icon/readme.md
packages/core/src/components/table/table-body-input-wrapper/readme.md
packages/core/src/components/table/table-body-input-wrapper/table-body-input-wrapper.scss
packages/core/src/components/table/table-body-input-wrapper/table-body-input-wrapper.tsx
packages/core/src/components/table/table-component-basic.stories.tsx
packages/core/src/components/table/table-component-batch-actions.stories.tsx
packages/core/src/components/table/table-component-custom-width.stories.tsx
packages/core/src/components/table/table-component-expandable-rows.stories.tsx
packages/core/src/components/table/table-component-filtering.stories.tsx
packages/core/src/components/table/table-component-horizontal-scroll.stories.tsx
packages/core/src/components/table/table-component-multiselect.stories.tsx
packages/core/src/components/table/table-component-pagination.stories.tsx
packages/core/src/components/table/table-component-sorting.stories.tsx
packages/core/src/components/table/table-header-input-wrapper/readme.md
packages/core/src/components/table/table-header-input-wrapper/table-header-input-wrapper.scss
packages/core/src/components/table/table-header-input-wrapper/table-header-input-wrapper.tsx
packages/core/src/components/table/table-vars.scss

Created and started on `tds-table-input-wrapper` component
- **Jira:** Add ticket number after `CDEP-`: [CDEP-](https://tegel.atlassian.net/browse/CDEP-)    
1. Go to...
2. Check in...
3. Run ...

feat: added new component tds-table-input-wrapper

---

packages/core/.storybook/main.cjs
packages/core/package-lock.json
packages/core/src/components/table/table-body-input-wrapper/table-body-input-wrapper.scss
packages/core/src/components/table/table-body-input-wrapper/table-body-input-wrapper.tsx
packages/core/src/components/table/table-component-column-filtering.stories.tsx
packages/core/src/components/table/table-component-editing.stories.tsx
packages/core/src/components/table/table-header-input-wrapper/table-header-input-wrapper.scss
packages/core/src/components/table/table-header-input-wrapper/table-header-input-wrapper.tsx
packages/core/src/components/table/table-vars.scss

First version of column filtering and data editing stories
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3430](https://tegel.atlassian.net/browse/CDEP-3430)    
1. Check preview link
2. Check Editing story under Table
3. Check Filter column story under Table
[CDEP-3430]: https://tegel.atlassian.net/browse/CDEP-3430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(table): column filtering & data editing stories

---

LICENSE
packages/styles/README.md

Providing structure overview of @tegel/styles repo 
- **No issue:** Polishing docs before publishing of npm package
1. Please check how does readme looks like and if it contains all the necessary info.
2. As this would be text visible on the NPM side, is there something more that needs to be added?

docs(tegel-styles): readme update

---

packages/core/src/stories/announcements/table-libraries.stories.ts

Basic info on differences and when to use each library for table
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3449](https://tegel.atlassian.net/browse/CDEP-3449)    
1. Check text written under Intro --> Announcements --> Table Libraries
2. Please suggest changes if something in not current or wrong with grammar or spell check.
[CDEP-3449]: https://tegel.atlassian.net/browse/CDEP-3449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(table-libraries): added basic info about tegel, tanstack and ag-grid

---

packages/angular-17/angular.json
packages/angular-17/package-lock.json
packages/angular-17/package.json
packages/angular-17/projects/components/package-lock.json
packages/angular-17/projects/components/package.json
packages/angular/package-lock.json
packages/angular/package.json
packages/angular/projects/components/package-lock.json
packages/react/package-lock.json
packages/react/package.json
packages/styles/package-lock.json

Updated tegel dependencies in wrapper packages

chore: update tegel dependencies in wrapper packages

---

.github/workflows/release-all.yml
.github/workflows/release-angular-17.yml
.github/workflows/release-angular.yml
.github/workflows/release-react.yml
package.json
packages/angular-17/package-lock.json
packages/angular-17/package.json
packages/angular-17/projects/components/ng-package.json
packages/angular-17/projects/components/package-lock.json
packages/angular/package-lock.json
packages/angular/projects/components/package-lock.json
packages/angular/projects/components/package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/components/table/table-footer/table-footer.tsx
packages/core/src/components/table/table-toolbar/table-toolbar.tsx
packages/core/src/components/table/table/table.tsx
packages/react/package-lock.json
packages/styles/package.json

Fixing broken horizontal scroll
- **Jira:** [CDEP-3450](https://tegel.atlassian.net/browse/CDEP-3450)    
1. Go to Storybook.
2. Check in Storybook
4. Enter a value for horizontal scroll
[CDEP-3450]: https://tegel.atlassian.net/browse/CDEP-3450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(table): passing on unit value with horizontalscroll

---

.github/workflows/release-all.yml
.github/workflows/release-angular-17.yml
.github/workflows/release-angular.yml
.github/workflows/release-react.yml
package.json
packages/angular-17/package-lock.json
packages/angular-17/package.json
packages/angular-17/projects/components/ng-package.json
packages/angular-17/projects/components/package-lock.json
packages/angular/package-lock.json
packages/angular/projects/components/package-lock.json
packages/angular/projects/components/package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/components/table/table-footer/table-footer.tsx
packages/core/src/components/table/table-toolbar/table-toolbar.tsx
packages/core/src/components/table/table/table.tsx
packages/react/package-lock.json
packages/styles/package.json

This reverts commit 7d584a1c8a72ffe8814ba67ea36aab81cbaa53a4.
Reverting erroneus PR introduced [here](https://github.com/scania-digital-design-system/tegel/pull/736)
Run ```npm run build-all```, and see that it compiles all packages.

revert(table): passing on unit value with horizontalscroll (#736)

---

packages/angular-17/package.json
packages/angular-17/projects/components/package.json
packages/angular/package.json
packages/react/package.json

Update dependency version for @scania/tegel

chore: bump versions

---

packages/angular-17/package-lock.json
packages/angular-17/projects/components/package-lock.json
packages/angular/package-lock.json
packages/react/package-lock.json

Updated package-lock files to match bumped version 1.15.0 in package.json files
1. Checkout this branch
2. Make sure all packages build without diffs in local

chore: update package-lock files for version bump 1.15.0

---

.github/PULL_REQUEST_TEMPLATE.md

Added to "before submission"-checklist

fix: pr template improvements

---

packages/core/src/components/table/table-component-pagination.stories.tsx
packages/core/src/components/table/table-footer/table-footer.tsx

Fixing pagination bug.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-](https://tegel.atlassian.net/browse/CDEP-)    
1. Go to amplify -> tables  -> pagination
2. Go to last page
3. Change number of pages

fix: reseting pagination if number of pages changes

---

package-lock.json
package.json
packages/angular-17/package-lock.json
packages/angular-17/projects/components/package-lock.json
packages/angular/package-lock.json
packages/angular/projects/components/package-lock.json
packages/core/package-lock.json
packages/react/package-lock.json
reinstall.sh

Automated process: 
cd into all packages, remove node_modules and package-lock.json. Then install dependencies again.
- **Jira:** `CDEP-3501` [tegel-script-to-improve-debugging](https://tegel.atlassian.net/browse/CDEP-3501)    
1. cd to tegel directory
2. run command: `npm run reinstall`
Another suggestion is to split the script in two, one command to delete files, and one to install. Let me know what you think

build: reinstall packages script

---

packages/core/src/components/table/table-body-row/table-body-row.tsx
packages/react/package.json

moved comment that caused stencil build error.
1. fetch and ceckout branch
2. `npm run build-all` in root

fix(table-body-row): moved comment that caused stencil build error

---

package-lock.json
packages/angular-17/package-lock.json
packages/angular-17/projects/components/package-lock.json
packages/angular/package-lock.json
packages/angular/projects/components/package-lock.json
packages/core/package-lock.json
packages/react/package-lock.json

fix: added package-lock files

---

.github/workflows/smoketest-all.yml

Install Core in all wrappers to make sure all dependencies are there

fix: install core in all wrappers

---

.github/workflows/holy-grail.yml
.github/workflows/merge-develop-test
.github/workflows/release-all.yml
packages/core/src/components/table/table/test/expandable-row-autocollapse/expandable-row-autocollapse.e2e.ts

Adding token authentication for Tegel-Scania
Adding new script to cover all release steps in one
Adding test merge script to test merge to protected branch with Tegel-Scania user
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3550](https://tegel.atlassian.net/browse/CDEP-3550)    
1. Check if jobs in the script make sense
2. Once merged, it will be tested
[CDEP-3550]: https://tegel.atlassian.net/browse/CDEP-3550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci(release-script): token authentication, all in one, merge test

---

.github/workflows/smoketest-all.yml

Added manually trigger for Smoke test workflow
- **Jira:**  `Part of` [https://tegel.atlassian.net/browse-CDEP-3560)](https://tegel.atlassian.net/browse-CDEP-3560)    
1. Go to GitHub Actions
2. Go to "Smoke test - Release" workflow
3. Run workflow
Part of other jira ticket, added here for testing purposes

chore: manually trigger + name change

---

packages/angular/package.json
packages/react/package.json

fix: update to right versions

---

packages/react/package.json

fix(wrappers): wrong versions

---

packages/core/src/components/icon/icon.stories.tsx
packages/core/src/stories/foundations/icons-gallery.stories.tsx

Added icon gallery for easy overview of available icons
- **No issue:** Heard from a user during ScaniaJS meet up as missing feature.
1. Check preview link
2. Go to Icons and check "Gallery" story

feat: icon gallery

---

packages/angular-17/package.json
packages/angular-17/projects/components/package.json
packages/react/package.json

build: bump wrapper versions

---

packages/angular-17/package-lock.json
packages/react/package-lock.json

build/bump versions 1.18.0

---

.github/ISSUE_TEMPLATE/bug_report.md

Following up on our discussion yesterday and updating our bug template accordingly. Please read through and give your opinion.
Updating the bug template so that we can better understand the developers problem and help in a more efficient way.
Please read through the new bug template

fix: update bug template

---

README.md

Linking to the copy assets script readme from the "official" readme. 
- **Jira:** [CDEP-3601](https://tegel.atlassian.net/browse/CDEP-3601)    
Not entirely sure how we should formulate the info link, so have a look and see if it makes sense.
[CDEP-3601]: https://tegel.atlassian.net/browse/CDEP-3601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: adding link to static assets copy command

---

.github/workflows/smoke-test-all.yml

ci: smoke test improvement

---

.github/workflows/smoke-test-all.yml

changed all build scripts to colon-based

fix: changing build scripts to new colon:based

---

.github/workflows/holy-grail.yml

Fix Holy Grail script to work with new script syntax using colons.

ci: update holy grail script with new npm script syntax

---

package-lock.json
packages/angular-17/package-lock.json
packages/angular-17/package.json
packages/angular-17/projects/components/package-lock.json
packages/angular-17/projects/components/package.json
packages/angular/package-lock.json
packages/angular/package.json
packages/angular/projects/components/package-lock.json
packages/core/package-lock.json
packages/react/package-lock.json
packages/react/package.json

Manual release of wrappers since Holy Grail script failed after script update from dash to colons.

release: version 1.21.0 for wrappers

---

packages/core/package-lock.json
packages/core/package.json

Due to failed release we need to update version number in core to align on a new release using holy grail script.

fix: tegel core version number

---

.github/workflows/beta-release.yml

changed run scripts to use colon

fix: beta release correct run scripts

---

.github/PULL_REQUEST_TEMPLATE.md

Added accessibility check to pr template and testing to run storybook with dev flag on PRs

fix: added accessibility checks for PRs

---

.github/workflows/accessibility-test.yml
.gitignore
package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/playwright-axe.config.ts
packages/core/src/components/accordion/test/basic/accordion.axe.ts

A start to setup github action and a separate playwright flow for accessibility tests

test: accessibility

---

packages/core/src/components/toggle/toggle.scss

Updating the hover state of the toggle component to align with the Figma design
- **Jira:** Add ticket number after `CDEP-`: [CDEP-80](https://jira.scania.com/browse/CDEP-80)    
Compare the changes with the figma design

fix(toggle): add hover effect

---

.github/PULL_REQUEST_TEMPLATE.md

Update template with correct syntax for build commands and Jira linking. 
- **Jira:** [CDEP-168](https://tegel.atlassian.net/browse/CDEP-168)

docs: update to PR template

---

.github/workflows/accessibility-test.yml
.gitignore
packages/core/package.json
packages/core/playwright-axe.config.ts
packages/core/src/components/accordion/accordion-item/accordion-item.tsx
packages/core/src/components/accordion/accordion-item/readme.md
packages/core/src/components/accordion/accordion.stories.tsx
packages/core/src/components/accordion/test/basic/accordion.axe.ts
packages/core/src/utils/axeHelpers.ts

The pull request addresses the issues we have found in the Accessibility audit related to the accordion component.
- **Jira:**  [CDEP-303](https://jira.scania.com/browse/CDEP-303)    
1. Accordion header as a heading
Inspect the element structure in the browser dev tools.
Ensure the button is inside an element with role="heading".
Verify it has an appropriate aria-level matching the document hierarchy.
- Not that I have hear added aria-level="3" as an arbitrary value. Perhaps we want the developer themselves decide this? 
(Please give us you input!)
2. Accordion button linked to the panel
Check that the accordion button has an aria-controls attribute.
Confirm that aria-controls references the correct panel ID.
3. Accordion panel identification
Ensure …

feat(accordion): accessibility improvement 

---

packages/core/src/components/card/card.tsx

refactor code to be more reactive
- **Jira:** Add ticket number after `Ternary operators in class, card.tsx`: [CDEP-230](https://jira.scania.com/browse/CDEP-230)
1. Go to... storybook
2. Toggle... stretch, above/below
3. Inspect...

chore(card): refactor ternary operators to be more reactive

---

packages/core/src/components/badge/badge.tsx

- **Jira:**`CDEP-253 ternary operators badge.tsx`: [CDEP-253](https://jira.scania.com/browse/CDEP-253)
2. Play with controls

chore(badge): refactor ternary operators

---

packages/core/src/components/textarea/textarea.tsx

- **Jira:**`Textarea - ternary operators in class names`: [CDEP-251](https://jira.scania.com/browse/CDEP-251)
1. Go to Textarea in story book
2. Play with controls connected to class names

chore(textarea): refactor ternary operators

---

packages/core/src/components/footer/footer.tsx

ternary operators refactor
- **Jira:** `Footer - ternary operators in class name`: [CDEP-234](https://jira.scania.com/browse/CDEP-234)
2. Inspect element, see that class variants are working as expected

chore(footer): ternary operators refactor

---

packages/core/src/components/checkbox/checkbox.tsx

chore(checkbox): added missing type

---

packages/core/src/components/message/message.tsx

- **Jira:** `Message - ternary operators in class names`: [CDEP-238](https://jira.scania.com/browse/CDEP-238)
2. Play with controls connected to class names

chore(message): refactor ternary operators

---

packages/core/src/components/block/block.tsx

refactor ternary operator, easier to read
- **Jira:** `Block - ternary operators in class names`: [CDEP-233](https://jira.scania.com/browse/CDEP-233)
1. Go to storybook, and double check nothing is breaking

chore(block): refactor ternary operator, easier to read

---

packages/core/src/components/popover-core/popover-core.tsx

chore(popover-core): missing types

---

packages/core/src/components/modal/modal.tsx

- **Jira:** `Modal - ternary operators in class name`: [CDEP-239](https://jira.scania.com/browse/CDEP-239)
1. Go to modal
2. Play with controls to show/hide modal

chore(modal): refactor ternary operators

---

packages/core/src/components/button/button.tsx

- **Jira:** `Button - ternary operators in class names`: [CDEP-231](https://jira.scania.com/browse/CDEP-231) 
1. Go to button in storybook
2. Test mode variants

chore(button): refactor ternary operators

---

packages/core/src/components/tabs/folder-tabs/folder-tab/folder-tab.tsx
packages/core/src/components/tabs/inline-tabs/inline-tab/inline-tab.tsx
packages/core/src/components/tabs/navigation-tabs/navigation-tabs.tsx

refactor ternary operators in class names
- **Jira:** `Tabs - ternary operators in class names`: [CDEP-249](https://jira.scania.com/browse/CDEP-249)
1. Go to storybook for tabs
2. Test controls connected to class names

chore(tabs): refactor ternary operators

---

packages/core/src/utils/axeHelpers.ts

chore(helper): remove linter warning

---

packages/core/src/components/dropdown/dropdown.tsx

- **Jira:** `Dropdown - ternary operators in class names`: [CDEP-292](https://jira.scania.com/browse/CDEP-292)
1. Check that dropdown behaviour is not broken

chore(dropdown): refactor ternary operators

---

packages/core/src/components/badge/badge.stories.tsx
packages/core/src/components/badge/badge.tsx
packages/core/src/components/badge/readme.md
packages/core/src/components/badge/test/basic/badge.axe.ts

The pull request addresses the issues we have found in the a11y audit related to the badge component.
✅ Added analyze test file to component
✅ Made sure screen readers are notified when the badge value changes
✅ Added clear context when badge is empty
✅ Make decorative elements not interfere with screen readers
✅ Handling numbers over 99 for screen readers
- **Jira:**  [CDEP-299](https://jira.scania.com/browse/CDEP-299)    
**Scenario: Screen readers are notified when the badge value changes**
1. Go to aws link
2. Use a screen reader (VoiceOver for Mac) and load the badge component.
-  I managed to get this to work with firefox & Voiceover. (Arc browser did not work so there seem to be working with only some browsers. At least we can confirm it does …

feat(badge): accessibility improvements

---

packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/dropdown/readme.md
packages/core/src/components/dropdown/test/basic/dropdown.e2e.ts

- Added new `value` prop to support controlled component behavior, allowing external control of the dropdown's selected value(s)
- Introduced private `selectedOptions` state to better manage internal selection state, improving separation between external value representation and internal state management
- Improved state management by consolidating selection logic into `updateDropdownState` method
- Added validation for selected values to ensure they match available options
- Enhanced multiselect handling with proper array normalization
- Improved type safety and error handling for value changes
- Added warning for invalid option values
- Maintains backward compatibility with existing `defaultValue` prop for uncontrolled behavior and methods (`setValue`, `reset`, `removeValue`).
- …

feat(dropdown): value prop for two way data binding

---

packages/core/src/components/divider/test/divider.axe.ts

Added accessibility test for Divider component
- **Jira:** Coming soon
1. Go to amplify
2. Check accessibility tab has no violations on divider component

feat(divider): added accessibility test for divider

---

packages/core/src/components/spinner/test/standard/spinner.axe.ts

Added accessibility test for Divider component
- **Jira:** Coming soon
1. Go to amplify
2. Check accessibility tab has no violations on divider component

feat(spinner): added accessibility test

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx

This PR was originally opened by @acivgin. However, the branch name didn’t clearly convey the purpose of the improvements, so I’ve created a new PR that includes these changes under a more descriptive name. 
Adds initial state variables and add defensive checks.
1. Open aws link
2. Go to dropdown component
3. Make sure it works as expected.

refactor(dropdown-option): initialize state variables and add defensive checks

---

spacing/_units.scss

Creating new spacing variables for Tegel
- **Jira:** Add ticket number after `CDEP-`: [CDEP-395](https://jira.scania.com/browse/CDEP-395)
1. Go to Figma [file](https://www.figma.com/design/oXyzzbDmusEfy6GWIbyEEw/TRATON-UI-Kit-(Frozen)?m=auto&node-id=0-1&vars=1)
2. Check units value and confirm they match one in PR.
Note: All values are prefixed with --tds2 and will be renamed to --tds in later stages of project. This is just temporarily to avoid conflicts. Possibly there is none, but just to be on safe side.

feat(spacing): new brand units for tegel

---

color/_traton-color-primitives.scss

New brand primitives for Tegel
- **Jira:** [CDEP-397](https://jira.scania.com/browse/CDEP-397)
1. Check the [Figma file](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?m=auto&node-id=0-1&vars=1).
2. Compare color names and values and make sure they match.

feat(color): new brand primitives for Traton

---

color/_traton-usage-tokens.scss

New usage tokens for Traton variables project
- **Jira:** [CDEP-398](https://jira.scania.com/browse/CDEP-398)
1. Open Figma file
2. Compare Brand usage tokens with values in [Figma file](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?m=auto&node-id=0-1&vars=1&var-id=25-3164)

feat(color): traton usage tokens

---

packages/core/src/components/tabs/folder-tabs/folder-tab/folder-tab.tsx
packages/core/src/components/tabs/folder-tabs/folder-tabs.stories.tsx
packages/core/src/components/tabs/folder-tabs/folder-tabs.tsx
packages/core/src/components/tabs/folder-tabs/readme.md
packages/core/src/components/tabs/inline-tabs/inline-tab/inline-tab.tsx
packages/core/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
packages/core/src/components/tabs/inline-tabs/inline-tabs.tsx
packages/core/src/components/tabs/inline-tabs/readme.md
packages/core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.tsx
packages/core/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx
packages/core/src/components/tabs/navigation-tabs/navigation-tabs.tsx
packages/core/src/components/tabs/navigation-tabs/readme.md
packages/core/src/components/tabs/test/folder-tabs/folder-tabs.axe.ts
packages/core/src/components/tabs/test/folder-tabs/index.html
packages/core/src/components/tabs/test/inline-tabs/index.html
packages/core/src/components/tabs/test/inline-tabs/inline-tab.axe.ts
packages/core/src/components/tabs/test/navigation-tabs/index.html
packages/core/src/components/tabs/test/navigation-tabs/navigation-tabs.axe.ts
packages/core/src/utils/axeHelpers.ts

Added accessibility tests
Added  `role="tablist"`
Added warnings when slotted interactive elements does not include correct `role` & `aria-controls`-reference
- **Jira:**: [CDEP-427](https://jira.scania.com/browse/CDEP-427)
1. Go to amplify link
2. Inspect tabs to see that it has all the dynamic (like disabled) aria attributes, reference:
https://docs.google.com/document/d/1i9-JiIbDUV9-M7pJEWETIwdwAEt8xPvQtlx7oW773rU/edit?pli=1&tab=t.msvl34j47v68

feat(tabs): improved accessibility

---

packages/core/src/tokens/README.md

Adding empty tokens dir for token sync from Figma. 
- **No issue:** We need this empty dir path in place for design to be able to sync from Figma.

chore(tokens): scaffold empty tokens directory

---

typography/tokens/_typography-traton.scss

Typography tokens for Traton
- **Jira:** [CDEP-401](https://jira.scania.com/browse/CDEP-401)
1. Go to this [Figma file](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?m=auto&node-id=0-1&vars=1&var-id=731-28724)
2. Verify the tokens match

feat(typography): tokens for Traton

---

spacing/_radius.scss
spacing/_traton-units.scss

Adding units for Traton
- **Jira:** [CDEP-512](https://jira.scania.com/browse/CDEP-512)
Go to [Figma file](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/branch/yM7ReLbGXBF0UdtmgZdBMd/TRATON-Component-Library?m=auto&node-id=0-1&t=kveX4eVI2rlxnAZS-1)

feat(units): adding units for Traton

---

packages/core/src/components/dropdown/dropdown.tsx

After last [release](https://github.com/scania-digital-design-system/tegel/releases/tag/%40scania%2Ftegel%401.26.0) and the updates to the dropdown a bug was raised [here](https://github.com/scania-digital-design-system/tegel/issues/1086) this fix takes care of it. 
- **Jira:** [CDEP-483](https://jira.scania.com/browse/CDEP-483)
2. Check in Dropdown verify it works.
3. Added test PR's in demo pages [here](https://github.com/scania-digital-design-system/tegel-angular-17-demo/pull/43) and [here](https://github.com/scania-digital-design-system/tegel-react-demo/pull/224) also using the beta release I made for this fix.

fix(dropdown): initial value not being selected on load

---

package.json

As discussed in a dev-checkin. this PR aims to clarify commit messages descriptions.

docs(package.json): enhance commit message descriptions for clarity

---

.github/CODEOWNERS

Adding Patrik as codeowner for Tegel
_Describe what the pull-request is about_
1. Go to...
2. Check in...
3. Run ...

chore: add user to codeowner

---

packages/core/src/components/datetime/datetime.tsx
packages/core/src/components/datetime/test/disabled/datetime.axe.ts
packages/core/src/components/datetime/test/error/datetime.axe.ts
packages/core/src/components/datetime/test/error/datetime.e2e.ts
packages/core/src/components/datetime/test/success/datetime.axe.ts

Added additional accessibility tests
- **Jira:**
1. check that all actions pass

test(datetime): accessibility tests

---

packages/core/src/components/button/test/danger/button.axe.ts
packages/core/src/components/button/test/disabled/button.axe.ts
packages/core/src/components/button/test/ghost/button.axe.ts
packages/core/src/components/button/test/icon/button.axe.ts
packages/core/src/components/button/test/icon/index.html
packages/core/src/components/button/test/secondary/button.axe.ts

Added remainder of accessibility tests for button component
- **Jira:** 

test(button): added more accessibility tests

---

packages/core/src/components/card/test/clickable/card.axe.ts
packages/core/src/components/card/test/clickable/index.html
packages/core/src/components/card/test/default/card.axe.ts
packages/core/src/components/card/test/default/index.html

Adding additional axe tests for card component
- **Jira:** 

test(card): added additional accessibility tests

---

README.md

Old version of Node mentioned
- **No issue:** Updating README.md with correct Node version.

fix(readme): update to correct version of node in reamde text

---

packages/core/src/components/slider/slider.stories.tsx
packages/core/src/components/slider/slider.tsx

- Support for decimal numbers in Slider component.
- Support `step` prop always, not only when `showControls` is enabled. 
- Replace use of `parseInt` with `parseFloat` to allow floats.
- Introduce helper function `roundToStep`, for rounding of numbers with the precision specified in `step` prop.
-  Replacing use of Math.round to above mentioned helper to allow for rounding without loosing decimals.
- **Jira:** : [CDEP-702](https://jira.scania.com/browse/CDEP-702)
1. Go to slider component in Storybook.
2. Use 'step' prop to allow for decimals like so: step = 0.1 should allow for one decimal, step …

feat(slider): allow float numbers

---

packages/core/src/components/message/message.tsx
packages/core/src/components/message/test/error/index.html
packages/core/src/components/message/test/error/message.axe.ts
packages/core/src/components/message/test/information/index.html
packages/core/src/components/message/test/information/message.axe.ts
packages/core/src/components/message/test/success/index.html
packages/core/src/components/message/test/success/message.axe.ts
packages/core/src/components/message/test/warning/index.html
packages/core/src/components/message/test/warning/message.axe.ts

Added additional accessibility tests for message component
- **Jira:** 
1. Check that actions passes

test(message): adding additional accessibility tests

---

packages/core/src/components/chip/test/disabled/chip.axe.ts
packages/core/src/components/chip/test/icon/chip.axe.ts
packages/core/src/components/chip/test/icon/chip.e2e.ts
packages/core/src/components/chip/test/icon/index.html

Added additional accessibility tests for chip component
- **Jira:** 

test(chip): added additional accessibility tests

---

packages/core/src/components/text-field/test/disabled/text-field.axe.ts
packages/core/src/components/text-field/test/focus/text-field.axe.ts
packages/core/src/components/text-field/test/password-error/text-field.axe.ts
packages/core/src/components/textarea/test/basic/index.html
packages/core/src/components/textarea/test/basic/textarea.axe.ts
packages/core/src/components/textarea/test/read-only/textarea.axe.ts
packages/core/src/components/textarea/textarea.tsx

Added additional accessibility tests for text-field & text-area components
- **Jira:**

test(text-field): added additional accessibility tests

---

packages/core/src/components/toast/test/error-with-slots/index.html
packages/core/src/components/toast/test/error-with-slots/toast.axe.ts
packages/core/src/components/toast/test/information/index.html
packages/core/src/components/toast/test/success-empty-action-slot/index.html
packages/core/src/components/toast/test/success-empty-action-slot/toast.axe.ts
packages/core/src/components/toast/test/warning-not-closable/index.html
packages/core/src/components/toast/test/warning-not-closable/toast.axe.ts
packages/core/src/components/toast/toast.tsx

Added additional accessibility test for toast component
- **Jira:**

test(toast): added additional accessibility tests

---

packages/core/src/components/accordion/test/disabled/accordion.axe.ts
packages/core/src/components/banner/test/default/banner.axe.ts
packages/core/src/components/banner/test/error/banner.axe.ts
packages/core/src/components/banner/test/information/banner.axe.ts
packages/core/src/components/checkbox/test/disabled/checkbox.axe.ts
packages/core/src/components/checkbox/test/indeterminate/checkbox.axe.ts
packages/core/src/components/radio-button/test/disabled/radio-button.axe.ts
packages/core/src/components/side-menu/test/collapsible/index.html
packages/core/src/components/side-menu/test/collapsible/side-menu.axe.ts
packages/core/src/components/slider/test/disabled/index.html
packages/core/src/components/slider/test/disabled/slider.axe.ts
packages/core/src/components/slider/test/read-only/index.html
packages/core/src/components/slider/test/read-only/slider.axe.ts
packages/core/src/components/toggle/test/disabled/toggle.axe.ts
packages/core/src/components/tooltip/test/click/tooltip.axe.ts
packages/core/src/components/tooltip/test/disabled/tooltip.axe.ts

Added remainder of accessibility test for component (broken down in commits).
- **Jira:** 
2. double check naming of files and functions :)

test: accessibility tests

---

packages/core/src/global/global.scss

Adding missing import of primitives
- **No issue:** Missing import of primitives, notices while working
1. Hard to test as no components has new ("changed") tokens. Just import of file in global.scss is sufficient proof.

fix(color): import of new primitives

---

packages/core/src/components/textarea/textarea.tsx

Previously, `handleInput` incorrectly checked for `HTMLInputElement`,
causing textarea value not to update on input.
This broke the character counter and reactive behavior.
Fixed by checking for `HTMLTextAreaElement` instead.
- **Jira:**: [CDEP-715](https://jira.scania.com/browse/CDEP-715) & [CDEP-816](https://jira.scania.com/browse/CDEP-816)
1. Go to `textarea` component in storybook.
2. Set a `maxLength` for the textarea.
3. Type in the textarea and confirm that the 'counter' updates.
Before: 
After: 
[CDEP-715]: https://tegel.atlassian.net/browse/CDEP-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

fix(textarea): update value on input to fix counter & reactive issues

---

packages/core/src/components/checkbox/checkbox-vars.scss
packages/core/src/components/checkbox/checkbox.scss

Added new colors for checkbox component

fix(checkbox): added new colors for contrast

---

packages/core/src/components/toggle/toggle-vars.scss
packages/core/src/components/toggle/toggle.scss

Added new colors for contrast to toggle component

fix(toggle): added new colors for contrast

---

packages/core/src/components/divider/divider-vars.scss

fix(divider): added colors for contrast

---

packages/core/.storybook/main.ts

_Describe what the pull-request is about_
1. Go to...
2. Check in...
3. Run ...

chore(vite): fix HMR by overriding Vite build output to avoid dist conflicts

---

packages/core/src/components/footer/footer-group/footer-group.scss
packages/core/src/components/footer/footer-item/footer-item.scss
packages/core/src/components/footer/footer-vars.scss

Added new colors to footer for contrast

fix(footer): color contrast

---

packages/core/src/components/banner/banner-vars.scss

Updates for banner color contrasts

fix(banner): update colors for improved contrast

---

packages/core/src/components/card/card-vars.scss

fix(card): update color variables for improved contrast

---

packages/core/src/components/toast/toast-vars.scss
packages/core/src/components/toast/toast.scss

Updated the color contrast to toast to comply with accessibility

fix(toast): update colors for contrast and improve accessibility

---

packages/core/src/components/message/message-vars.scss
packages/core/src/components/message/message.scss
packages/core/src/components/modal/modal-vars.scss
packages/core/src/components/modal/modal.scss
packages/core/src/components/spinner/spinner-vars.scss
packages/core/src/components/spinner/spinner.scss
packages/core/src/global/global.scss

Updating message, modal, spinner css code to follow CSS convention we discussed and implemented on block component last week. 
- **No issue:** Updating files according to convention
1. Check if CSS variables are separated according to convention
2. Check that components are getting all colors in place after update

fix(message, modal, spinner): convention update

---

packages/core/src/components/chip/chip-vars.scss
packages/core/src/components/chip/chip.scss

Fix(chip): color contrast

---

color/_scania-brand-usage.scss
packages/core/src/components/button/button-vars.scss
packages/core/src/components/button/button.scss
packages/core/src/mixins/_focus-state.scss

Update the color for button to increase contrast for better accessibility

fix(button): update focus styles and improve accessibility

---

packages/core/.storybook/preview.ts
packages/core/src/components/accordion/readme.md
packages/core/src/components/datetime/readme.md
packages/core/src/components/dropdown/readme.md
packages/core/src/components/header/readme.md
packages/core/src/components/modal/readme.md
packages/core/src/components/popover-canvas/readme.md
packages/core/src/components/popover-menu/readme.md
packages/core/src/components/side-menu/readme.md
packages/core/src/components/slider/readme.md
packages/core/src/components/table/table-component-basic.stories.tsx
packages/core/src/components/table/table.accessibility.md
packages/core/src/components/table/table/readme.md
packages/core/src/components/tabs/folder-tabs/readme.md
packages/core/src/components/tabs/inline-tabs/readme.md
packages/core/src/components/tabs/navigation-tabs/readme.md
packages/core/src/stories/foundations/accessibility/accessibility.mdx
packages/core/src/stories/foundations/color/colors.mdx

Documentation for accessibility in Storybook

docs(storybook): add 'Accessibility' section to preview

---

.github/CODEOWNERS

Added @NordbergAnna as code owner

ci(codeowner): added new member

---

TRATON-README.md
packages/core/.storybook/main.ts
packages/core/.storybook/preview.ts
packages/core/src/stories/Introduction/traton-setup.mdx

- **Jira:** [CDEP-854](https://jira.scania.com/browse/CDEP-854)
2. Verify that readme is visible under Introduction section.

feat: added multibrand readme

---

packages/core/src/components/toast/toast-vars.scss
packages/core/src/components/toast/toast.scss

Toast component using new multibrand tokens
- **Jira:** [CDEP-766](https://jira.scania.com/browse/CDEP-766)
1.Go to preview link
2.Compare Toast component styles in both Scania and Traton, in both light and dark modes with [Traton UI Kit: Toast](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=3799-109929&m=dev)

feat(toast): added multibrand tokens

---

packages/core/src/components/toggle/toggle-vars.scss
packages/core/src/components/toggle/toggle.scss

Fixed vars file
1. Check code
2. Compare to [Figma](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=35264-124913&m=dev)

fix(toggle): fix toggle vars file

---

packages/core/src/components/toast/toast.scss

Test without !important
- **Jira:**`remove !important`: [CDEP-1107](https://jira.scania.com/browse/CDEP-1107)
1. Test in beta/demo page
2. Confirm that font is not overwritten by CSS reset

fix(toast): removed important and aligned with figma

---

.gitignore

chore: update .gitignore to include cursor directory

---

packages/core/src/global/tegel-light-components.scss
packages/core/src/tegel-light/components/tl-link/_tl-link-vars.scss
packages/core/src/tegel-light/components/tl-link/tl-link.scss
packages/core/src/tegel-light/components/tl-link/tl-link.stories.tsx

A tegel light link component
[CDEP-973](https://jira.scania.com/browse/CDEP-973)
1. Go to preview link and navigate to tegel light and the Link component
3. Check Docs to see how styles are implemented with classes

feat(tegel-light): added tl-link component

---

packages/core/src/global/tegel-light-components.scss
packages/core/src/tegel-light/components/tl-text-field/_tl-text-field-mixins.scss
packages/core/src/tegel-light/components/tl-text-field/_tl-text-field-vars.scss
packages/core/src/tegel-light/components/tl-text-field/tl-text-field.scss
packages/core/src/tegel-light/components/tl-text-field/tl-text-field.stories.tsx

Tegel light text field component
[CDEP-1190](https://jira.scania.com/browse/CDEP-1190)
1. Go to preview link and navigate to tegel light and the text field component
3. Check Traton/Scania
4. Check Docs to see how styles are implemented with classes
[Figma link](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=26756-59844&p=f&m=dev)

feat(tegel-light): added tl-text-field component

---

packages/core/src/stories/foundations/color/colors.mdx

Fixes the incorrect names of the variables that were previously set.
- **Jira:** [CDEP-1167](https://jira.scania.com/browse/CDEP-1167) 
Nothing to test
None
None

fix(documentation): fix incorrect names of color variables

---

packages/core/src/global/tegel-light-components.scss
packages/core/src/tegel-light/components/tl-textarea/_tl-textarea-vars.scss
packages/core/src/tegel-light/components/tl-textarea/tl-textarea-mixins.scss
packages/core/src/tegel-light/components/tl-textarea/tl-textarea.scss
packages/core/src/tegel-light/components/tl-textarea/tl-textarea.stories.tsx

Created tegel light textarea component
[CDEP-1191](https://jira.scania.com/browse/CDEP-1191)
1. Go to preview link and navigate to tegel light and the textarea component
3. Check Traton/Scania
4. Check Docs to see how styles are implemented with classes
[figma link](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=13890-22053&m=dev)

feat(tegel-light): added tl-textarea component

---

packages/core/src/global/tegel-light-components.scss
packages/core/src/tegel-light/components/tl-toggle/_tl-toggle-vars.scss
packages/core/src/tegel-light/components/tl-toggle/tl-toggle.scss
packages/core/src/tegel-light/components/tl-toggle/tl-toggle.stories.tsx

A tegel light toggle component.
[CDEP-1325](https://jira.scania.com/browse/CDEP-1325)
1. Go to preview link and navigate to tegel light and the toggle component
3. Check Traton/Scania
4. Check Docs to see how styles are implemented with classes
[Figma link](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=26756-59846&p=f&t=5BvyYFrSTnC8PasH-0)

feat(tegel-light): added tl-toggle component

---

packages/core/src/global/tegel-light-components.scss
packages/core/src/tegel-light/components/tl-accordion/_tl-accordion-vars.scss
packages/core/src/tegel-light/components/tl-accordion/tl-accordion-item/tl-accordion-item.scss
packages/core/src/tegel-light/components/tl-accordion/tl-accordion.scss
packages/core/src/tegel-light/components/tl-accordion/tl-accordion.stories.tsx

Create tegel light accordion component
[CDEP-1218](https://jira.scania.com/browse/CDEP-1218)
1. Go to preview link and navigate to tegel light and the accordion component
3. Check Traton/Scania
4. Check Docs to see how styles are implemented with classes
[Figma link](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=26408-59506&p=f&m=dev)
Dark mode behavior needs update from design - link to jira ticket here:
[CDEP-1360](https://jira.scania.com/browse/CDEP-1360)

feat(tegel-light): added tl-accordion component

---

packages/core/src/components/text-field/text-field.tsx
packages/core/src/components/textarea/textarea.tsx
packages/core/src/utils/getAriaInvalid.ts

A user [reported an issue](https://github.com/scania-digital-design-system/tegel/issues/1452) requesting that aria-invalid be forwarded to the internal <textfield> component and correctly accept both boolean and string values. Specifically, the user wants to be able to pass "true"/"false" as strings, as well as true/false as booleans in React.
Currently, we apply aria-invalid directly on the textarea component using a state-based approach:
`aria-invalid={this.state === 'error' ? 'true' : 'false'}`
To support aria-invalid consistently across the repository, we propose a unified approach. This PR introduces a standard method for handling aria-invalid throughout the codebase.
As part of this change, the textarea component has been updated to follow the same unified approach.
- **Jira:** …

feat(aria-invalid) Forward aria invalid to inputs

---

packages/core/src/tegel-light/components/tl-card/tl-card.scss
packages/core/src/tegel-light/components/tl-card/tl-card.stories.tsx

When I was trying to use the card component inside a real demo project (outside storybook) I noticed some layout issues.
The first thing is that, the card is a modular component and its size should be inherited by its parent wrapper.
Since we didn’t have height/width: 100%(which I’m now introducing in this PR), it didn’t really adjust its size to the parent size. It just adjusted itself after the amount of content it has (paragraph, header etc…)
Please look at these screenshots. The red background color is the wrapper/parent of the card component with a fixed width and height. I also have some padding on the wrapper if you're wondering why the card component it isn't 100% sized
Before:
After:
And the reason I’m introducing flex is because the actions-row of the card didn’t position itself …

fix(tl-card): fixed layout issue

---

packages/core/src/tegel-light/components/tl-checkbox/tl-checkbox.scss
packages/core/src/tegel-light/components/tl-table/_tl-table-vars.scss
packages/core/src/tegel-light/components/tl-table/tl-table-component-basic.stories.tsx
packages/core/src/tegel-light/components/tl-table/tl-table-component-multiselect.stories.tsx
packages/core/src/tegel-light/components/tl-table/tl-table-component-zebra.stories.tsx
packages/core/src/tegel-light/components/tl-table/tl-table.scss

This is a PR for the tl-table multiselect
[CDEP-1467](https://jira.scania.com/browse/CDEP-1467)
1. Go to preview link and navigate to tegel lite -> [multiselect](https://pr-1470.d3fazya28914g3.amplifyapp.com/?path=/story/tegel-light-css-table-multiselect--default)
3. Check multibrand switch 
4. Compare design to [Traton UI figma file](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=35259-124876&p=f&m=dev) (table not dev ready) and [preview link](https://feat-design-tokens-multibrand.d3fazya28914g3.amplifyapp.com/?path=/story/components-table-multiselect--default) for multibrand branch table
Since table is not dev ready in figma I suggest an approach of combined check of figma and preview link for the design …

feat(tegel-lite): added table multiselect component
