core/src/global/global.scss

- Fixes wrong color css path that caused build to crash
- Updates the path to use unbuilt scss files to not require building other packages.

fix: update color and grid path

---

.github/CODE_STYLE.md
core/src/components/banner/sdds-banner.tsx
core/src/components/block/sdds-block.tsx
core/src/components/button/button.tsx
core/src/components/checkbox/sdds-checkbox.tsx
core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.tsx
core/src/components/dropdown-v2/dropdown-v2.tsx
core/src/components/footer/webcomponent/sdds-footer-group/sdds-footer-group.tsx
core/src/components/footer/webcomponent/sdds-footer-item/sdds-footer-item.tsx
core/src/components/footer/webcomponent/sdds-footer.tsx
core/src/components/link/sdds-link.tsx
core/src/components/radio-button/radio-button.tsx
core/src/components/stepper/sdds-stepper.tsx
core/src/components/tabs/inline-tabs/inline-tabs.tsx
core/src/components/toast/sdds-toast.tsx
core/src/components/toggle/sdds-toggle.tsx

Removed HostElement import from `'@stencil/core/internal';` as it is no longer a part of it. Changed it to using htmlelement instead. Also moved declaration to top of file as per styleguide.
Fixes: [DTS-1669](https://tegel.atlassian.net/browse/DTS-1669)
1. Go to...
2. Check in...
3. Run ...
[DTS-1669]: https://tegel.atlassian.net/browse/DTS-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(components): changed from hostelement to htmlelement

---

core/src/components/button/button.scss
core/src/components/button/button.stories.tsx
core/src/components/button/button.tsx

* Removed the underlying slot in the button
* Added pointer-events non to the sdds-icon slot
* Made the underlying button disabled
Note: This PR only make the icon non-clickable using CSS. We should add some underlying JS to make it a bit more secure.
Fixes: #
1. Go to storybook link below
2. Check in Components -> Button
3. Click the button and check the log for the event
4. Disable the button
5. Click the button and check that there are no new logs

fix(button): made the button non-clickable when disabled

---

core/src/components/button/button.scss

Updated the margin-left value on the sdds-icon in the button to represent the latest changes in figma. Removed the fullbleed specific icon margin rules since they should always be the same.
Fixes: https://tegel.atlassian.net/browse/DTS-1550
1. Go to storybook link below.
2. Check in Components -> Button
3. Add an icon and make sure it has the correct margin-left.

fix(button): updated margin-left on sdds-icon inside btn, removed rules for fullbleed

---

core/src/stories/foundations/typography/typography-body.stories.tsx
core/src/stories/foundations/typography/typography-detail.stories.tsx
core/src/stories/foundations/typography/typography-headline.stories.tsx
core/src/stories/foundations/typography/typography-paragraph.stories.tsx
typography/scania-fonts-selectors.scss
typography/scania-fonts-vars.scss

Updated prefixes in typography to `tds`, updated to stories to correspond with the new prefix.
Fixes: https://tegel.atlassian.net/browse/DTS-1613
1. Check out the branch and run storybook locally.
2. Check in Foundations ->. Typography
3. Check that the fonts are correct.
Note: This does PR does not update any components using our css-variables.

feat(typography): prefix change

---

color/_color.scss
color/package.json
core/src/stories/foundations/color/color-brand.stories.tsx
core/src/stories/foundations/color/color-scales.stories.tsx
core/src/stories/foundations/color/color-semantic.stories.tsx
globals.scss

Changing prefix in color package
Fixes: DTS-1555
2. Check if Color stories still render colors, now with -tds prefix instead -sdds
A prefix change happened in the globals file which affect the grid too, so the grid might appear broken. It will be fixed in another PR.

feat(color): prefix change

---

core/src/components/button/button.scss
core/src/components/button/button.tsx
core/src/components/button/readme.md
core/src/utils/utils.ts

* Disabled button is no longer clickable. It will do nothing on click.
* Scss file cleanup in button
**Should we also expose a default slot that people can use instead of the text prop? We would need to do some check if that slot has any content in connectedCallback to be able to set onlyIcon to true it the slot is empty and there is no text prop.**
Fixes: https://tegel.atlassian.net/browse/DTS-1671
1. Go to storybook link below
2. Check in Components -> Button
3. Check the log on a disabled button and make sure nothing is emitted.
4. Check the overall style of the button.

fix(button): made disabled button non-clickable

---

core/src/global/_logotypes.scss

Made the logotype variables use the prefix const.
Fixes: https://tegel.atlassian.net/browse/DTS-1616
Could be tested by validating the the old scss variables doesn't exist any more. The footer uses the scania wordmark, which will not show since the variable has changed.

feat(logotype): used prefix const

---

core/src/components/badge/badge.stories.tsx
core/src/components/badge/badges.scss
core/src/components/badge/badges.tsx
core/src/components/badge/readme.md
core/src/stories/Migration/Migration.stories.mdx

- Updated the prefix for the badge componet.
- Renamed it to conform with singular naming convention.
- Removed previously deprecated **isSmall** prop.
Fixes: https://tegel.atlassian.net/browse/DTS-1624
2. Check in Component -> Badge
3. Check the styling and the API.

feat(badge) prefix change

---

core/src/components/toggle/readme.md
core/src/components/toggle/sdds-toggle.stories.tsx
core/src/components/toggle/sdds-toggle.tsx

Updated comments and docs to always use singular capitalized case when referencing the component.
Part of: https://tegel.atlassian.net/browse/DTS-1329
2. Check in Components -> Toggle
3. Make sure it is always referenced with singular capital case (Toggle)

chore(toggle): use singular Capital Case where possible

---

core/src/components/checkbox/checkbox-vars.scss
core/src/components/checkbox/checkbox.scss
core/src/components/checkbox/checkbox.stories.tsx
core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/readme.md
core/src/components/dropdown-v2/dropdown-option-v2/dropdown-option-v2.tsx

Updated the prefix for the checkbox. Also updated the event type that was imported in the dropdown-option-v2, the import needed to be updated in this PR otherwise it would not have been able to build correctly. Also updated the components file names.
Fixes: https://tegel.atlassian.net/browse/DTS-1630
2. Check in Components -> Checkbox
3. Check the prefix and the overall style of the component.

feat(checkbox): prefix change

---

core/src/components/dropdown-v2/dropdown-vars.scss
core/src/components/message/message-vars.scss
core/src/components/textarea/textarea-vars.scss
core/src/components/toast/toast-vars.scss
core/src/components/toggle/toggle-vars.scss

Added root selector to get light mode by default. We were missing this on some components, which lead to variables being undefined if the user had not put sdds-mode-light as class anywhere.
Fixes: https://tegel.atlassian.net/browse/DTS-1757
2. Remove the wrapping sdds-mode-light class
3. Check that the toggle is using light mode by default.

fix(toggle/toast/textarea/message/dropdown-v2): added root selector to get light mode by default

---

core/src/components/textarea/readme.md
core/src/components/textarea/textarea.stories.tsx
core/src/components/textarea/textarea.tsx

Making sure Textarea is spelled in a capital case.
Fixes: DTS-1329
1. Check if all textarea is mentioned as "Textarea" in docs files

docs(textarea): singular capital case

---

core/src/components/icon/icon-font.stories.tsx
core/src/components/icon/icon-web-component.stories.tsx

Update icon size controls to be a select instead of range.
Fixes: https://tegel.atlassian.net/browse/DTS-1758
2. Check in Foundations -> Icons
3. Check the controls for the size.

docs(icon size): updated icon size control to be select instead of range

---

core/src/components/header/header-brand-symbol/header-brand-symbol.scss
core/src/components/header/header-brand-symbol/header-brand-symbol.tsx
core/src/components/header/header-brand-symbol/readme.md
core/src/components/header/header.stories.tsx
core/src/components/side-menu/side-menu.stories.tsx
core/src/stories/patterns/navigation/navigation-basic.stories.tsx
core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx

Updated the header-brand-symbol to use slot instead of prop for link. This is to allow for framework routers.
Fixes: https://tegel.atlassian.net/browse/DTS-1780
2. Check in Components -> Header
3. Test and check the style of the brand-symbol (top right corner.)

feat(header): brand link

---

core/src/components/badge/badge.tsx
core/src/components/banner/banner.tsx
core/src/components/toast/toast.tsx

Adds the reflect flag to the hidden prop. This is inorder to bind a value to the attribute
Fixes: issue find in manual testing.
2. Check in Components -> Banner/Badge/Toast
3. Try hiding the component and make sure it still works

fix(banner/badge/toast): reflect hidden prop

---

core/src/components/button/button.scss
core/src/components/button/button.tsx
core/src/utils/utils.ts

Possible fix for the forever-lasting disabled state of the button.
When the button is set statically to a disabled state on the initial load, it seems to remain in it.
connectedCallback is run only once, on the initial load so the component is not aware of the change of "disabled" prop change. We add click listener on it, but do not remove it which makes the button remain in the disabled state even when disabled is false.
Martin and I took a look and proposed a solution where we remove logic that sets it disabled via stoppingPropagation and preventingDefault. Now button uses only CSS rule of pointer-events:none and we leave it up to user to stopPorpagation or preventDefault. 
Not sure if is this testable without a release, …

fix(button): locked in disabled state

---

core/src/components/link/link.scss
core/src/components/link/link.tsx

Sets the display of the link to inline so that it can be used in text blocks. Also did shadowDOM; true and updated the css.
Fixes: 
1. Checkout the branch
2. Add the link in flowing text
3. Check that the styling and behaviour is correct.

feat(link): display:inline and updated component to use shadowDOM

---

core/src/components/banner/banner.scss
core/src/components/banner/banner.stories.tsx
core/src/components/banner/banner.tsx
core/src/components/banner/readme.md
core/src/utils/utils.ts

Refactored the slot, both names and implementation. 
- Names of slots are now according to convention
- No check for slots are being done in component files
- All conditional rendering was removed and replaced by CSS.
- Added slot documentation.
Fixes: https://tegel.atlassian.net/browse/DTS-1951
2. Check in Components -> Banner
3. Test the controls and see that the style is still correct.

fix(banner): align slots

---

.github/CODE_STYLE.md
core/src/stories/Migration/Migration.stories.mdx

Added section for naming convention in migration docs & in our CODE_STYLES.
Fixes: https://tegel.atlassian.net/browse/DTS-2033
1. Go to migration docs
2. Check the slot naming conventions

docs(slots): documentation for slot naming convention

---

core/src/global/global.scss

Corrected the rules for global background and color.
In the old solution the mode-variants were taking precedence, resulting in dark mode being useless if mode-variant was used.
Fixes: -
2. Do link to react-demo-page
3. Remove everything in index.css from line 18 - 30.
4. Make sure dark/light and primary/secondary works as inteded.

fix(globals): corrected rules for global background and color

---

core/src/components/footer/footer-group/footer-group.scss
core/src/components/footer/footer-group/footer-group.tsx
core/src/components/footer/footer.scss
core/src/components/footer/footer.stories.tsx
core/src/components/footer/footer.tsx
core/src/components/footer/readme.md
core/src/components/header/header-dropdown-list-user/readme.md

- Aligned the naming of the slots in the footer
- Added docs for slots in readme.
Fixes: https://tegel.atlassian.net/browse/DTS-2021
1. Go to Footer
2. Check in Notes
3. Check the slots section
4. Test the top part controls
5. Make sure the styling is correct.
How do we feel about naming here? Are the slots named correctly?

feat(footer): slot alignment

---

core/src/components/tabs/folder-tabs/folder-tabs.tsx
core/src/components/tabs/inline-tabs/inline-tabs.tsx
core/src/components/tabs/navigation-tabs/navigation-tabs.tsx

Adds an if check for disabled state in the event handler for click. This makes sure that the tdsChange is only emitted if the tab in not disabled. This also enables a tab to disabled/enabled in runtime and the functionality will still work. 
Fixes: https://tegel.atlassian.net/browse/DTS-1835
1. Go to Folder/Inline/Navigation Tabs
2. Try clicking the disabled tab.
3. Make sure it doesn't change the content.

fix(tabs): no event emitted on disabled tabs

---

core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
core/src/components/breadcrumbs/breadcrumb/breadcrumb.tsx
core/src/components/breadcrumbs/breadcrumb/readme.md
core/src/components/breadcrumbs/breadcrumbs-vars.scss
core/src/components/breadcrumbs/breadcrumbs.tsx

Removed the logic for checking and added a last class to the last breadcumb and instead implemented CSS to handle this. Also removed the disabled prop since it's only used to show "current" in design.
Fixes: https://tegel.atlassian.net/browse/DTS-2042, https://tegel.atlassian.net/browse/DTS-2043
1. Go to Breadbrumb
2. Check that the styling is correct for all items.

fix(breadcrumbs): last element and disabled corrections

---

core/src/components/table/table-body-row-expandable/readme.md
core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
core/src/components/table/table-component-batch-actions.stories.tsx
core/src/components/table/table-header-cell/readme.md
core/src/components/table/table-toolbar/readme.md
core/src/components/table/table-toolbar/table-toolbar.scss
core/src/components/table/table-toolbar/table-toolbar.tsx

Aligns slot names for the table.
Table toolbar: 
- Renamed "tds-table__actionbar" slot to "end"
- Updated CSS rule to enable people to pass in a container as the slot.
- Used tds icon instead of hardcoded svg.
Table  expanded row:
- Docs for slots
Fixes: https://tegel.atlassian.net/browse/DTS-2025
1. Go to Table -> Filter/Batch Actions
2. Check the styling of the search and the batch actions

feat(table): slot alignment

---

core/src/components/accordion/accordion-item/accordion-item.tsx
core/src/components/accordion/accordion-item/readme.md
core/src/components/accordion/accordion.stories.tsx

Align slot naming as per convention. 
Fixes: [DTS-1950](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1950)
1. Go to Storybook link
2. Check in Components -> Accordion
3. Check Notes tab -> Accordion Item, verify label name is correct. 
[DTS-1950]: https://tegel.atlassian.net/browse/DTS-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(accordion): align slot naming

---

core/src/components/chip/chip.scss

The former css selector didn't allow for people to use the default size (not setting size="lg/sm") on the component. This fixes that, sets the gap to 8px by default and 6px if size="sm".
1. Go to Chip
2. Test the controls for size in combination with/without an icon.

fix(chip): css selector for gap

---

core/src/components/modal/modal.tsx

Enabled closing of modal programatically when preventing event. When the modal is closed using the closeModal method on the component it no longer emitts the tdsClose event.
Fixes: https://tegel.atlassian.net/browse/DTS-1839
1. Check out the branch
2. Prevent the close event and implement your own closing logic using the closeModal method.
4. Make sure the modal closes.

fix(modal): closing programatically without emitting event

---

core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss

Sets the width transition on hover to not the the flashing on page load.
Fixes: https://tegel.atlassian.net/browse/DTS-2006
1. Go to Inline/Navigation Tabs
2. Check the animation on the selected tab on load.
3. It should not transition.

fix(tabs): set transition on hover

---

core/src/components/side-menu/side-menu.scss
core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx

Updated z-index to only take affect on smaller screens. This fixes the issue of a user on small screen opening the side-menu -> making the window bigger -> side-menu now overlaps header.
Fixes: 
**Screenshots**

fix(side-menu): z-index

---

core/src/components/toast/toast.tsx

Updated the hide/showToast methods to not emit tdsClose/tdsShow event.
Fixes: https://tegel.atlassian.net/browse/DTS-1960
1. Check out branch.
2. Prevent default on tdsClose/Show event.
3. Hide/show the toast programatically and make sure it works.

fix(toast): closing programatically without emitting event

---

core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.scss
core/src/components/side-menu/side-menu-vars.scss

Corrected background color of collapsed dropdown.
Fixes: -
1. Go to Side Menu
2. Check the background of the collapsed dropdown.
**Screenshots**

fix(side menu): corrected background color of collapsed dropdown

---

core/src/components/message/message.scss
core/src/components/message/message.tsx
core/src/components/message/readme.md
core/src/components/table/table-toolbar/readme.md

Documented default slot for the extended message section and aligned SCSS classes. 
Fixes: https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1953
1. Go to Storybook.
2. Check in Components -> Message.
3. Test the controls and check the styles.
4. Go to Notes tab and read slot documentation.

feat(message): align slots

---

core/src/components/icon/readme.md
core/src/components/table/table-body/readme.md
core/src/components/table/table-body/table-body.tsx
core/src/components/table/table-component-filtering.stories.tsx
core/src/components/table/table-header-cell/readme.md
core/src/components/table/table-toolbar/readme.md

-  Fixed logic for showing/hiding no result message
- Introduces slot for no result message
- Introduces prop for no result message. 
Fixes: https://tegel.atlassian.net/browse/DTS-2044
1. Go to Table -> Filtering
2. Search for "jp"
3. Check that the no result message works.

feat(table): fixed logic for showing/hiding no result message

---

core/src/components/side-menu/readme.md
core/src/components/side-menu/side-menu-collapse-button/readme.md
core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.tsx
core/src/components/side-menu/side-menu-dropdown-list-item/readme.md
core/src/components/side-menu/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
core/src/components/side-menu/side-menu-dropdown-list/readme.md
core/src/components/side-menu/side-menu-dropdown-list/side-menu-dropdown-list.tsx
core/src/components/side-menu/side-menu-dropdown/readme.md
core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
core/src/components/side-menu/side-menu-item/readme.md
core/src/components/side-menu/side-menu-item/side-menu-item.tsx
core/src/components/side-menu/side-menu-user-image/readme.md
core/src/components/side-menu/side-menu-user-image/side-menu-user-image.tsx
core/src/components/side-menu/side-menu-user/readme.md
core/src/components/side-menu/side-menu-user/side-menu-user.tsx
core/src/components/side-menu/side-menu.stories.tsx
core/src/components/side-menu/side-menu.tsx

Aligning slots naming per our convention
Fixes: [DTS-1957](https://tegel.atlassian.net/browse/DTS-1957)
**What was done:**
- document all slot and their names in readme files
- use `<default>` to indicate those are not named for purpose, can be used for side-menu sub-components ect...
- show the user only Notes they really need to know about (show one used in stories, hide internal ones)
1. Go to Netlify PR preview link
4. Check that the Side-menu component and pattern stories still look and function OK.
[DTS-1957]: https://tegel.atlassian.net/browse/DTS-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(side-menu): slots

---

core/src/components/table/table-body/readme.md
core/src/components/table/table-body/table-body.tsx
core/src/components/table/table-component-batch-actions.stories.tsx
core/src/components/table/table-component-bodydata.stories.tsx
core/src/components/table/table-component-filtering.stories.tsx
core/src/components/table/table-component-multiselect.stories.tsx
core/src/components/table/table-component-pagination.stories.tsx
core/src/components/table/table-component-sorting.stories.tsx
core/src/components/table/table-header-cell/readme.md

BREAKING CHANGE: Removed enable-dummy-data prop
Removed dummy-data prop and updated stories to not use the prop.
Fixes: https://tegel.atlassian.net/browse/DTS-2056
2. Check in Table -> All stories
3. Make sure they all still look as intended.

fix(table): removed dummy-data prop

---

core/src/components/dropdown/dropdown.tsx
core/src/components/table/table-header-cell/readme.md

Move opening direction calculation to render, so it is updated after scroll.
Fixes: #DTS-1979
1. dropdown story
2. resize window so vertically and watch open direction change.

fix(dropdown): move open dir calc to render

---

.npmrc
README.md
core/.storybook/main.js
core/README.md
core/package-lock.json
core/package.json
package-lock.json
package.json

Updating code to use version 18
Fixes: DTS-1706
1. Open this branch on your local machine
2. Try to run it on your current version of node - anything below node version 18.16 should result in error
3. Install node 18
4. Run the code again (`npm run build` and `npm run start`)
5. If everything runs OK, we are good to go
6. Check below in case you are Mac or Windows user. It would be nice to have confirmation it works on both OS.
Important to check:
I have put `postcss: false` as that feature was creating an issue for us on node 18. There is a possibility for a workaround, but I am not sure we need it as we load a CSS file (tegel.css) which is already compiled by Stencil. In version 7 of Storybook, …

build: update to node 18

---

core/src/components/table/table-header-cell/table-header-cell.scss

Content jumping on sorting in react-demo-apge
Fixes: [DTS-2005](https://tegel.atlassian.net/browse/DTS-2005)
1. Go to react demo example
2. Open table component
3. Try to sort it - content should move left/right a bit
4. Now inspect the element and on `tds-table__header-button-icon` add width: 16px.
5. Jumping left and right should stop now.
6. I have added that rule in CSS in this PR...
**Note**
The issue seems not to be visible in Storybook, therefore testing in React.
[DTS-2005]: https://tegel.atlassian.net/browse/DTS-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(table:sorting): fixed width on icon to prevent content jump

---

core/src/components/stepper/stepper.scss

Adjusted justify-content rule to not force space between Steps when in horizontal orientation and labels are aside.
Fixes: https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-2051
2. Check in Components -> Stepper
3. Make sure Stepper looks according to design when Orientation = Horizontal and Text position = Aside
4. Change layout: 'centered', to layout: 'padded', on line 9 in stepper.stories.tsx and make sure everything still looks as it should

fix(stepper): adjust Stepper layout to not force space between Steps

---

core/.npmignore
core/src/components/card/card.stories.tsx
core/tsconfig.json

Adding .npmignore file to handle files we do not want to publish when releasing code
Component readme files are imported in every story for the need of showing it in the <i>Notes</i> tab. We were getting typescript issues for them, even though they are defined in the globals.d.ts. 
The reason for that is that they were excluded in tsconfig. 
Another way is to exclude them in the .npmignore file and then the problem is gone.
1. Branch out main and see if you get warnings for in import lines of readme's in any component. (There should be one)
2. Now branch out this branch and see if warnings are gone

feat: adding .npmignore 

---

core/src/components/modal/modal.tsx
core/src/components/popover-canvas/popover-canvas.tsx
core/src/components/popover-menu/popover-menu.tsx
core/src/components/table/table-header-cell/readme.md
core/src/components/tooltip/tooltip.tsx

Makes referenceEl accept null since, for example, in React a ref is null before it is an element.
Fixes: #DTS-2040
1. Check out repo on your local machine
1. Build the project.
1. Check the types in src/core/components.d.ts that reference el can be null.

fix(popover): reference el prop accept null

---

core/src/components/chip/chip-vars.scss
core/src/components/chip/chip.scss

Adding background variable and change when component is in focus
Fixes: [DTS-2072](https://tegel.atlassian.net/browse/DTS-2072)
1. Check Netlify PR preview link
2. Open Chip component
3. Check that on focus background color is grey-50 (in light mode) and grey-900 in dark mode.
[DTS-2072]: https://tegel.atlassian.net/browse/DTS-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(chip): focus background color

---

core/src/components/slider/slider-vars.scss
core/src/components/slider/slider.tsx

Refactoring the way class name for disabled state is set. The use of template literals stops the component updating in runtime.
Fixes: https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-2064
2. CD into core
3. Run npm pack
4. Copy generated file into tegel-react-demo local repo on root level
5. In package.json, update path to @scania/tegel to the generated file name (example: "@scania/tegel": "file:scania-tegel-0.0.9.tgz",)
6. Run npm run build (this might cause some errors since we've made changes in Tegel that haven't been released yet. Remove what you don't need for testing the Slider.
7. Run npm run start.
8. Check that the Slider disabled state can be update in …

fix(slider): disabled state update in runtime

---

core/src/components/button/button.scss
core/src/components/button/button.tsx

Fix for the disabled state of the button
pointer-events: none is never removed as in frameworks disabled prop is there all the time so selector it valid all the time. 
Fixes: [DTS-2155](https://tegel.atlassian.net/browse/DTS-2155)
1. Pack the code 
2. Test it in react framework
3. Toggle disabled state to see if it works
_If applicable, add screenshots to help explain_
_Add any other context about the pull-request here._
[DTS-2155]: https://tegel.atlassian.net/browse/DTS-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): disabled state and pointer events

---

core/src/components/card/card.scss
core/src/components/card/card.stories.tsx
core/src/components/card/card.tsx

Missing CSS rule for body image
Fixes: [DTS-2152](https://tegel.atlassian.net/browse/DTS-2152)
1. Go to Netlify preview
2. Check Card component
3. Try to change image in body, try to use extra large one to test that it will shrink within card area 
[DTS-2152]: https://tegel.atlassian.net/browse/DTS-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(card): class and rule for body image

---

core/src/components/footer/footer.scss

When no box-sizing, padding is added after width rule, so width: 100% + 40px + 40px which results in horizontal scroll.
Fixes: [DTS-2153](https://tegel.atlassian.net/browse/DTS-2153)
1. Check the prod storybook
2. Check the PR storybook
3. Compare the footer component with top part, inspect and see if there is no more horizontal scroll
[DTS-2153]: https://tegel.atlassian.net/browse/DTS-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(footer): horizontal scroll issue

---

core/src/components/button/button.scss
core/src/components/popover-canvas/popover-canvas.scss
core/src/components/popover-canvas/popover-canvas.stories.tsx

Prefer using tds-link component in popover-canvas example
Fixes: [DTS-1996](https://tegel.atlassian.net/browse/DTS-1996)
1. Open Storybook preview 
2. Check Popover Canvas
3. There should be <tds-link component
[DTS-1996]: https://tegel.atlassian.net/browse/DTS-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(popover-canvas): use tds link component

---

core/src/components/header/header-dropdown/readme.md
core/src/components/header/header-launcher/readme.md
core/src/components/popover-canvas/popover-canvas.tsx
core/src/components/popover-canvas/readme.md
core/src/components/popover-core/popover-core.tsx
core/src/components/popover-core/readme.md
core/src/components/popover-menu/popover-menu.tsx
core/src/components/popover-menu/readme.md
core/src/components/tooltip/readme.md
core/src/components/tooltip/tooltip.tsx

Rename core-popover component
Fixes: [DTS-2158](https://tegel.atlassian.net/browse/DTS-2158)
1. Go to Netlify Preview
2. Check that the Popover canvas, Popover menu and Tooltip work as intended
[DTS-2158]: https://tegel.atlassian.net/browse/DTS-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(popover-core): rename and move

---

core/src/components/link/link.stories.tsx
core/src/components/link/link.tsx

div inside a component prevents it from inlining, lets use span instead
Fixes: [DTS-2144](https://tegel.atlassian.net/browse/DTS-2144)
1. Go to the Netlify preview link
2. Check if the Link component is now in line with text
**Additional note**
[Inline Display Components](https://www.w3schools.com/css/css_display_visibility.asp)
[DTS-2144]: https://tegel.atlassian.net/browse/DTS-2144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(link): span instead of div for inline alignment

---

core/src/components/message/message.stories.tsx
core/src/components/message/message.tsx
core/src/components/message/readme.md

Renaming type prop to variant
Fixes: [DTS-2132](https://tegel.atlassian.net/browse/DTS-2132)
1. Go to Netlify Preview
2. Check if the variant prop is there in the code and Notes
3. Check if Controls is updated with renamed prop and if switching between variants works OK
[DTS-2132]: https://tegel.atlassian.net/browse/DTS-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(message): variant instead of type prop

---

core/src/components/toast/readme.md
core/src/components/toast/toast.stories.tsx
core/src/components/toast/toast.tsx

Renaming prop type to variant 
Fixes: [DTS-2133](https://tegel.atlassian.net/browse/DTS-2133)
1. Go to the Netlify preview link
2. Check the Toast component
3. Run through its variant options and make sure the code and design is updated
[DTS-2133]: https://tegel.atlassian.net/browse/DTS-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(toast): variant instead of type prop

---

core/src/components/header/header-dropdown-list-item/header-dropdown-list-item.scss
core/src/components/header/header-dropdown-list-item/header-dropdown-list-item.tsx
core/src/components/header/header-dropdown-list-item/readme.md
core/src/components/header/header-dropdown-list/header-dropdown-list.scss
core/src/components/header/header-dropdown-list/header-dropdown-list.tsx
core/src/components/header/header-dropdown-list/readme.md
core/src/components/header/header-launcher-list-item/header-launcher-list-item.tsx
core/src/components/header/header-launcher-list/header-launcher-list.tsx
core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx

Renaming type prop to size
Fixes: [DTS-2129](https://tegel.atlassian.net/browse/DTS-2129)
1. Go to Header and Patterns stories in Netlify preview link
2. Check that dropdown and dropdown list items look OK
3. Check if Notes are reflecting renamed props
[DTS-2129]: https://tegel.atlassian.net/browse/DTS-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(header): size instead of type prop

---

core/src/components/dropdown/dropdown.tsx

Removing emitting tdsChange on initial setting of default value
Fixes: [DTS-2161](https://tegel.atlassian.net/browse/DTS-2161)
1. Add event listenerfor tdsChange 
2. Component should not fire tdsChange if there is default-value prop selected
[DTS-2161]: https://tegel.atlassian.net/browse/DTS-2161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): remove emit on setting default value

---

core/src/components/chip/chip.tsx

In the react demo page the onClick event on the tds-chip were being fired twice. This was due to the click on the element was triggering a click on both the label and the input. I have now put a stopPropogation on the onClick event of the label.
**To see the error in action:**
1. Go the the react demo page
2. Go to Chips page
3. Click either of the two first chips
4. See the alert appear twice.
Fixes: [DTS-2176](https://tegel.atlassian.net/browse/DTS-2176)
1. Checkout branch.
5. Run npm build in tegel/core
6. Run npm pack
7. Run npm install {link to tarball generated by npm pack}
8. Go to the demo page -> chips -> click the chips and se that the alert only appears once.
[DTS-2176]: …

fix(chip): double events firing

---

core/src/components/datetime/datetime.stories.tsx
core/src/components/datetime/datetime.tsx
core/src/components/datetime/readme.md
core/src/components/dropdown/readme.md
core/src/components/table/table-header-cell/readme.md

Allowing users to set min and max value in DateTime component
Fixes: [DTS-2179](https://tegel.atlassian.net/browse/DTS-2179)
1. Go to Netlify preview link
2. Try to set different min/max values in Storybook.
3. Check if works as intended for date and datetime. "time" has issues with limitation even in native HTML component.
Example for different types: datetime="2023-01-31T00:00" date="2023-01-01" time="15:00"
[DTS-2179]: https://tegel.atlassian.net/browse/DTS-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(datetime): min & max props

---

core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
core/src/components/table/table-body-row/table-body-row.scss
core/src/components/table/table-body-row/table-body-row.tsx
core/src/components/table/table-vars.scss
core/src/components/table/table/table.tsx

Tabel rows were missing hover color on its rows when mode-variant was used. 
Fixes: [CDEP-2047](https://tegel.atlassian.net/browse/CDEP-247)
1. Go to the preview link below
2. Hover over table rows, the background color should change
3. Select mode-variant, hover background color on rows should be present
4. Select the "Multiselect" story, and select one of the rows - it should change the background color as long as it is selected. Also, the background color of it should change on hover. 
5. Do the same test for light and dark mode
- In light mode: The hover color is usually one step darker than the regular state of the row. The selected state is one step darker than the …

fix(table): hover on rows

---

core/src/components/button/button.scss
core/src/components/button/button.tsx
core/src/components/table/table-header-cell/readme.md

In the check for if it in an only-icon button we also need to check if they are using the slot rather than the text prop.
Before this fix the button would be treated as a only-icon button if they used the label slot.
Note: I have not added any slot/prop toggle in storybook. When testing you need to checkout the branch and implement the slot usage on your own.
Fixes: [CDEP-2196](https://tegel.atlassian.net/browse/CDEP-2196)
2. In story file, use the slot="label" rather than the text prop.
3. See that the button still works as intended.
[CDEP-2196]: https://tegel.atlassian.net/browse/CDEP-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): fixed usage of label slot

---

core/src/components/button/button-vars.scss
core/src/components/button/button.scss

Added a variable for the slotted icon on active state of button. This was previously getting overridden by the hover state of the slotted icon.
Fixes: [CDEP-1982](https://tegel.atlassian.net/browse/CDEP-1982)
1. Go to storybook link below.
2. Check in Components -> Button
3. Set it to use secondary variant.
4. Click the button and make sure the icon is the correct color when it is being clicked.
[CDEP-1982]: https://tegel.atlassian.net/browse/CDEP-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): added variable for active state on slotted icon

---

core/src/components/dropdown/dropdown-option/dropdown-option.tsx
core/src/components/dropdown/dropdown.stories.tsx
core/src/components/dropdown/dropdown.tsx
core/src/components/dropdown/readme.md

* Moved the fetching of data in the dropdown option from it's parent to a later lifecycle hook. This
to be sure that all the attributes of the parent are present.
* Refactored the setValue/reset methods to fetch the dropdowns children before running. This to allow people to render the options dynamically.
Fixes: [CDEP-2191](https://tegel.atlassian.net/browse/CDEP-2191)
2. Check that the Dropdown works as before.
**More testing**
1. Check out the branch, pack it and use it in the react demo page.
2. Render dropdown options in runtime and make sure the dropdown works as before.
[CDEP-2191]: https://tegel.atlassian.net/browse/CDEP-2191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …

fix(dropdown): select issues

---

core/src/components/side-menu/side-menu-close-button/side-menu-close-button.scss
core/src/components/side-menu/side-menu-overlay/side-menu-overlay.scss
core/src/components/side-menu/side-menu.scss
core/src/components/side-menu/side-menu.stories.tsx
core/src/components/side-menu/side-menu.tsx

Removed all animation when opening/closing the side menu.
Fixes: [CDEP-2195](https://tegel.atlassian.net/browse/CDEP-2195)
2. Check in Side Menu
3. Try opening and closing the side menu (mobile)
[CDEP-2195]: https://tegel.atlassian.net/browse/CDEP-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(side-menu): removed open/close animation

---

core/src/components/link/link-vars.scss
core/src/components/toast/toast.scss
core/src/components/toast/toast.stories.tsx

The Link component in the Toast component has to have revert logic when it comes to dark and light mode due to the background color used in the Toast component itself. To clarify, the Toast component in Light mode is using a dark background and an opposite one for light, therefore we need to have a "switch" so the Link component looks good in both versions of the component.  
Fixes: [CDEP-2159](https://tegel.atlassian.net/browse/CDEP-2159)
1. Go to the Netlify preview link
2. Check the Toast component
3. Inspect the colors of the Link component - in Light mode for the Toast component Link should use its colors for Dark mode and vice versa.
**Note**
The current Link component is OK to use in Toast. …

fix(toast): link component colors

---

core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
core/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
core/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx

Refactored the tabs to include the entire slotted item as a clickable area, due to focus state this had to be done using a pseudo element.
Fixes: [CDEP-2226](https://tegel.atlassian.net/browse/CDEP-2226)
1. Go to Tabs
2. Check in Folder/Inline/Navigation tabs
3. Make sure the clickable area is the entire tab.
4. Change from Button to Link in the controls.
5. Make sure the clickable area is the entire tab.
[CDEP-2226]: https://tegel.atlassian.net/browse/CDEP-2226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tabs): clickarea should cover entire tab

---

core/src/components/datetime/datetime-vars.scss
core/src/components/datetime/datetime.scss
core/src/components/datetime/datetime.tsx

The datetime had a different implementation of primary/secondary mode which led to some unexpected behaviour in our demo page. 
If the element did not have a pop of mode-variant it could not inherit the mode-variant from outside of the component.
You can view the issue by checking out the main branch of tegel-react-demo -> in the FormPage.tsx remove all inline setting of mode-variant="secondary" and then toggle the mode-variant.
Fixes: [CDEP-2416](https://tegel.atlassian.net/browse/CDEP-2416)
**How to test** 
1. Check the form on [this](https://github.com/scania-digital-design-system/tegel-react-demo/pull/126) page and toggle the primary/secondary mode-variants
**NOTE**
It is only the inital input that should change, not the background of …

fix(datetime): corrected secondary mode variant

---

core/src/components/icon/icon.scss
core/src/components/icon/icon.tsx
core/src/components/side-menu/side-menu.stories.tsx

The icon size was unable to change in firefox. This was due to the scss file setting the height/width of the icon to always be 1em (16px).
Fixes: [CDEP-2427](https://tegel.atlassian.net/browse/CDEP-2427)
1. Open the previewlink in firefox and chrome
2. Go to Side Menu
3. Make sure the icons are the same size.
4. Go to Icons
5. Try changing the size of the icon with the control.
6. Make sure it changes.
[CDEP-2427]: https://tegel.atlassian.net/browse/CDEP-2427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(icon): set height/width of svg based on size prop

---

core/src/components/side-menu/side-menu-item/side-menu-item.scss

Added position relative to allow for underlying item to position themself absolute, and to keep correct position on scroll.
Fixes: [CDEP-2433](https://tegel.atlassian.net/browse/CDEP-2433)
1. Go to Side Menu
2. Create vertical scroll on side menu (in collapsed state)
3. Make sure the icons/buttons are positioned correctly.
[CDEP-2433]: https://tegel.atlassian.net/browse/CDEP-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(side menu): collapsed scroll

---

core/src/components/header/header-dropdown/header-dropdown.tsx
core/src/components/header/header-dropdown/readme.md
core/src/components/side-menu/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
core/src/components/side-menu/side-menu-dropdown/readme.md
core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
core/src/components/side-menu/side-menu.stories.tsx
core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx

Update slot in side menu (button-label/button-icon) to conform with slot naming standard.
Fixes: [CDEP-2431](https://tegel.atlassian.net/browse/CDEP-2431)
1. Go to Side Menu
2. Check under notes and check that slot names are correct.
3. Check Side Menu examples
4. Make sure they still work as before.
[CDEP-2431]: https://tegel.atlassian.net/browse/CDEP-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(side menu): slot name

---

core/src/components/textarea/readme.md
core/src/components/textarea/textarea.tsx
core/src/stories/Migration/Migration.stories.mdx

Aligned the autofocus prop with other components (datetime and text-field)
Fixes: [CDEP-2437](https://tegel.atlassian.net/browse/CDEP-2437)
1. Go to Textarea
2. Check the notes and check that to autofocus prop is lowercased and one word.
3. Validate that it is the same for datetime and text-field
[CDEP-2437]: https://tegel.atlassian.net/browse/CDEP-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(textarea): aligned autofocus prop with other components

---

core/src/components/checkbox/checkbox.scss
core/src/components/dropdown/dropdown-option/dropdown-option.scss
core/src/components/table/table-header-cell/readme.md

Make multiselect items clickable everywhere. Done by modifications to checkboxes clickable area.
Fixes: [CDEP-2327](https://tegel.atlassian.net/browse/CDEP-2327)
Test clickable area of checkbox, components using checkbox, and dropdown multiselect. 
These are the only parts that should have been potentially affected.
Checkboxes were modified to make their use simpler in cases like this. (Making it so the user doesn't have to do a hack to accomplish this)
[CDEP-2327]: https://tegel.atlassian.net/browse/CDEP-2327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dropdown, checkbox): fix multiselect clickable area

---

core/src/components/banner/banner.scss
core/src/components/banner/banner.stories.tsx
core/src/components/banner/banner.tsx
core/src/components/banner/readme.md
core/src/components/card/card.scss
core/src/components/card/card.stories.tsx
core/src/components/card/card.tsx
core/src/components/card/readme.md
core/src/components/modal/modal.stories.tsx
core/src/components/modal/modal.tsx
core/src/components/modal/readme.md
core/src/components/toast/readme.md
core/src/components/toast/toast.scss
core/src/components/toast/toast.stories.tsx
core/src/components/toast/toast.tsx

**Describe pull-request**
Aligned bottom slot name and renamed actions prop (modal).
Fixes: [CDEP-2447](https://tegel.atlassian.net/browse/CDEP-2447)
1. Go to the affected components
2. Make sure the slots work as inteded.
[CDEP-2441]: https://tegel.atlassian.net/browse/CDEP-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDEP-2447]: https://tegel.atlassian.net/browse/CDEP-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(modal/toast/banner/card): align slot names

---

core/src/components/chip/chip.tsx
core/src/components/chip/readme.md

updated the tdsChange event emitted from the chip to optionally include a checked key/value for checkboxes.
Fixes: [CDEP-2453](https://tegel.atlassian.net/browse/CDEP-2453)
1. Go to Chip
2. Check/Uncheck a checkbox
3. Check the console for a log of the event
4. Check the detail.checked value

fix(chip): updated tdsChange to include the updated checked value

---

core/src/components/tabs/folder-tabs/folder-tabs.tsx
core/src/components/tabs/inline-tabs/inline-tabs.tsx
core/src/components/tabs/navigation-tabs/navigation-tabs.tsx

Added a watcher for the default-selected-index & selected-index in order to keep the state aligned with the attribute.
Fixes: - 
1. Go the the react test environment: https://github.com/scania-digital-design-system/tegel-react-demo/pull/130
2. Check under Tabs -> Link
3. Try switching tab and see that all tabs change the selected tab

fix(tabs): watcher for selectedIndex & defaultSelectedIndex

---

core/src/components/tabs/inline-tabs/inline-tabs.tsx
core/src/components/tabs/inline-tabs/readme.md

Added missing description to tdsChange event for Inline Tabs component
Fixes: [CDEP-2457](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2457)
2. Check in Tabs -> Inline Tabs -> Notes
3. Check that there is a description for the event tdsChange

docs(inline tabs): add description to tdsChange event

---

core/src/components/tabs/folder-tabs/folder-tabs.stories.tsx
core/src/components/tabs/inline-tabs/inline-tabs.stories.tsx

Updated naming of Tab subcomponents for Inline and Folder Tabs in notes tab on Storybook
Fixes: [CDEP-2458](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2458)
2. Check in Tabs -> Folder Tabs -> Notes _and_ Tabs -> Inline Tabs -> Notes
3. Check that components/subcomponents are called _Folder Tabs_ / _Folder Tab_ and _Inline Tabs_ / _Inline Tab_ respectively
**CURRENT**
**EXPECTED**

docs(tabs): update naming of Tab sub components in notes tab

---

core/src/components/table/table-footer/table-footer.scss
core/src/components/table/table-vars.scss

- Introduces two new variables for table-footer (for both modes):
`--tds-table-footer-page-selector-icon`
`--tds-table-footer-page-selector-icon-disabled`
- Used these variables to color the pagination button icons
Fixes: [CDEP-2438](https://tegel.atlassian.net/browse/CDEP-2438)
1. Go to Table -> Pagination
2. Check the color of the icons in the pagination buttons.
3. Do this check for both modes.
[CDEP-2438]: https://tegel.atlassian.net/browse/CDEP-2438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(table-footer): correct color of pagination button icons for both modes

---

core/src/stories/Installation/installation.stories.ts

Corrected spelling in HTML installation guide.
Fixes: [CDEP-2568](https://tegel.atlassian.net/browse/CDEP-2568)
1. Go to Installation
2. Check under HTML
3. Check the spelling of `install`
[CDEP-2568]: https://tegel.atlassian.net/browse/CDEP-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(installation): corrected spelling in HTML installation guide

---

core/src/components/banner/banner.stories.tsx
core/src/components/banner/banner.tsx
core/src/components/banner/readme.md

Removed docs and implementation of unused event. This event could never get emitted so this is not a breaking change.
Fixes: -
1. Go to Banner
2. Check in Notes
3. Make sure the only event is the tdsClose event.

fix(banner): removed docs and implementation of unused event

---

.eslintignore
.gitignore
core/package.json
core/stencil.config.ts

Updated stencil config to put dist-custom-elements in correct folder and switched behaviour to auto-define-custom-elements. Also update ignore config to ignore stencil built components folder.
Fixes: -
1. Checkout branch
2. Run `npm build` in core.
3. Check that a `components` folder was generate (next to dist and loader)

build(stencil.config): prepare stencil build for wrappers

---

core/src/components/text-field/readme.md
core/src/components/text-field/text-field.tsx

Updated description for no-min-width prop to match same prop in Textarea
Fixes: [CDEP-2589](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2589)
2. Check in Text Field -> Notes
3. Check that the no-min-width prop has the same description as the corresponding prop in Textarea component
[CDEP-2589]: https://tegel.atlassian.net/browse/CDEP-2589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(text field): update description for no-min-width prop

---

packages/core/src/components/dropdown/dropdown-button.scss
packages/core/src/components/dropdown/dropdown.stories.tsx

The dropdowns focus state was previously missaligned with its bottom border. This was due to us adding a bottom border of 2px on top of the regular bottom border when it had focus. This PR fixes this issue. 
Fixes: [CDEP-2644](https://tegel.atlassian.net/browse/CDEP-2644)
2. Click the dropdown
3. Make sure the line on the side of the dropdown is still inline with the bottom border.
**NOTE:** The divider needs to be removed before merging.
[CDEP-2644]: https://tegel.atlassian.net/browse/CDEP-2644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): fixed missplacement issue of the dropdowns focus state

---

packages/core/src/components/popover-menu/popover-menu.stories.tsx
packages/core/src/components/tooltip/tooltip.stories.tsx

Updated storybook to document `selector` over `referenceEl` due to unstable support of referenceEl in framework wrappers.
Fixes: [CDEP-2651](https://tegel.atlassian.net/browse/CDEP-2651)
1. Go to Tooltip/Popover Menu
2. Test that the component works as intended
[CDEP-2651]: https://tegel.atlassian.net/browse/CDEP-2651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(popover/tooltip): used selector over referenceEl

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx

When selecting a muliselect option in the dropdown two `tdsChange` event were being emitted. One from the `tds-dropdown` and one from the `tds-checkbox` inside the `tds-dropdown-option`. This PR stopPropgation on the second event to only emit a `tdsChange` event from the `tds-dropdown`.
Fixes: [CDEP-2639](https://tegel.atlassian.net/browse/CDEP-2639)
2. Add multiselect.
3. Select an option
4. Check the console and make sure only one `tdsChange` evet in being logged.
[CDEP-2639]: https://tegel.atlassian.net/browse/CDEP-2639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): stopPropogation on checkbox change event in dropdown-option

---

packages/core/src/components/dropdown/dropdown-button.scss
packages/core/src/components/dropdown/dropdown.stories.tsx

The value in the dropdown is getting cut off (due to overflow: hidden). To combat this we need to up the line-height.
Example: 
Fixes: [CDEP-2637](https://tegel.atlassian.net/browse/CDEP-2637)
2. Select the first value
3. Make sure no parts of the word is getting cut off.
[CDEP-2637]: https://tegel.atlassian.net/browse/CDEP-2637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): override line-height to avoid overflow:hidden

---

packages/core/src/components/banner/banner.stories.tsx

The banner story shows undefined under the icon prop for the "Error" and "Information" variants.
Fixes: [CDEP-2645](https://tegel.atlassian.net/browse/CDEP-2645)
1. Open Storybook preview
2. Check Banner component
3. Set it to the Information or Error variant
4. Observe "Docs" tab - icon prop should not be there
5. Compare with [prod Storybook](https://tegel-storybook.netlify.app/?path=/story/components-banner--default), issue is present there - icon is "undefined" for those two varinats
[CDEP-2645]: https://tegel.atlassian.net/browse/CDEP-2645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(banner): no undefined icon in error and info variant

---

packages/core/src/components/button/button.stories.tsx

Removes an usused class from the icon inside `tds-button`
Fixes: [CDEP-2654](https://tegel.atlassian.net/browse/CDEP-2654)
1. Go to Button
2. Add an icon
3. Check the overall styling of the component for all variant and states.
[CDEP-2654]: https://tegel.atlassian.net/browse/CDEP-2654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(button): remove unused class from button icon

---

packages/core/src/components/slider/slider.stories.tsx
packages/core/src/components/slider/slider.tsx

Added a watcher on value to allow for runtime updates. 
Removed the internal `readOnlyState` which was being set in `componentWillLoad`, this enabled for runtime updates of the `readOnly` prop.
Fixes: [CDEP-2587](https://tegel.atlassian.net/browse/CDEP-2587), [CDEP-2655](https://tegel.atlassian.net/browse/CDEP-2655)
1. Checkout branch and run storybook
2. Go to Slider 
3. Update the readOnly / value props in runtime.
4. Make sure the sliders readOnly prop is being toggled.
[CDEP-2587]: https://tegel.atlassian.net/browse/CDEP-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDEP-2655]: https://tegel.atlassian.net/browse/CDEP-2655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

fix(slider): enable for runtime updates of value/readOnly

---

packages/core/src/components/card/card.scss

Made the card 100% width when clickable.
Fixes: [CDEP-2661](https://tegel.atlassian.net/browse/CDEP-2661)
1. Go to Card
2. Make it `clickable`
3. Make sure it has the same width as the non clickable card.
[CDEP-2661]: https://tegel.atlassian.net/browse/CDEP-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(card): clickable card not full width

---

packages/core/src/components/table/table-component-filtering.stories.tsx

Removed obsolete control from story.
Fixes: [CDEP-2665](https://tegel.atlassian.net/browse/CDEP-2665)
1. Go to Table -> Filter
2. Check the controls and make sure the is no `Use data prop` control
[CDEP-2666]: https://tegel.atlassian.net/browse/CDEP-2666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDEP-2665]: https://tegel.atlassian.net/browse/CDEP-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(table): removed obsolete control

---

packages/core/src/components/tabs/inline-tabs/inline-tabs.tsx
packages/core/src/components/tabs/navigation-tabs/navigation-tabs.tsx

Removed events that was causing multiple events to be fired.
Fixes: [CDEP-2668](https://tegel.atlassian.net/browse/CDEP-2668)
1. Go to Tabs
2. Click the tabs and check the console for the log of the events.
3. Make sure only one event it being fired when a tab is changed.
[CDEP-2668]: https://tegel.atlassian.net/browse/CDEP-2668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tabs): multiple events firing

---

packages/core/src/components/table/table-component-multiselect.stories.tsx

Removed obsolete control from story.
Fixes: [CDEP-2666](https://tegel.atlassian.net/browse/CDEP-2666)
1. Go to Table -> Multiselect
2. Check the controls and make sure the is no `multiselect` control
[CDEP-2666]: https://tegel.atlassian.net/browse/CDEP-2666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(table): removed obsolete control from story

---

packages/core/src/components/block/block.tsx

Placed the setting of child blocks in side the render function. This will ensure us that the function `setModeVariantOnChildBlocks` run every time the block is rerender or on initial render.
Fixes: [CDEP-2434](https://tegel.atlassian.net/browse/CDEP-2434)
1. Go to Block
2. Update the modeVariant of the parent block in runtime
For example, add the following inte the template in the block story file: 
```
<button id="test">test</button>
<script>
block = document.querySelector('#block')
button = document.querySelector('#test')
button.addEventListener('click', () => {
block.modeVariant = block.modeVariant === 'primary' ? 'secondary':'primary';
})
</script>
```
3. Make sure this changes the modeVariant of the child element …

fix(block): updating block modeVariant in runtime

---

packages/core/src/stories/foundations/color/color-semantic.stories.tsx

**Describe pull-request** 
Fixes old typo in Storybook
Fixes: [CDEP-2658](https://tegel.atlassian.net/browse/CDEP-2658)
2. Check under Foundations -> Color, and see that it says "Semantic"
[CDEP-2658]: https://tegel.atlassian.net/browse/CDEP-2658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: typo in Storybook

---

packages/core/src/components/dropdown/dropdown.tsx

The filter and tabbing functionality of the dropdown did not work until a selection had been made in the dropdown. This was due to us fetching children in the connectedCallback. Since all children are rendered after the dropdown we need to get the children before performing a filter or tabbing. This using the `getChildren()` function. 
See video:
https://github.com/scania-digital-design-system/tegel/assets/62651103/56efca81-968a-4643-b058-9d71874d970a
Fixes: [CDEP-2691](https://tegel.atlassian.net/browse/CDEP-2691)
2. Try filtering before any selection have been made.
3. Try filtering after a selection have been made. 
4. Do the same for tabbing.
[CDEP-2691]: …

fix(dropdown): use getChildren over fetching children in connectedCallback

---

packages/core/src/stories/Installation/installation.stories.ts

Off indentation in Storybook
Fixes: [CDEP-2699](https://tegel.atlassian.net/browse/CDEP-2699)
2. Check in Installation, and compare to production.
[CDEP-2699]: https://tegel.atlassian.net/browse/CDEP-2699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: indentation on installation page in storybook

---

packages/core/src/components/icon/icon.tsx
packages/core/src/components/icon/readme.md

Adds a prop for users to overrride the default `title` in the Icons `svg`
Fixes: [CDEP-2700](https://tegel.atlassian.net/browse/CDEP-2700)
1. Checkout branch
2. Set the title prop in the icon story
3. Make sure it overrides the default icon title.
[CDEP-2700]: https://tegel.atlassian.net/browse/CDEP-2700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(icon): enable for override of default title

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
packages/core/src/components/dropdown/dropdown.stories.tsx
packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/dropdown/readme.md
packages/core/src/components/table/table-header-cell/readme.md

The setValue method updated the `selection` of the dropdown without updating the selected state of its children. 
This PR updates the `setValue` method to enable for both value and label pair, object and array of object as it parameters. It also fixes a previous issue with double events firing on selection on multiselect. 
Fixes: [CDEP-2656](https://tegel.atlassian.net/browse/CDEP-2656)
2. Update the selection using the setValue method.
[CDEP-2656]: https://tegel.atlassian.net/browse/CDEP-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): setValue method

---

packages/core/src/components/icon/icon.tsx
packages/core/src/components/icon/readme.md

Switched title for `svgTitle` since title is a reserved attribute name. The previous prop name gave a warning on build.
Fixes: -

fix(icon): switched title for svgTitle since title is a reserved attribute name

---

packages/core/src/components/datetime/datetime.tsx
packages/core/src/components/text-field/text-field.tsx

Some inputs with empty helper text still added some spacing at the bottom. 
This PR fixes that by not rendering the helper text container div when there is no helper text.
Fixes: [CDEP-2701](https://tegel.atlassian.net/browse/CDEP-2701)
2. Check in Datetime & Textfield
3. Open devtools
4. Verify that the elements are the right height when there are no helper text
[CDEP-2701]: https://tegel.atlassian.net/browse/CDEP-2701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove extra margin under inputs without helper text

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
packages/core/src/components/dropdown/dropdown.stories.tsx
packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/dropdown/readme.md
packages/core/src/components/table/table-header-cell/readme.md

This PR builds further on the `setValue()` and `removeValue()` methods. This removes the dependency on `label` as an attribute to the methods. 
The user should still be able to interact with the `setValue` method by passing in two attributes (value, label). However the label passed in is not used, this is only there to not break the API. The user can now also pass in a string array that should have one entry per value they want selected.
Fixes: -
**How to test:**
1. Checkout branch.
2. Try updating the dropdown using the `setValue` method.
3. Test it for default, filter and multiselect dropdown
4. Verify that the dropdown works as before

refactor(dropdown): cleanup and enhancement setValue & removeValue

---

packages/core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.scss
packages/core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.tsx
packages/core/src/components/side-menu/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
packages/core/src/components/side-menu/side-menu-dropdown-list/side-menu-dropdown-list.tsx
packages/core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
packages/core/src/components/side-menu/side-menu-item/side-menu-item.tsx
packages/core/src/components/side-menu/side-menu.stories.tsx

- Added a `connectedCallback` check in child components to check the default `collapsed` state of the Side Menu.
- Added a `collapsed` control to storybook.
- Conditionally rendered the "Collapse" text based on it being collapsed or not. 
Fixes: [CDEP-2714](https://tegel.atlassian.net/browse/CDEP-2714)
1. Go to Side Menu
2. Set collapsible and collapsed to true
3. Make sure design is looking fiiine.
[CDEP-2714]: https://tegel.atlassian.net/browse/CDEP-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(side menu): collapsed by default

---

.eslintrc.json
packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/footer/footer-group/footer-group.tsx
packages/core/src/components/footer/footer.tsx
packages/core/src/components/stepper/stepper.tsx
packages/core/src/components/tabs/inline-tabs/inline-tabs.tsx
packages/core/src/components/toast/toast.tsx

**Describe pull-request**
Some components are currently importing from Stencil's internal package. However, Stencil warns to never do that.
> NOTE!! The @stencil/core/internal package is not meant to be consumed directly by anything other than Stencil internals. It is its own package so that it can be resolved by Stencil, but breaking changes can/will happen at any time. This isn't a "use at your own discretion" moment, but it's more of a "never use this because your code will break" fact.
https://github.com/ionic-team/stencil/blob/main/src/internal/readme.md
Added an ESLint rule to prevent importing from the internals again in the future and changed the imports affected by the rule.

fix: add ESLint rule to prevent importing from Stencils internal package

---

packages/core/src/components/card/card.scss
packages/core/src/components/modal/modal.scss
packages/core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
packages/core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
packages/core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
packages/core/src/components/toast/toast.scss

Our CSS-reset has a rule:
```css
input,
button,
textarea,
select {
font: inherit;
}
```
Which was causing issues for the Tabs. There selector (slotted(*)) for targeting slotted buttons was not strong enough and was getting overwritten by the rule above. This resulted in this look:
When it should look like this:
To combat this. I have used `!important` for the `font` and `letter-spacing` in our CSS whenever we are targeting `::slotted(*)`
Fixes: [CDEP-2708](https://tegel.atlassian.net/browse/CDEP-2708)
To see the error: 
1. Checkout the `develop` branch.
2. In `preview.css` add our CSS-reset
3. Check in Tabs and verify that the text have the wrong styling.
1. Checkout this branch.
3. In `preview.css` add our CSS-reset
5. …

fix(css reset/components): added important for slotted(*) targeted elements font styles

---

packages/core/src/components/modal/modal.scss
packages/core/src/global/global.scss

Before this change, third-party Stencil applications using Tegel together with @stencil/sass and shadow DOM would get the Tegel modal component styling applied to them, and they'd end up looking pretty strange. 
This happened because the modals `:host` pseudo-class got included in the `tegel.css` dist file *(probably by accident)*.
The classes `.header` and `.body` were also leaking and could cause conflicts with user styling.
**To prevent this from happening again in the future**, it might be a good idea to analyze the dist stylesheet. 
You could perhaps use a second Stylelint config and lint the dist stylesheet after a build to ensure things like `:host` stay out of this file.
https://stylelint.io/user-guide/rules/selector-pseudo-class-disallowed-list/
You …

fix(modal): leaked CSS

---

packages/react/tsconfig.json
tsconfig.json

In our root `tscinfig` we had previously set the `"jsx":"react"` and `"jsxFactory":"h"` because this is what we use in `core/`, however this is not the case for `react`. This PR removes jsx and jsxFactory in the root and leaves it up to the tsconfig in the packages to determine this.
Fixes:: - 
**How to se error:**  
1. I develop branch
2. Open accordion.tsx
3. You should se an error in the import of `h`.
**How to test:**
1. Check out this branch
2. Open accordion.tsx
3. There should be no errors.
4. From root, run `npm run build` and `npm run build-react`
5. They should both succeed.

build(tsconfig): eliminate conflicts

---

packages/core/src/components/modal/modal.scss
packages/core/src/components/modal/modal.stories.tsx
packages/core/src/components/modal/modal.tsx

This fixes an issue where text in the modal was selected when quickly toggling its visibility, or double clicking on the backdrop of a modal that had the `prevent` prop set to `true`.
**How to test** 
1. Spam click on the "Open Modal" button in Storybook.
2. Double click anywhere on the backdrop of a modal that has `prevent` set to `true`.
Modal content should still be selectable and interactable. It should still be possible to close the modal by clicking on the modals backdrop when `prevent` is set to `false`.
**Screenshots**
Before:
After:

fix(modal): prevent text selection when toggling modal

---

packages/core/src/components/stepper/readme.md
packages/core/src/components/stepper/stepper.tsx

Added @internal decorator to 'internalTdsPropsChange' event so it's not documented in the readMe.
Fixes: [CDEP-2749](https://tegel.atlassian.net/browse/CDEP-2749)
2. Check in Stepper -> Notes
3. Check that the event 'internalTdsPropsChange' is not documented
[CDEP-2749]: https://tegel.atlassian.net/browse/CDEP-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stepper): change internal event to not be documented in readme file

---

packages/core/src/components/dropdown/dropdown.tsx

Fixes dropdown getting value "undefined" (as a string) when it was a multiselect, filter, and opened and closed without selecting a value.
> "The reason inputElement.value is "undefined" as a string is because when you assign undefined to an input element's value, it gets converted to the string "undefined". This is a standard behavior in JavaScript: when undefined is coerced into a string, it becomes "undefined"."
-- GPT-4
Fixes: [CDEP-2749](https://tegel.atlassian.net/browse/CDEP-2759)
1. Go to deploy preview
2. Check in dropdown, add multiselect & filter
3. Open and close the dropdown and verify it looks good.
[CDEP-2749]: https://tegel.atlassian.net/browse/CDEP-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

fix(dropdown): fix multiselect & filter getting value "undefined"

---

packages/core/src/components/modal/readme.md
packages/core/src/components/popover-canvas/readme.md
packages/core/src/components/popover-menu/readme.md
packages/core/src/components/tooltip/readme.md

This PR adds documentation on how to use the referenceEl prop in with our React/Angular wrappers.
Fixes: [CDEP-2766](https://tegel.atlassian.net/browse/CDEP-2766)
1. Go to Modal, Tooltip, Popover Menu/Canvas
2. Check under Notes
3. Check the documentation on Angular/React usage.
[CDEP-2766]: https://tegel.atlassian.net/browse/CDEP-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(tooltip,modal,popover): referenceEl usage in Angular/React

---

packages/core/src/components/datetime/datetime.stories.tsx

Updated the documentation for default value and max properties.
Fixes: [CDEP-2653](https://tegel.atlassian.net/browse/CDEP-2653)
1. Go to Datetime
2. Check the documentation of the controls
[CDEP-2653]: https://tegel.atlassian.net/browse/CDEP-2653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(datetime): updated default value and max properties

---

packages/core/src/components/slider/slider.tsx
packages/core/src/components/slider/test/slider.e2e.ts

This PR adds a function that runs `onblur` if the user is using the input fields. It also adds tests to validate these flows.
This PR also marks the value prop in the slider as mutable, since it is being changed from within. 
It also refactors some of the internal methods of the slider to try and make the code a bit more readable. For example, eventhandlers are set in the JSX over {element}.addEventListener(). 
Fixes:
- [CDEP-2707](https://tegel.atlassian.net/browse/CDEP-2707)
- [CDEP-1992](https://tegel.atlassian.net/browse/CDEP-1992)
1. Go to Slider
2. Add input fields (in controls)
3. Update the value of the input field and then tab out of the input
4. Make sure the value is updated
5. Check out the branch
6. CD into …

feat(slider): update value onblur

---

packages/core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
packages/core/src/components/breadcrumbs/breadcrumbs.tsx

Corrects the focus state of the breadcrumb.
Fixes: -
1. Go to Breadcrumb
2. Put focus on a slotted anchor tag (navigate via keyboard)
3. Check the styling and make sure it is aligned with design
Before:
After:

fix(breadcrumb): correct focus state

---

packages/core/src/components/footer/footer-item/footer-item.scss

This PR updates all the footer links to use the correct font (headline-07)
Fixes: [CDEP-2839](https://tegel.atlassian.net/browse/CDEP-2839)
1. Go to Footer
2. Add a top part (via controls)
3. Check the links and make sure they use headline-07
[CDEP-2839]: https://tegel.atlassian.net/browse/CDEP-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(footer): link/title correct font

---

packages/core/src/components/table/table-component-multiselect.stories.tsx
packages/core/src/components/table/table-header/readme.md
packages/core/src/components/table/table-header/table-header.tsx

This PR adds a prop to the `table-header` component, `indeterminate`. This allows the user to toggle the indeterminate state of the checkbox present in the header, if the table is a multiselect one.  It also introduces an alternative prop to toggle the checke state of the "all selected"-checkbox, `selected` and adds a deprecation warning on the `allSelected` prop. 
This is done to align the prop names with the ones used in the `tds-table-body-row`.
Fixes: [CDEP-2884](https://tegel.atlassian.net/browse/CDEP-2884)
1. Go to Table -> Multiselect
2. Toggle the `All Indeterminate` control
[CDEP-2884]: https://tegel.atlassian.net/browse/CDEP-2884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(table): add inderminate state & updated selected prop

---

.github/workflows/release-angular.yml
.github/workflows/release-core.yml
.github/workflows/release-react.yml

This PR adds three github actions:
- release-core
- release-react
- release-angular
This are all actions that are triggered manually and they do a release to npm for each package.
The `release-core` actions requires the following input:
- Release type (major, minor, patch)
- Node version (18.16.0 by default) -> this specifies which node package should be built with.
- Tag -> specifies what npm tag the release should have
- Dry run -> if true the `npm publish` will run with a dry-run flag
The `release-react` and `release-angular` requires the following input:
- Tegel version -> which tegel version is the dependency for the package. This will also be the version of the built an published package. For example: if Tegel version is 1.1.0, the tegel-angular package …

build(core/react/angular): added release actions for all packages

---

packages/core/src/components/stepper/step/step.tsx
packages/core/src/components/stepper/stepper.stories.tsx

There was a mismatch in the prop name ('hideLabels') in the `tds-stepper` and the state name ('hideLabel') in the tds-step. This was causing an error where the hidden state of the labels could not update in runtime.
This PR fixes this issue by keeping the naming of the prop/state consistent.
Fixes: -
1. Go to Stepper
2. Click the testing button to update the prop in runtime.
3. Make sure the labels shows/hides.

fix: stepper hideLabels in runtime

---

packages/core/src/stories/Migration/Migration.stories.mdx
packages/core/src/stories/announcements/announce-tegel.stories.ts
packages/core/src/stories/tegel.stories.ts

Replace ambiguous term "native" components with css class components.
Fixes: [CDEP-2880](https://tegel.atlassian.net/browse/CDEP-2880)
**To test**
Look at the changes
[CDEP-2880]: https://tegel.atlassian.net/browse/CDEP-2880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: "native" components -> css class components

---

packages/core/src/components/button/button.scss

Corrected the font-size for button text when using icon slot.
Fixes: [CDEP-2900](https://tegel.atlassian.net/browse/CDEP-2900)
1. Go to Button
2. Add a Icon to the Button
3. Check the font-size of the button text.
[CDEP-2900]: https://tegel.atlassian.net/browse/CDEP-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): correct font-size for icon button

---

.github/workflows/bump-npm-version.yml
.github/workflows/release-angular.yml
.github/workflows/release-core.yml
.github/workflows/release-react.yml

This PR cleans up the github actions used for the releases of @scania/tegel, @scania/tegel-react and @scania/tegel-angular.
For @scania/tegel-react and @scania/tegel-angular, it adds a installation and build step for the core package. This is to be able to generate the wrappers based off of the core package. It also adds the package type (tegel, tegel-react, tegel-angular) to the PR branch it creates when a release is completed.
It also moves the NPM version bump into a seperate action that then creates a PR againt main. 
The release flow would look like this: 
1. Run the `Bump NPM version (core/angular/react)` action
2. Review and merge the PR it created into main
3. Review and merge the same branch into develop
4. Run: `Release @scania/tegel`, `Release @scania/tegel-react` and `Release …

build(release actions): cleanup of release gh actions

---

packages/core/src/components/dropdown/dropdown-button.scss
packages/core/src/components/dropdown/dropdown-filter.scss
packages/core/src/components/dropdown/dropdown.tsx

This PR fixes the issue of the error state not being correct whenever a Dropdown was focused/opened. 
It also makes sure that the filter input is focus whenever the icon in the dropdown is clicked. 
Before: 
After:
Fixes: -
2. Set error to true
3. Open the Dropdown
4. Make sure the error state aligns with design

fix(dropdown): error focus state style alignment

---

packages/angular/README.md
packages/core/README.md
packages/react/README.md

Updating link to reflect Amplify links
Fixes: [CDEP-2893](https://tegel.atlassian.net/browse/CDEP-2893)
1. Check changes in this PR
2. Readme files should have updated links that are pointing to tds-storybook hosted under tegel.scania.com domain and not under netlify.
[CDEP-2893]: https://tegel.atlassian.net/browse/CDEP-2893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(readme): amplify links updates

---

packages/core/package-lock.json
packages/core/package.json

Upgrading Stencil to version 4.7.1
Fixes: [CDEP-2305](https://tegel.atlassian.net/browse/CDEP-2305)
1. Check if you can run your local environment using this branch
2. Check if the Storybook starts as usual
[CDEP-2305]: https://tegel.atlassian.net/browse/CDEP-2305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build(stencil): upgrade to 4.7.1

---

packages/core/.storybook/main.cjs
packages/core/package-lock.json
packages/core/package.json

It is no longer needed as of node 20. We are also not really using it today, so I removed our only implementation of it in the storybook main.js. 
Our only use for it was to hide/show certain addons in production. I do not think we are really using these in development today, so I would suggest we remove them all together. 
Fixes: https://github.com/scania-digital-design-system/tegel/issues/407
2. Run `npm i` in core
3. Start storybook
4. Make sure everything runs as before.

build: removed dotenv dependency

---

packages/core/src/components/tabs/folder-tabs/folder-tab/folder-tab.scss
packages/core/src/components/tabs/folder-tabs/folder-tabs.scss
packages/core/src/components/tabs/inline-tabs/inline-tab/inline-tab.scss
packages/core/src/components/tabs/inline-tabs/inline-tabs.scss
packages/core/src/components/tabs/navigation-tabs/navigation-tab/navigation-tab.scss
packages/core/src/components/tabs/navigation-tabs/navigation-tabs.scss

z index were unnecessarily high.
NOTE: Might technically be a breaking change. However, I believe users getting negatively affected would be very rare. As such, I think leaving it will cause far more issues for users than removing it (z-index).
**How to test:**
Open the deploy preview and check that:
- tabs have no z-index set
- scroll buttons still appear and work as expected
- check for other issues

fix(tabs): unset z index

---

packages/core/src/components/chip/chip.tsx

Setting chip to active when type radio should not require to double click. 
Fixes: [CDEP-2995](https://tegel.atlassian.net/browse/CDEP-2995)
2. Check in Chip component, and change to type radio, setting to active should not require double click
[CDEP-2995]: https://tegel.atlassian.net/browse/CDEP-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(chip): double click for radio type

---

packages/core/src/components/side-menu/side-menu.tsx

1. When collapsed state is set initially by user, menu needs to stay collapsed when you switch to mobile view and back to desktop. Until now, logic was resetting it so menu appers in full size even prop collapsed states differently.
2. When loading the page on mobile size when prop collapsed set to true, mobile menu appears off. That is due to the fact that the function to check screen size runs only once user resizes the screen around 992px. On inital load we need to understand width of screen in order to display mobile menu correctly.
Both issues are able to reproduce in main version of Storybook. 
Fixes: [CDEP-3080](https://tegel.atlassian.net/browse/CDEP-3080)
Issue 1:
1. Set controls Collapsible prop to true and …

fix(side-menu): collapsed state on mobile view

---

packages/core/src/components/footer/footer.tsx
packages/core/src/components/footer/readme.md

Slot is enabling customization of copyright text. This is mainly done for projects in China as they need to translate it to mandarin. Reason for using slot over the prop is due to posible special signs/characters that may be used.  
Fixes: [CDEP-3053](https://tegel.atlassian.net/browse/CDEP-3053)
1. Branch out
2. Change story file so you inject slot at the bottom with custom text.
3. Default copyright text should be relaced with custom one
4. Delete slot
5. Check if original test appers again.
I was thinking to use name "bottom" as opposite to "top" slot, but as this one changes only copyright on the bottom left I tought this was good. 
[CDEP-3053]: …

feat(footer): copyright slot

---

packages/core/src/components/table/table-header-cell/readme.md
packages/core/src/components/table/table-header-cell/table-header-cell.tsx

Adding a slot to the table-header-cell component to enable users to use it for content like HTML in more complex use cases, like filtering over a single column or adding an icon to the title or when passing content between parenthesis. 
Fixes: [CDEP-3092](https://tegel.atlassian.net/browse/CDEP-3092)
1. Open a branch on your local
2. Try to add icon or any other HTML code between the parenthesis of <tds-table-header-cell>
3. Your component should be shown in story file (in case you test in Storybook)
I made other props optional by adding "?", does not change anything on the user side, but it is a small Typescript improvement. 
[CDEP-3092]: https://tegel.atlassian.net/browse/CDEP-3092?atlOrigin=eyJpIj …

feat(table-header-cell): added slot

---

packages/core/src/components/modal/modal.scss

Fixing value for the extra small size of modal on medium screen size.
Fixes: [CDEP-3095](https://tegel.atlassian.net/browse/CDEP-3095)
1. Check if the new value extra small size of the modal on medium screen is 50%.
[CDEP-3095]: https://tegel.atlassian.net/browse/CDEP-3095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(modal): medium screen and xs size

---

packages/core/tsconfig.json

Removing test and story files from shipping in npm package as users do not need them, plus it reduces the size of the package.
1. Open branch on local
2. Delete "dist" folder under packages/core
3. Run build command
4. Run npm pack
5. Check the size of package, it should be 3.6MB
6. Check "dist" folder and see if you can see any of test or story files in.
7. Do the same but on develop branch, size should be 4.1MB

build: test files and stories removed from shipping

---

packages/core/package-lock.json
packages/core/package.json

Adding a newer version of Stencil core.
More about it [here](https://github.com/ionic-team/stencil/releases).
1. Checkout branch
2. Navigate to packages/core
3. Run npm i
4. Check if the library builds and starts without issues
The issue with Stencil watcher not triggered when change is done in nested CSS files seems to be fixed in version 4.11. Nice for us as we have a lot of nested CSS files.

build(stencil): 4.12.0

---

packages/core/src/components/text-field/readme.md
packages/core/src/components/text-field/text-field.stories.tsx
packages/core/src/components/text-field/text-field.tsx

Currently from our application can pass type=number attribute to tegel-text field, but we cant define min, max attributes from our-side. That effects how user can interact with increase/decrease buttons inside the input field.
Adding support for  customisable min, max values for the input type number.
1. Go to text-field storybook
2. select input type number
3. define min,max values,
4. interact with increment/decrement buttons
_If applicable, add screenshots to help explain_
_Add any other context about the pull-request here._

feat(text-field): adding number type and min-max attributes

---

packages/core/src/components/datetime/datetime.tsx
packages/core/src/components/datetime/readme.md

Enabling setting "value" to another value during the runtime.
Fixes: [CDEP-3110](https://tegel.atlassian.net/browse/CDEP-3110)
1. Open the preview link
2. Navigate to Datetime component
3. From the console, try to use setValue method on input by setting new value like: component.setValue('2000-01-13T14:15') 
Sometimes you need to find element in "Element" tab in Chrome before using console as sometimes targeting element ends in "null". At least that happened to me. 
[CDEP-3110]: https://tegel.atlassian.net/browse/CDEP-3110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(datetime): setValue method

---

packages/core/src/components/icon/icon.stories.tsx
packages/core/src/components/icon/icon.tsx

1. Removing setting the icon name as the default value for <title> tag as it creates more issues than help for users.
2. Adding more a11y fields for icons that are dependent on svgTitle and svgDescription props.
Fixes: [CDEP-3113](https://tegel.atlassian.net/browse/CDEP-3113)
1. title and description elements should not be there if you inspect preview branch
3. Adding svgTitle and svgDescription will enable title and description fields as well as aria attributes too.
4. Run ...
[CDEP-3113]: https://tegel.atlassian.net/browse/CDEP-3113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(icon): a11y

---

.github/workflows/create-release-pr.yml
.github/workflows/release-all.yml
.github/workflows/release-angular.yml
.github/workflows/release-core.yml
.github/workflows/release-react.yml

1. We encountered a lot of issues with making a feature release branch out of develop and merging it to develop and main. 
There are issues with merge conflicts and rebasing content back so I propose that all action happens on the develop branch and once a successful release is done we sync the main with develop with merging.
2. Tag creation happens on develop branch so the creation of release notes should work as expected. 
3. All actions are set for release with tag latest and with dry run disabled - user can always choose different settings there.
4. Added a release-all script, which releases all packages. I made sure there is a dependency on successful core release for angular and react wrappers.   
**How to test it**
Check the lines and see if you find …

ci(release-scripts): run on develop and release all

---

packages/core/src/components/datetime/readme.md
packages/core/src/components/icon/readme.md
packages/core/src/components/popover-core/readme.md
packages/core/src/components/slider/readme.md
packages/core/src/components/slider/slider.stories.tsx
packages/core/src/components/slider/slider.tsx
packages/core/src/components/text-field/readme.md

Slider component spam users as we emit tdsChange on every move of the thumb. That made users use timeout functions to prevent it. The solution is to emit tdsChange once the user lifts the finger from the mouse or there is an end of touch (for touch devices).
Fixes: [CDEP-3199](https://tegel.atlassian.net/browse/CDEP-3199)
1. Open the preview Storybook of this branch and the production version of Storybook.
2. Open inspector and observe Console.
3. Move the thumbs of the slider left and right. Production one emits events all the time, while in this PR it happens only once the user releases the mouse button or stops touch.
4. Also, check behavior for snapping points, increase via +/- buttons as well as input. 
**Checklist …

fix(slider): emit tdsChange on mouse-up and touch-end events

---

packages/core/src/components/toast/readme.md
packages/core/src/components/toast/toast.scss
packages/core/src/components/toast/toast.stories.tsx
packages/core/src/components/toast/toast.tsx

Introduced prop to make close button optional to align with design in Figma.
2. Check in Toast component
3. Toggle the "Closable" control, make sure the close button toggles accordingly between visibility and hidden

feat(toast): make close button optional

---

packages/core/src/components/modal/modal.stories.tsx
packages/core/src/components/modal/modal.tsx
packages/core/src/components/modal/readme.md

Modal component, when rendered dynamically and simultaneously using selector/reference has an issue. It looks like the reference is lost after the initial render. That can be observed if the user navigates to other pages and returns to one where the component is. On the initial visit of the page, Modal opens, on revisit - it does not. 
What I did is to have the initialization of selector/reference in a later and more repetitive lifecycle method. The user can call the same method in case the lifecycle fails, just as a fallback solution. An additional thing was adding the removal of listeners once the component is destroyed - just to be neat and prevent performance and memory issues. 
Fixes: …

feat(modal): re-initilize selector and clean-up method

---

packages/core/src/components/text-field/readme.md
packages/core/src/components/text-field/test/read-only-with-suffix/index.html
packages/core/src/components/text-field/test/read-only-with-suffix/text-field.e2e.ts
packages/core/src/components/text-field/text-field.scss
packages/core/src/components/text-field/text-field.tsx

When using the suffix icon and read-only, the read-only icon takes priority, and the suffix icon remains hidden. 
Fixes: [CDEP-3182](https://tegel.atlassian.net/browse/CDEP-3182)
https://github.com/scania-digital-design-system/tegel/issues/522
1. Add suffix icon
2. Turn on "read-only"
3. Suffx icon should be hidden
4. PS. Please check that other controls like size, mode-variant, and state are working too. I had to change from using string literals to using an object way of writing CSS as string literals had some hiccups when changing values in runtime. 
[CDEP-3182]: https://tegel.atlassian.net/browse/CDEP-3182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …

fix(text-field): read-only hides suffix icon

---

packages/core/src/components/table/table-body-cell/readme.md
packages/core/src/components/table/table-body-cell/table-body-cell.tsx
packages/core/src/components/table/table-component-basic.stories.tsx
packages/core/src/components/table/table-header-cell/readme.md
packages/core/src/components/table/table-header-cell/table-header-cell.scss
packages/core/src/components/table/table-header-cell/table-header-cell.tsx

Additional `text-align` value for centering content inside `tds-header-cell` and `tds-body-cell` component.
**Solving issue**
Fixes: [548](https://github.com/scania-digital-design-system/tegel/issues/548)
1. Open StoryBook
2. Navigate to and open folder "Table"
3. Click on "Basic"
4. Examine the behavior of the table cells and the columns. For deeper explanation, open the "Docs"/code.
Before:
After:

fix(table-body-cell): Behavior and additional `text-align` values in `tds-header-cell` and `tds-body-cell`

---

packages/core/src/components/table/table-body-cell/readme.md
packages/core/src/components/table/table-body-cell/table-body-cell.tsx
packages/core/src/components/table/table/test/filtering/table.e2e.ts
packages/core/src/components/table/table/test/sorting/table.e2e.ts

tds-body-cell, when generated via for/while/map loop, missed internal event for text-align property from parent. That said, no matter body cell has prop for text-align itself, it does not get mapped to textAlignState as mapping was happening only in internal event. Now mapping is added to the lifecycle too. 
1. Check if prop will work in cases where cells are generated from JSON file, local textAlign prop on tds-body-cell has to have effect on text alignment.
React demo example with this code used via npm pack: https://github.com/scania-digital-design-system/tegel-react-demo/pull/176
PS: I increased tolerance on table test to 5% and made new screenshots too for two tests.

fix(table-body-cell): map text-align prop in lifecycle

---

packages/core/src/components/dropdown/dropdown-button.scss
packages/core/src/components/dropdown/dropdown-filter.scss
packages/core/src/components/dropdown/dropdown-vars.scss
packages/core/src/components/dropdown/dropdown.scss
packages/core/src/components/dropdown/dropdown.tsx

**Added a clear filter button**  
_Added a clear filter button since users gets confused how to use the filter ie that they have to delete the existing text in the input._
-
1. Go to...
2. Check in...
3. Run ...
Selecting the dropdown
After clicking the reset button

feat(tds-dropdown): added a clear filter button

---

packages/core/src/components/header/header-launcher/header-launcher.tsx

Adding a check for tds-header-launcher-list. 
If an element exists, we should add a class to the launcher list enabling it to take all available height on the screen.
We get an console.error that it is null. 
Fixes: [CDEP-3126](https://tegel.atlassian.net/browse/CDEP-3126)
2. Check in the Header and see that there is no error in the console.
3. Check this story `/?path=/story/patterns-navigation--few-navigation-items` in preview. It does not have tds-header-launcher-list, so launcher takes as much height is needed to present all items, but not more. In other stories tds-header-launcher-list is present so launcher takes 100% of available height. 
See screenshot for error:
**Aditional notes**
It seems we …

fix(header-launcher): null check

---

packages/core/src/components/popover-core/popover-core.tsx
packages/core/src/components/popover-menu/popover-menu.stories.tsx

Enable automatic closure of other instances of tds-popover-component when new one opens.
Cases like that are in
- Popover Canvas
- Popover Menu
- Tooltip 
Fixes: [CDEP-3105](https://tegel.atlassian.net/browse/CDEP-3105)
1. Go to the preview link in this PR.
2. Navigate to the Popover Menu story
3. Try to open one and then the second component. The first one should close when a new one opens.
[CDEP-3105]: https://tegel.atlassian.net/browse/CDEP-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(popover-core): close instances of component when another opens

---

packages/core/src/components/toast/toast.stories.tsx

Update default header, subheader and link text in Storybook example to align with design in Figma.
Fixes: [CDEP-3253](https://tegel.atlassian.net/browse/CDEP-3253)
2. Check in Toast component
3. Compare with design in [Figma](https://www.figma.com/file/d8bTgEx7h694MSesi2CTLF/Tegel-UI-Library?type=design&node-id=26756-59845&mode=design&t=DJl6JHpAQibOE9Xw-0)
[CDEP-3253]: https://tegel.atlassian.net/browse/CDEP-3253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

fix(toast): update default header, subheader and link text

---

packages/core/src/components/table/table-body-cell/table-body-cell.scss
packages/core/src/components/table/table-body-cell/table-body-cell.tsx
packages/core/src/components/table/table-header-cell/table-header-cell.scss

This PR enables disable-padding to work with compact design instead of the latter overwriting the former. It also sets a top and bottom padding on the Table header text to ensure padding even if the text is very long and breaks into multiple rows.
**Solving issue** 
Fixes: [CDEP-3194](https://tegel.atlassian.net/browse/CDEP-3194) and [CDEP-3215](https://tegel.atlassian.net/browse/CDEP-3215)
https://github.com/scania-digital-design-system/tegel/issues/469
https://github.com/scania-digital-design-system/tegel/issues/557
1. Go to Storybook link below.
2. Check in Table -> Basic.
3. Enable "Compact design" and "Disable cell padding".
4. Ensure the Table cell padding is disabled _and_ the Table header padding is reduced at the same time.
5. …

fix(table): disable-padding with compact design

---

packages/core/src/components/dropdown/dropdown.tsx

Setting default value does not work properly when used in environment where slotted content is loading slow. 
Fixes: 
- [CDEP-3192](https://tegel.atlassian.net/browse/CDEP-3192)
- https://github.com/scania-digital-design-system/tegel/issues/524
1. Check if setting default value still works as intended.
2. Try to set defaultValue to the element that does not exists yet in the dropdown menu. It should return warning message.
3. Try to add option that is matching defaultValue in run time, observe if it sets it correctly. 
[CDEP-3192]: https://tegel.atlassian.net/browse/CDEP-3192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): monitor slot changes to assigning defaultValue on dropdown menu update

---

README.md

Link for contribution docs was using main instead of develop branch
- **No issue:** Correcting link to contribution guide
1. Check if the link to the contribution guide is correct. Try to open link from document in new tab.

docs(contribution): link correction

---

.husky/pre-push

Moving running test from pre-commit to pre-push
- **No issue:** Making a better world for developers.
1. Run this branch on your local, and create another branch out of it.
2. Trying changing anything.
3. Try to commit, it should be instant.
4. Try to push that branch as remote or push your changes, it should take a bit more as unit tests are running.

ci(test): unit test to run on push commit instead of commit

---

packages/core/src/components/stepper/step/step.scss
packages/core/src/components/stepper/stepper.tsx

Fixes an issue where the first and last styling was not applied to tds-step after the initial render of tds-stepper. The issue was that the styling was applied inside the `componentWillLoad` method of the tds-stepper. Now it's applied using pure CSS and no longer depends on the component lifecycle.
Fixes an issue where padding-left was applied to the first tds-step element and padding-right was applied to the last tds-step element in horizontal mode.
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/630
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/631
1. Run storybook
2. Navigate to the stepper story
3. Check the first element has no padding left in horizontal mode
4. Check that the last element …

fix(stepper): correct first and last item padding

---

packages/angular-17/projects/components/package-lock.json
packages/angular-17/projects/components/package.json
packages/angular/package-lock.json
packages/angular/package.json
packages/core/package-lock.json
packages/core/package.json
packages/react/package-lock.json
packages/react/package.json

New version of Tegel to fix the issue with export of tegel.css file.
- **No issue:** There was a prod issue with version 1.9.0 and export of main CSS file for tegel. This version fixes it. 
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/640
1. Check PRs on demo pages

release: tegel 1.9.1

---

packages/core/package.json

Added type definitions that were missing when using modern TypeScript `moduleResolution` options, such as `bundler`.
- **GitHub:** #658
1. Go to...
2. Check in...
3. Run ...
I wasn't able to run the tests locally because of issues with Docker/WSL on my work laptop.

fix: add missing type definitions

---

packages/core/src/components/table/table-component-basic.stories.tsx
packages/core/src/components/table/table-header-cell/readme.md
packages/core/src/components/table/table-header-cell/table-header-cell.scss
packages/core/src/components/table/table-header-cell/table-header-cell.tsx

Simular to `table-body-cell` we add a prop to `table-header-cell` that removes all padding. Intended to be used when adding custom components like a `input` field in a header.
- **Jira:** https://tegel.atlassian.net/browse/CDEP-3429
1. Go to...
2. Check in...
3. Run ...

feat(table-header-cell): added disable padding prop

---

.github/workflows/create-release-pr.yml
.github/workflows/release-all.yml
.github/workflows/release-angular-17.yml
.github/workflows/release-angular.yml
.github/workflows/release-core.yml
.github/workflows/release-react.yml

- adding --no-verify flag to all push commands in release scripts
- remaking release all script, now with merging develop to main as part of the script
- **No issue:** These issues we encountered last couple of times during the release
1. Please check code and see if ti makes sense. If you have doubts, better flag it so we can check together.
2. I don't know if there is a proper way to test it, we may need to run it on the next release.

ci(release-scripts): no-verify flag and release-all script update

---

packages/core/src/global/scania-fonts-vars.scss
typography/scania-fonts-vars.scss

Fixing wrong font family usage in css variable for tds-headline-01
**No issue:** When using the headline-01 variable instead of the class you don't get the same header. Variable is using Scania Sans instead of Scania Sans Headline
This variable is not used in any component so have to test it in a separate project or use it temporarily in a component while verifying. Encountered this when using variable inside another stencil project with shadow dom enabled.

fix: use correct font family in headline 01 variable

---

packages/core/src/components/table/table/test/sorting/table.e2e.ts

Failing test in screenshots part.
- **No issue:** Sometimes the sorting test fails in screenshot taking. This is an attempt to improve its stability.
1. Have a branch in your local
2. Run `npm run test` a couple of times
3. The test for sorting feature of the table should pass
4. If any other test fails, please ping me so I can improve those too.

test(table:sorting): added waitFor to improve screenshot stability

---

packages/core/src/components/stepper/step/step.scss
packages/core/src/components/stepper/step/step.tsx

UI Improvements of stepper component
- **Jira:** Add ticket number after `CDEP-3348`: [items not aligned](https://tegel.atlassian.net/browse/CDEP-CDEP-3348)    
1. Go to stepper in storybook
2. Check that steps are aligned
3. Toggle small/large labels and so on...
4. Repeat in a non-webkit browser(e.g. Firefox)
Using -webkit becuase it was the only alignment property that did the trick, is not a standard, so it could be unreliable in the future? However looks good in both Chrome and Firefox.

fix(stepper): items not aligned

---

packages/angular-17/projects/components/package-lock.json
packages/angular-17/projects/components/package.json

Fix for an issue on peer dependencies. Using @scania/tegel-angular-17 should not require `--force` when installing.
- **No issue:** Being reported in [support channel.](https://teams.microsoft.com/l/message/19:5e33f67fe502441f914fbcdc6e2548f5@thread.skype/1716804816292?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1716804816292&teamName=Tegel%20Design%20System&channelName=Development%20support%20-%20Tegel&createdTime=1716804816292)
1. Pack the angular-17 code and test it on angular-17-demo page.
2. Installation of package should be smooth, without any additional flags like `--force` or `--peerDependencies`

fix(angular-17): dependency on version 17 or higher

---

packages/core/src/components/textarea/textarea.scss
packages/core/src/components/textarea/textarea.stories.tsx

Enable scrolling when in read-only mode.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-1183](https://tegel.atlassian.net/browse/CDEP-1183)    
1. Go to the preview link
2. Open textarea component
3. Set some long text using the "Text value" control
4. Try to scroll, it should work as expected and editing text should be possible
5. Set the component to read-only mode
6. Try to scroll, it should be possible but text editing should not be possible.
Additional control for value control is added.
[CDEP-1183]: https://tegel.atlassian.net/browse/CDEP-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(textarea): scroll in readonly mode

---

packages/core/src/components/button/button.scss
packages/core/src/components/popover-canvas/test/default/popover-canvas.e2e.ts

Small fix to full bleed button.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-1261](https://tegel.atlassian.net/browse/CDEP-1261)    
1. Go to the preview link
2. Check button with full bleed rule
3. There should be no changes in the behavior
[CDEP-1261]: https://tegel.atlassian.net/browse/CDEP-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): fullbleed 100% rule

---

packages/core/src/mixins/_scrollbar.scss

After changes in dropdown scroll we lost background color in track. 
- **No issue:** 2 users have already complained about this in support channel. I have added variable to scrollbar track instead of transparent value. It has been checked in Chrome, Firefox and Safari - works in all three.
1. Go to the preview link and check if the scrollbar in the dropdown has a background color. Use a different background in Storybook to check it.

fix(dropdown): scrollbar background color

---

packages/core/src/components/banner/banner.scss

The icon has a padding of 20px on the left. When no icon is used, text comes to the left side of the component. 
I have added padding of 16px left when no icon is there and an additional 4px in the icon component to keep it per design.
No test needed to be updated as there is no visual change. 
- **Jira:** Add ticket number after `CDEP-`: [CDEP-2899](https://tegel.atlassian.net/browse/CDEP-2899)    
1. Go to the preview link.
2. Check the Banner component
3. Check the option with any random icon, check with "none".
4. There should be padding on 16px the the left when just text is there and 20px (16px + 4px) when icon is used.
[CDEP-2899]: https://tegel.atlassian.net/browse/CDEP-2899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(banner): padding left in no icon variation

---

packages/core/src/components/dropdown/dropdown.tsx

If the dropdown does not have children, but the default option is set, it would throw a lot of errors in the console.
Some users have an async way of adding data later to the component so they end up in errors even if their state is "normal".
Now we stop processing in the early stage. Also lopping over dropdown items is improved.  
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3116](https://tegel.atlassian.net/browse/CDEP-3116)    
1. Open the preview link
2. Check if adding a default value works as expected in the component
3. Try to add more items to the dropdown during the lifetime (fun times in the console ahead :D )
I might try to set up an example on one of the demo pages if needed.
[CDEP-3116]: https://tegel.atlassian.net/browse/CDEP-3116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …

fix(dropdown): async data source handling

---

packages/core/src/components/header/header-title/header-title.scss
packages/core/src/components/header/header-title/header-title.tsx
packages/core/src/components/header/header.scss

The header was not using any of the heading elements (h1-h6 for the title )which led to accessibility warnings in the console. While improving it, I found some of the lines of code that were not used so I cleaned it a bit. 
- **No issue:** User reported in the support channel.
1. Check preview link
2. Make sure Header title looks like one in [prod](https://tds-storybook.tegel.scania.com/?path=/story/components-header--default)

refactor(header-title): code clean-up and improvement

---

packages/core/src/components/table/table-body-row-expandable/readme.md
packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.scss
packages/core/src/components/table/table-component-expandable-rows.stories.tsx

Any elements, that are wider than the available width inside the expand-row slot, should overflow instead of expanding the entire table.
- **Jira:** [CDEP-3353: The expand-row slot expands the entire table instead of overflowing](https://tegel.atlassian.net/browse/CDEP-3353)     
1. Go to: `table-component-expandable-rows.stories.tsx`
2. Replace `<div slot="expand-row">Hello world 1</div>` with some wider content for example:  
```
<div slot="expand-row">
<tds-body-cell cell-value="Test value 1" cell-key="truck"></tds-body-cell>
<tds-body-cell cell-value="Test value 2" cell-key="driver"></tds-body-cell>
<tds-body-cell cell-value="Test value 3" cell-key="country"></tds-body-cell> …
```

fix(table): scroll instead of expanding parent

---

.github/workflows/release-all.yml
.github/workflows/release-angular-17.yml
.github/workflows/release-angular.yml
.github/workflows/release-react.yml
package.json
packages/angular-17/package-lock.json
packages/angular-17/package.json
packages/angular-17/projects/components/ng-package.json
packages/angular-17/projects/components/package-lock.json
packages/angular-17/projects/components/package.json
packages/angular/package-lock.json
packages/angular/package.json
packages/angular/projects/components/package-lock.json
packages/angular/projects/components/package.json
packages/core/package-lock.json
packages/core/package.json
packages/react/package-lock.json
packages/react/package.json
packages/styles/package-lock.json
packages/styles/package.json

- Fixing issues with wrapper packages after the addition of a new component 
- Renaming build commands 
- Updating Angular-17 wrapper to export components project directly in dist, instead of dist/components it used to be. 
- **No issue:** There was an issue with the beta release of tables. The core problem was that wrapper packages did not have the dependency on @scania/tegel package.
- Also, Angular-17 got .npmignore file in build process which removes package.json of component when shipping the code so apps consuming wrappers do not know where to load the module from.
1. Create a packed file with `npm pack` of `packages/core`
2. Install that file in one of the wrapper packages. Note: Angular needs it on `packages/angular` and `packages/angular/projects/components` levels
3. Try to run …

build: release script and wrappers improvement

---

packages/core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss

#556
Update CSS selector to hide the arrow on a breadcrumb to `.current` since .current is always last.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-](https://tegel.atlassian.net/browse/CDEP-)    
- **GitHub:** #556
1. Go to Breadcrumbs
2. Make sure the last breadcrumb has no arrow
3. Try it in the demo pages
4. Make sure to try it by navigating between pages

fix(breadbrumbs): update CSS selector to .current since .current is always last.

---

packages/core/src/components/table/table-body-row-expandable/readme.md
packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.scss
packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
packages/core/src/components/table/table-component-expandable-rows.stories.tsx

The purpose of this PR is to provide an option to remove the padding in the expanded area. Additionally, I want to have control over the overflow behavior. Otherwise, it might cause elements like dropdowns to be cut off.
The proposed technical solution is to add a "part" that allows styling of the expanded area in an expanded table row. This would enable adjustments like removing padding, allowing the expanded area to utilize its full width.
More information can be found in the Teams channel "Development support - Tegel".
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/785

feat(table): add part for the cell in the expanded row of the table. add visible for overflow.

---

packages/core/src/components/table/table-component-expandable-rows.stories.tsx

Adding missing config for storybook controls on expandable story
- **No issue:** Issue spotted "on-fly"
1. Go to preview link
2. Check Table Expandable rows story
3. Check that overflow control has default "auto" and possibility to switch to "hidden" and "visible"

docs(storybook-table): controls for overflow

---

.github/workflows/holy-grail.yml
.github/workflows/release-all.yml

This is a new script that should contain all release steps in one action, from bumping the version in core and wrappers to merging develop to main. It creates a release branch which is used to add all files changes and serves like a form of memory in the release process.
Changes done:
- dryRun is removed in favor of "smoke-script" which will be used as regression test before this script.
- version is output only once, in create release branch step and all other steps depend on it
- `npm ci` is used instead of `npm i` to improve stability
- release branch is created and used as memory dump to keep track of all package.json changes across the release process
- **Jira:** Add ticket number after `CDEP-`: …

ci: release script improvements

---

.github/workflows/holy-grail.yml

- Separating version bump in all wrappers to separate job 
- Removing committing and push from wrappers 
- The branch dept is set to 1 for wrappers as they do not need other branches but just release branch
- **No issue:** In last release we had issue where not every wrapper committed changes done in`package.json` and `package-lock.json` files. Now, as bumping is extracted from all of the wrappers and made into separate step, I think we should have all the versions in place after successful release.
1. Check if code makes sense.
Partial jobs might be tried with ACT. So feel free to test it.

ci(holy-grail): improvements

---

packages/core/src/components/slider/slider.tsx

Removed preventDefault for touchmove.
**Tested on:**
- Chrome device: Galaxy S8+, Surface Pro 7, iPhone SE, iPad Air
- Physical devices: iPhone 14 Pro Max, iPad Pro
Issue was confirmed on Chrome emulated android devices.
- **Jira:** [CDEP-3566](https://tegel.atlassian.net/browse/CDEP-3566)
- **GitHub:** [812](https://github.com/scania-digital-design-system/tegel/issues/812)
1. Go to amplify link in chrome.
2. Open any android device through inspector device emulator, slider should now work.
[CDEP-3566]: https://tegel.atlassian.net/browse/CDEP-3566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tds-slider): removed preventDefault for touchMove

---

.github/workflows/smoke-test-all.yml
.github/workflows/smoke-test-failure-webhook.yml
.github/workflows/smoketest-webhook.yml

Added a Teams channel webhook that triggers a post with information once a failing smoke test occurs.
- **Jira:** [ci: Smoke test webhook in dev channel](https://tegel.atlassian.net/browse/CDEP-3562)
1. Go to GitHub Actions
2. Check for failed smoke test
3. If that is the case, check in teams channel under "IXI - Corporate Digital Experience -> Failed Jobs" for more information
More improvements of the smoke test will be done in different PR:s

build: smoke test webhook

---

packages/core/src/components/text-field/text-field-vars.scss
packages/core/src/components/text-field/text-field.scss
packages/core/src/components/text-field/text-field.tsx

This PR address the color on the text field counter label when its disabled. Adding a more toned down grey color to it when its disabled.
[CDEP-2669](https://tegel.atlassian.net/browse/CDEP-2669?atlOrigin=eyJpIjoiOGIxZWM0NGQyZWUxNGJiMWIwNmQ1NGRmZTc2MjI1ODMiLCJwIjoiaiJ9)
1. Go to aws storybook link
2. Navigate to the textfield component 
3. Add an limit to the textfield text and toggle disabled controller to true. 
4. Make sure it works as intended.
5. Also change to dark mode to make sure it looks good here as well.
[CDEP-2669]: https://tegel.atlassian.net/browse/CDEP-2669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(text-field): counter label color in disabled state

---

packages/core/package.json

Updating the package.json file so that we store prettier in dev-dependancies instead of dependancies.
[CDEP-3453](https://tegel.atlassian.net/browse/CDEP-3453?atlOrigin=eyJpIjoiNTY4MDY2YzMxZTZlNDgyN2JjYTA3OTg0M2JhOTk5NDMiLCJwIjoiaiJ9)
Checkout to this branch and try to spin up the project.
[CDEP-3453]: https://tegel.atlassian.net/browse/CDEP-3453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(package): restore prettier as a dev dependency

---

packages/core/src/components/text-field/text-field.tsx

The label inside in text field component has an issue. On focus it appears larger then it should be, it jumps in size.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3598](https://tegel.atlassian.net/browse/CDEP-3598)    
1. Open the preview link
2. Check the Text Field component
3. Set a label inside, type some text and click outside and then back inside
4. Label should not change size or position
5. Do the same in prod or develop branch and observe the issue
Video of issue:
https://github.com/user-attachments/assets/133a328b-e56d-487c-911b-9b99e3b96979
[CDEP-3598]: https://tegel.atlassian.net/browse/CDEP-3598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(text-field): label inside

---

packages/core/src/components/button/button.scss
packages/core/src/components/button/button.tsx
packages/core/src/components/button/test/disabled/button.e2e.ts

Added `disabled` attribute on host level and `pointer-events: none` once component is in disabled state so no event fires when the component is in that state. 
Additionally, I cleaned up the focus state so it uses mixin and only in one place, other places seemed to be repetitive without any value. 
- **Jira:** Add ticket number after `CDEP-`: [CDEP-3600](https://tegel.atlassian.net/browse/CDEP-3600)    
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/833
1. Read the GitHub issue and how to recreate it.
2. Go to preview link.
3. Try to recreate the issue.
4. Try the same in production Storybook.
5. Preview link should behave as expected.
As `pointed-events: none* rule are used, not-allowed cursor style is not possible to be …

fix(button): host in disabled state

---

packages/core/src/components/datetime/datetime.tsx
packages/core/src/components/datetime/readme.md

This PR adds a method to reset the value of the datetime back to `''` or `defaultValue` if set.
I based this on the Dropdown `reset()` method. 
This is my first PR for **tegel**, so let me know if everything is ok.
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/821
1. Whether you're using angular, react or web components:
2. Get datetime's element reference.
3. Invoke the `reset()` method.
4. Value should've gone back to default or `''`
- [ x Not breaking production behavior
The Contributing file, doesn't really explain how to properly test locally. 
There is a valid observation to add that both tegel, and tegel-{framework} should be built and link in …

feat: add a method to reset datetime value

---

docs/CONTRIBUTING.md

Adds a short but sweet guide to play locally with changes made to the Tegel Design System. helping future contributors test behaviors thoroughly.
- **No issue:** No guide on how to test Tegel locally.
Keeping my word #861

docs: add a guide to test changes locally

---

packages/core/src/components/popover-canvas/test/show-true/popover-canvas.e2e.ts
packages/core/src/components/popover-menu/test/show/popover-menu.e2e.ts

Popover test should accept a 5% pixel diff.
- **Jira:** [CDEP-3548](https://tegel.atlassian.net/browse/CDEP-3548)
1. All popover test should pass, consistently.
[CDEP-3548]: https://tegel.atlassian.net/browse/CDEP-3548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: popover test accepting a pixel diff ratio

---

.github/workflows/playwright.yml
packages/core/playwright.config.ts

testing to save screenshots on failure

ci: saving screenshots of failing tests

---

packages/core/src/components/header/header-dropdown/header-dropdown.scss

Fixes the header dropdown chevron to rotate when the element is clicked.
- **Jira:** [CDEP-3768](https://tegel.atlassian.net/browse/CDEP-3768)   
1. Open storybook
2. Go to Patterns → Navigation → Few Navigation Items.
3. Make sure that your window is wide enough that it shows the chevron icon element "Wheel Types" in the header without having to open the side menu
4. Click the "Wheel Types" button
None
None
[CDEP-3768]: https://tegel.atlassian.net/browse/CDEP-3768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(header-dropdown):  chevron icon rotation

---

packages/core/src/components/slider/slider.tsx

This pull request addresses an issue in the updateValue method of the tds-slider component, where the slider thumb exhibited "jumping" behavior when decreasing values. To fix this issue I replaced the `Math.trunc` to `Math.round`. 
Math.trunc always rounds downwards, so 4.9 becomes 4. This results in a flaky appearance.
- **Jira:** Add ticket number after: [CDEP-3125](https://tegel.atlassian.net/browse/CDEP-3125)    
1. Go to aws link
2. Navigate to the slider component
3. decrease and increase the value of the slider and make sure it operates smooth.
https://github.com/user-attachments/assets/bdc68c76-ac92-4eba-a3e9-f57f506c4aca
[CDEP-3125]: https://tegel.atlassian.net/browse/CDEP-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(slider): improve value snapping and calculation logic

---

packages/core/src/stories/Installation/javascript.stories.ts

Fixes the issue of the console.log warning related to "undefined" language. This isn't necessarily a good solution, it's more of a work-around I would say. Please read _Additional context_ below.
- **Jira:** [CDEP-2660](https://tegel.atlassian.net/browse/CDEP-2660)
1. Go to https://tds-storybook.tegel.scania.com/?path=/story/components-accordion--default
2. Open browser console
3. Click any of the toggles for the props of the component
4. Notice the warning messages
5. Go to https://pr-990.d3fazya28914g3.amplifyapp.com/?path=/story/components-accordion--default
6. Repeat steps 2-3 and note that the warning messages don't appear
None
I did a bit of digging by modifying files in node_modules, and my understanding now is this:
In **packages/core/src/stories/Installation/javascript.stories.ts* …

fix: highlight language warning in browser console

---

.github/workflows/smoke-test-all.yml
.gitignore

File name was changed. Probably that was the cause of the teams webhook not running.
Also added a job to echo out the node version.

fix: name change webhook file and print node version

---

packages/core/src/components/chip/chip.stories.tsx
packages/core/src/components/chip/chip.tsx

Added a internal event to listen to so if chip has type `radio` it responds to other `tds-chip` component changing.
- **Jira:** [CDEP-3818](https://tegel.atlassian.net/browse/CDEP-3818)
- **GitHub:** [Issue 983](https://github.com/scania-digital-design-system/tegel/issues/983)
1. Go to amplify link
2. Go to chip component
3. Click type `radio`
4. Inspect `tds-chip` in the browser, the checked flag should now move to next clicked element.
[CDEP-3818]: https://tegel.atlassian.net/browse/CDEP-3818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(chip): Internal event for radio button

---

.github/workflows/holy-grail.yml

This pull request updates our GitHub Actions workflow to address the recurring merge conflicts between the develop and main branches. The conflicts have been causing disruptions in our release process, primarily due to file modifications, deletions, and renames that cannot be automatically resolved.
Consistency: By resetting main to match develop, we ensure that the main branch always reflects the latest and most accurate state of our codebase.
This approach eliminates the need for manual conflict resolution, streamlining our release process and reducing potential errors.
It simplifies our workflow by ensuring that main is always an exact copy of develop, reducing the complexity of managing two diverging branches.
The workflow now includes a step to git reset --hard develop on the main …

ci(holy-grail): sync develop and main

---

packages/core/src/components/tooltip/tooltip.scss

Tooltip tends to claim space in user's application as it has no position defined. We control it by visibility attribute but in some occasions, it tends to occupy space and break the layout. With position absolute issue is removed. 
Text wrapping: additional CSS rule is added to help text wrapping due to limited width.
- **No issue:** Came in support channel.
1. Compare the preview link with the prod Storybook.
2. There should be no changes.

fix(tooltip): space claim and text wrapping

---

packages/core/src/components/slider/slider.tsx

Fixes native form reset handling of the slider component.
- **Jira:** [CDEP-3820](https://tegel.atlassian.net/browse/CDEP-3820)
Unfortunately the form-test repo doesn't create amplify links for PRs, so this has to be done manually to test:
1. Clone this repo: https://github.com/scania-digital-design-system/form-test
2. Check out to branch slider-demo
3. Remove node_modules
4. Run `npm install`
5. Run `npm run start`
6. Open http://localhost:3000/
7. Open browser console and consider only the right panel
8. Click anywhere on the tds-slider component to set it to a new value
9. Click the submit button, see the console
10. Click the reset button
11. Click the submit button, see the console and note that the reset value is logged
None
Thanks to @mistermalm for inspiration with event listener …

fix(slider): native style form reset handling

---

packages/core/src/components/popover-menu/popover-menu-item/popover-menu-item.scss

Sets the cursor to not-allowed when hovering on a disabled menu item.
- **Jira:** [CDEP-165](https://jira.scania.com/browse/CDEP-165)
1. Go to https://pr-1017.d3fazya28914g3.amplifyapp.com/?path=/story/components-popover-menu--default
2. Click the blue popover-menu button
3. Hover over the disabled menu item and see that the cursor becomes not-allowed
None
None

fix(popover-menu): disabled option cursor

---

packages/core/src/components/slider/slider.scss

The clickable area of the Slider is too narrow in current solution. This PR adds an invisible clickable area that does not affect visual appearance. 
- **Jira:** [CDEP-147](https://jira.scania.com/browse/CDEP-147)
2. Check in Slider component
3. Compare to the one in production and verify clickable area is bigger.

fix(slider): increase clickable area of slider

---

packages/core/src/components/accordion/accordion-item/accordion-item.tsx
packages/core/src/components/accordion/accordion-item/readme.md
packages/core/src/components/accordion/accordion.stories.tsx

This PR adress the typescript error we got after merge PR (feat(accordion): accessibility improvement  (https://github.com/scania-digital-design-system/tegel/pull/1018))
Instead of naming the aria-level Prop ariaLevel, we rename it to ariaLevelValue to avoid any conflicts with existing naming.
1. Checkout to the branch
2. run npm run build:all and make sure it runs with no issue.

fix(accordion): rename ariaLevel prop to ariaLevelValue

---

packages/core/src/components/text-field/text-field.tsx

removed linter warnings:
`@stencil/core` import should occur before import of `../../utils/hasSlot`
`Arrow function should not return assignment.`

chore(textfield): removed linter warning

---

packages/core/src/components/toggle/toggle.tsx

- **Jira:** `Toggle - ternary operators in class names`: [CDEP-220](https://jira.scania.com/browse/CDEP-220)
2. Check that toggle headline and disable is working

chore(toggle): refactor ternary operators

---

packages/core/src/components/block/block.stories.tsx
packages/core/src/components/block/block.tsx
packages/core/src/components/block/readme.md
packages/core/src/components/block/test/block.axe.ts
packages/core/src/utils/axeHelpers.ts

The pull request addresses the issues we have found in the a11y audit related to the block component.
✅ Added analyze test file to component
✅ Make sure its possible to navigate the nested blocks with screen reader.
✅ Added a prop called componentTag so the user can decide which html tag the block should be
✅ Update storybook documentation to use meaningful HTML elements for structure
- **Jira:**  [CDEP-301](https://jira.scania.com/browse/CDEP-301)    
Verify Keyboard Accessibility for Interactive Child Blocks
1. Go to react demo page /about [[LINK TO REACT DEMO PAGE](https://pr-220.d2vh2lmnzgzrkl.amplifyapp.com/about)]
2. Turn on screen reader
3. Try to navigate through the blocks with a screenreader [control+option + arrow right/left]. 
(I tested …

feat(block): accessibility improvements

---

packages/core/src/components/datetime/datetime.tsx

refactor ternary operators + odd looking icon
- **Jira:** `Datetime - ternary operators in class names`: [CDEP-227](https://jira.scania.com/browse/CDEP-227)
2. Play around with datetime
3. Check that Icon looks ok
Before removing icons:
After:
There is something odd with the icon in the datetime component, I removed the two icons in the code because they did not seem to make any impact, let's see what happens...

chore(datetime): refactor ternary operators 

---

packages/core/src/components/chip/chip.stories.tsx
packages/core/src/components/chip/chip.tsx
packages/core/src/components/chip/test/checkbox/chip.axe.ts
packages/core/src/components/chip/test/checkbox/index.html
packages/core/src/components/chip/test/default/chip.axe.ts
packages/core/src/components/chip/test/default/index.html
packages/core/src/components/chip/test/radio/chip.axe.ts
packages/core/src/components/chip/test/radio/index.html

Improves accessibility in the Chip component.
- **Jira:** [CDEP-308](https://jira.scania.com/browse/CDEP-308)
Not implemented. See additional notes.
Not implemented. See additional notes.
1. Go to https://pr-1062.d3fazya28914g3.amplifyapp.com/?path=/story/components-chip--default&args=inputType:Radio to test radio type chips
2. Open dev tools
3. Inspect the chips that are checked and verify that their input elements have the attribute aria-checked="true"
4. Inspect the chips that are not checked and verify that their input elements have the attribute aria-checked="false"
5. In the storybook controls, change the chip type to checkbox
6. Repeat steps 3-4
1. Go to https://pr-1062.d3fazya28914g3.amplifyapp.com/?path=/story/components-chip--default to test button type chips
2. Open dev tools …

feat(chip): improve accessibility

---

packages/core/src/components/button/button.stories.tsx
packages/core/src/components/button/button.tsx
packages/core/src/components/button/readme.md
packages/core/src/components/button/test/basic/button.axe.ts

Improves accessibility for the Button component
- **Jira:** [CDEP-304](https://jira.scania.com/browse/CDEP-304)
1. Go to preview link and open Button component page
2. Open browser console
3. Focus on the button by tabbing to it
4. Click the button
5. Notice the event mentioned in the console
1. Go to preview link and open Button component
2. Activate the "only icon" option for Button in storybook controls
3. Inspect the button
4. Make sure that it has aria-label="A button component" (or whatever text is in the input field in the storybook controls for Aria Label)
None
None

feat(button): improve accessibility

---

packages/core/src/components/header/header-item/header-item.tsx

- Updated the `tds-header-item` component to listen for changes on the native "order" attribute using a MutationObserver.
- When the "order" attribute changes (for example, set to "end"), the component updates its inline CSS `order` property accordingly (e.g., "end" sets the order to "1", otherwise it defaults to "0").
- This solution allows dynamic reordering of header items without introducing a new prop and without re-rendering all child components.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-](https://jira.scania.com/browse/CDEP-347)
- **GitHub:** [Include issue link  ](https://github.com/scania-digital-design-system/tegel/issues/528)
1. visit the angular demo page: https://pr-127.d1ax919pz49q2z.amplifyapp.com/
2. Go to about us
3. Rich …

feat(header-item): header item ignores end slot

---

packages/core/src/components/toggle/readme.md
packages/core/src/components/toggle/test/default/toggle.axe.ts
packages/core/src/components/toggle/toggle.stories.tsx
packages/core/src/components/toggle/toggle.tsx

Added accessibility test and `aria-label`.
Removed lingering label object in dom if no label slot is provided.
- **Jira:** [[CDEP-430](https://jira.scania.com/browse/CDEP-)](https://jira.scania.com/browse/CDEP-430)
1. Go to amplify link
2. Navigate to toggle component
3. Change label text in controls should change `aria-label` & remove text in controls should remove label object in dom
Do think we can skip refactoring the focus state, this is good enough in my opinion but will of course run this by designers even if we merge this PR as is.

feat(toggle): added accessibility test and aria-label

---

color/_scania-color-primitives.scss

New primitives color palette for Tegel from Tegel project
- **Jira:** Add ticket number after `CDEP-`: [CDEP-395](https://jira.scania.com/browse/CDEP-395)
1. Check the [Figma file](https://www.figma.com/design/oXyzzbDmusEfy6GWIbyEEw/TRATON-UI-Kit-(Frozen)?m=auto&node-id=0-1&vars=1&var-id=3-3).
2. Compare color names and values. They should match.
Note: prefix --tds2 is added to avoid conflicts with current palette. It will be changed to --tds once we change all components and we phase out the current palette in use. 
File is not connected to any other CSS file. That will happen in later stage of project.

feat(color): new brand primitives for Tegel

---

packages/core/src/components/link/link.tsx
packages/core/src/components/link/test/default/index.html
packages/core/src/components/link/test/default/link.axe.ts

Added accessibility test
preventing enter keydown when disabled
preventing focus when disabled
- **Jira:** [CDEP-417](https://jira.scania.com/browse/CDEP-417)
1. Go to amplify link
2. Navigate to Link component
3. Disable link and try to tab -> Enter on link

feat(link): improve accessibility

---

packages/core/src/components/checkbox/checkbox.stories.tsx
packages/core/src/components/checkbox/checkbox.tsx
packages/core/src/components/checkbox/readme.md
packages/core/src/components/checkbox/test/default/checkbox.axe.ts
packages/core/src/components/checkbox/test/default/index.html

Addresses the accessibility improvements in the Checkbox component.
- **Jira:** [CDEP-307](https://jira.scania.com/browse/CDEP-307)
Not implemented, see additional context.
Not implemented, see additional context.
This is an alternative to Scenario 2 for the current implementation. @ckrook or @Lunkan89 please confirm whether this test is sufficient.
1. Go to https://pr-1057.d3fazya28914g3.amplifyapp.com/?path=/story/components-checkbox--default
2. Open dev tools
3. Inspect the checkbox and verify that its input element has aria-label="A checkbox component" (or whatever text is in the Aria Label input in the storybook controls)
4. Make sure that the screen reader reads the aria-label.
Not implemented, see additional context.
This is an alternative to Scenario 3 for the current …

feat(checkbox): improve accessibility

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx
packages/core/src/components/dropdown/dropdown.stories.tsx
packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/dropdown/readme.md
packages/core/src/components/dropdown/test/basic/dropdown.axe.ts
packages/core/src/components/dropdown/test/basic/index.html
packages/core/src/components/dropdown/test/default/dropdown.e2e.ts
packages/core/src/components/dropdown/test/error/dropdown.e2e.ts
packages/core/src/components/dropdown/test/filter/dropdown.axe.ts
packages/core/src/components/dropdown/test/filter/index.html
packages/core/src/components/dropdown/test/multiselect/dropdown.e2e.ts

* Added accessibility test for basic dropdown
* Added accessibility test for filter dropdown
* Moved current `aria`-attributes to interactive elements
* Added `aria-label`, `aria-disabled`, `aria-orientation`, `aria-multiselectable`
* Fixed failing test (Removed some `aria-selected` expects in e2e test since we have axe tests now)
**NOTE**
Not tested `multiselect` yet since that uses `tds-checkbox`( which is not ready yet) within `tds-dopdown-option`
- **Jira:** [CDEP-432](https://jira.scania.com/browse/CDEP-)
1. Go to Amplify.
2. See that `aria`-attributes behave as expected.
3. Try out a wider wrapper to confirm responsiveness.

feat(dropdown): accessibility improvements

---

typography/_scania-fonts.scss

Added WOFF2 format support to all Scania Sans font declarations to improve font loading performance. The WOFF2 format is now the primary format, with WOFF as a fallback, and local assets as the final fallback.
Jira: https://jira.scania.com/browse/CDEP-202
This is a performance optimization to leverage modern font formats. WOFF2 offers better compression than WOFF, resulting in faster font loading times and reduced bandwidth usage.
Go to any page using Scania Sans fonts
Check in browser dev tools (Network tab) that fonts are being loaded in WOFF2 format
Verify that fonts still display correctly in all browsers
Test fallback behavior by temporarily disabling WOFF2 support in browser
No UI changes - this is a performance optimization that doesn't affect visual appearance.
- Added WOFF2 as …

feat(typography): woff2 as additional format

---

packages/core/src/components/modal/modal.stories.tsx
packages/core/src/components/modal/modal.tsx
packages/core/src/components/modal/readme.md
packages/core/src/components/modal/test/default/modal.axe.ts

Improved accessibility for modal component.
- **Jira:** [CDEP-419](https://jira.scania.com/browse/CDEP-419)
**Feature: Ensure component responsiveness**
Given the component is rendered in Storybook 
When viewport changes width 
Then the component should adjust its size accordingly without layout breaks 
And it should maintain a clear and consistent UI
_Seems to be working already, please resize window and look at container and text behavior._
**Scenario: Moving Focus to the First Tabbable Element Inside the Dialog**
Given a dialog is open and the focus is on the last tabbable element inside the dialog
When the user presses Tab to navigate further
Then the focus …

feat(modal): accessibility improvements

---

typography/_scania-fonts.scss
typography/_traton-fonts.scss
typography/tokens/_typography-scania.scss
typography/tokens/_typography-traton.scss

Adding font-face declarations for traton and fallback fonts for both Traton and Scania
- **Jira:** [CDEP-570](https://jira.scania.com/browse/CDEP-570)
1. Login into AWS and verify the [uploaded font files](https://eu-west-1.console.aws.amazon.com/s3/buckets/digitaldesign-assets?region=eu-west-1&bucketType=general&prefix=fonts%2Ftraton%2F1.0.0%2F&tab=objects) and paths looks correct compared to the _traton-fonts-scss.

feat(typography): add typography files for Traton and fallback fonts

---

color/_traton-usage-tokens.scss
packages/core/.storybook/preview.js
packages/core/src/global/global.scss
packages/core/src/global/multibrand-development.scss
packages/core/src/global/traton.scss
packages/core/stencil.config.ts
typography/_traton-fonts.scss
typography/tokens/_typography-traton.scss

A proposal on we can test multibrand in the development phase via different CSS files and how to switch brands in Storybook.
Jira: CDEP-399
1. Set environment variable STORYBOOK_ENV=dev in your local environment
2. Run Storybook using npm run storybook
3. Look for the brand switcher in the Storybook toolbar
4. Switch between Scania and Traton brands
5. Verify that:
6. The HTML tag's class changes accordingly
7. The window.TDS_BRAND variable updates
8. The BRAND_CHANGED event is emitted
9. Verify that in non-dev environments (when STORYBOOK_ENV=dev is unset):
10. The brand switcher is not visible
11. The brand remains fixed as 'scania'
[x] No accessibility violations in Storybook
[] I have added unit tests for my changes (if applicable)
[x] All existing tests pass
[ ] I have updated the …

feat: multibrand development and storybook control

---

packages/core/src/components/header/header-brand-symbol/header-brand-symbol.tsx
packages/core/src/components/header/header-brand-symbol/readme.md
packages/core/src/components/header/header-dropdown/header-dropdown.tsx
packages/core/src/components/header/header-dropdown/readme.md
packages/core/src/components/header/header-hamburger/header-hamburger.tsx
packages/core/src/components/header/header-hamburger/readme.md
packages/core/src/components/header/header-launcher-button/header-launcher-button.tsx
packages/core/src/components/header/header-launcher-button/readme.md
packages/core/src/components/header/header-launcher/header-launcher.tsx
packages/core/src/components/header/header-launcher/readme.md
packages/core/src/components/header/header.stories.tsx
packages/core/src/components/header/test/default/header.axe.ts
packages/core/src/components/header/test/default/index.html
packages/core/src/components/side-menu/side-menu.stories.tsx
packages/core/src/stories/patterns/navigation/navigation-basic.stories.tsx
packages/core/src/stories/patterns/navigation/navigation-fewitems.stories.tsx
packages/core/src/stories/patterns/navigation/navigation-manyitems.stories.tsx
packages/core/src/stories/patterns/navigation/navigation-user-menu.stories.tsx

Improves accessibility for the Header component.
- **Jira:** [CDEP-416](https://jira.scania.com/browse/CDEP-416)
 
> Scenario: Closing the Right-Side Menu with the Escape Key 
> Given the right-side menu is open  
> When the user presses the Escape key  
> Then the right-side menu should close  
> And focus should return to the previously focused element
This has been fixed for header-launcher and header-dropdown, see Scenario 4.
See Additional context.
> Scenario: Focusing on Sidebar Content When Opening the Left-Side Menu 
> Given the left-side menu is opened  
> When the menu becomes visible  
> Then the focus should directly move to the first interactive element within the sidebar  
> And keyboard users should be able to navigate seamlessly
This has been fixed for header-launcher and …

feat(header): accessibility improvements

---

packages/core/src/components/toast/readme.md
packages/core/src/components/toast/test/information/toast.axe.ts
packages/core/src/components/toast/toast.stories.tsx
packages/core/src/components/toast/toast.tsx

Toast component accessibility improvements.
- **Jira:** [CDEP-429](https://jira.scania.com/browse/CDEP-429)
**Feature: Ensure component responsiveness**
Given the component is rendered in Storybook 
When viewport changes width 
Then the component should adjust its size accordingly without layout breaks 
And it should maintain a clear and consistent UI
**Scenario: Announce Dynamic Content with aria-live**
Given the component is rendered in Storybook
When dynamic content is displayed, such as a toast message
Then aria-live should be added to ensure the content is properly announced by screen readers
But currently, aria-live is missing, so dynamic updates are not announced to users
**Scenario: Clarify Close Button Function with aria-label**
Given the …

feat(toast): accessibility improvements

---

packages/core/src/components/radio-button/radio-button.stories.tsx
packages/core/src/components/radio-button/radio-button.tsx
packages/core/src/components/radio-button/readme.md
packages/core/src/components/radio-button/test/default/radio-button.axe.ts

Improved accessibility for radio-button component.
- **Jira:** [CDEP-422](https://jira.scania.com/browse/CDEP-422)
**Scenario: Navigating Between Radio Buttons Using Tab & Shift+Tab**
Given a user is navigating a form with radio buttons
When the user presses the Tab or Shift+Tab keys
Then the focus should move between radio buttons correctly
_This only applies for radio buttons in groups, which we do not facilitate. Added a `tdsTabIndex` -prop which can be used to control tabindex if radio-button is used in groups_
**Scenario: Ensuring Proper Labeling for Accessibility**
Given a radio button component is rendered
When the component receives a tds-aria-label prop
Then it should correctly set the aria-label attributes on the input element
_Added both …

feat(radio-button): improved accessibility

---

packages/core/src/components/dropdown/dropdown.tsx

Converting Number values to strings, and allow Number 0 as value.
beta release: `1.27.0-allow-numbers-and-zero-values-beta.0`
showcase in react wrapper: https://github.com/scania-digital-design-system/tegel-react-demo/pull/228 
- **Jira:** Add ticket number after `CDEP-598`: [CDEP-598](https://jira.scania.com/browse/CDEP-598)
- **GitHub:** [Issue - The dropdown doesn't select the correct option when a numeric value is used #1125](https://github.com/scania-digital-design-system/tegel/issues/1125)
1. Beta release installed in react wrapper here: https://github.com/scania-digital-design-system/tegel-react-demo/pull/228 
2. Start the …

fix(dropdown): allow value to be Number 0

---

packages/core/src/components/text-field/text-field.tsx

Handling of input values when type is Number and Min or Max props is used.
Current behaviour allows typing of higher/lower values then set in max/min - the limits only applies when setting the number with input 'arrows'.
- **Jira:** Add ticket number after `CDEP-604`: [CDEP-604](https://jira.scania.com/browse/CDEP-604)
- **No issue:** 
1. Go to Storybook component Text Field
2. Set Type to Number and add a min/max value
3. Confirm that it is not possible to type higher/lower numbers 

feat(text-field): custom handling for min & max when input type is Number

---

logotype/_logotype.scss
packages/core/src/components/footer/footer.scss
packages/core/src/components/header/header-brand-symbol/header-brand-symbol.scss

This PR fixes the naming convention for local logotype variables to be consistent with CDN variables. The changes ensure proper fallback behavior for Scania logotypes in both header and footer components.
- **No issue:** Due to the same name of local and remote assets, the code generates an issue - CSS variable appears not to have content behind.
Issue in Development channel [here.](https://teams.microsoft.com/l/message/19:5e33f67fe502441f914fbcdc6e2548f5@thread.skype/1743678594125?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1743678594125&teamName=Tegel%20Design%20System&channelName=Development%20support%20-%20Tegel&createdTime=1743678594125)
1. Check preview link.
2. Check Header …

fix(logotypes): differentiate local variable from CDN ones

---

packages/core/src/components/textarea/readme.md
packages/core/src/components/textarea/test/default/textarea.axe.ts
packages/core/src/components/textarea/textarea.stories.tsx
packages/core/src/components/textarea/textarea.tsx

Improves accessibility for the Textarea component.
- **Jira:** [CDEP-428](https://jira.scania.com/browse/CDEP-428)
> Given the component is rendered in Storybook 
> When viewport changes width 
> Then the component should adjust its size accordingly without layout breaks 
> And it should maintain a clear and consistent UI
How to test:
1. Go to https://pr-1136.d3fazya28914g3.amplifyapp.com/?path=/story/components-textarea--default
2. Change the width of the window and verify that the textarea adjusts its width
This has not been fixed, see Additional context.
> Scenario: Proper Association Between Label and Textarea
> Given the component is rendered in Storybook
> When the label is displayed for the textarea
> Then the label should have a for attribute linking to the id of the textarea
> …

feat(textarea): accessibility improvements

---

packages/core/src/components/side-menu/side-menu-close-button/side-menu-close-button.tsx
packages/core/src/components/side-menu/side-menu-collapse-button/side-menu-collapse-button.tsx
packages/core/src/components/side-menu/side-menu-dropdown-list/side-menu-dropdown-list.tsx
packages/core/src/components/side-menu/side-menu-dropdown/side-menu-dropdown.tsx
packages/core/src/components/side-menu/side-menu.scss
packages/core/src/components/side-menu/side-menu.tsx
packages/core/src/components/side-menu/test/default/index.html
packages/core/src/components/side-menu/test/default/side-menu.axe.ts

✅ I have added the axe tests
✅ Close Hamburger Menu with Escape Key
✅ Focus on Inner Content After Opening Hamburger Menu
🟡 Open Submenu and Focus on First Item When Pressing Enter
_Did not manage to get this as I wish. I think the current logic is OK._
✅ Reverse Tabbing in Side Menu Should Work
✅ Move Focus Out When Exiting Menu Bar
✅ Add aria-expanded to Collapsible Side Menu
✅ Add aria-controls to Close Button
✅ Use aria-expanded on Collapsed Side Menu List
- **Jira:**  [CDEP-424](https://jira.scania.com/browse/CDEP-424)
✅ Close Hamburger Menu with Escape Key
1. Go to the [[side menu component]](https://pr-1127.d3fazya28914g3.amplifyapp.com/?path=/story/components-side-menu--default&globals=backgrounds.value:!hex(F9FAFB))
2. Make sure you can close …

fix(side-menu): accessibility improvements

---

packages/core/src/components/text-field/text-field.tsx

When there are multiple text-field elements on a page, when clicking on any of their labels, the first text-field is focused. This PR fixes so that the correct text-field is focused.
- **Jira:** [CDEP-662](https://jira.scania.com/browse/CDEP-662)
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/1155
1. Go to https://pr-230.d2vh2lmnzgzrkl.amplifyapp.com/form
2. Click on the text-field labels (e.g. for Phone number) and verify that the correct text-field is focused.
3. Compare with the current code on https://react-demo.tegel.scania.com/form where it doesn't work correctly
None
None

fix(text-field): add unique id

---

packages/core/src/components/textarea/textarea.tsx

When there are multiple textarea elements on a page, when clicking on any of their labels, the first textarea is focused. This PR fixes so that the correct textarea is focused.
- **Jira:** [CDEP-663](https://jira.scania.com/browse/CDEP-663)
1. Go to https://pr-231.d2vh2lmnzgzrkl.amplifyapp.com/form
2. Click on the labels of the two textarea elements and verify that only the one belonging to the label gets focused
None
None

fix(textarea): add unique id

---

packages/core/src/components/table/table-body-cell/table-body-cell.tsx
packages/core/src/components/table/table-body-input-wrapper/table-body-input-wrapper.tsx
packages/core/src/components/table/table-body-row-expandable/readme.md
packages/core/src/components/table/table-body-row-expandable/table-body-row-expandable.tsx
packages/core/src/components/table/table-body-row/table-body-row.tsx
packages/core/src/components/table/table-component-editable-cells.stories.tsx
packages/core/src/components/table/table-component-filtering.stories.tsx
packages/core/src/components/table/table-component-horizontal-scroll.stories.tsx
packages/core/src/components/table/table-component-multiselect.stories.tsx
packages/core/src/components/table/table-component-pagination.stories.tsx
packages/core/src/components/table/table-component-sorting.stories.tsx
packages/core/src/components/table/table-header-cell/readme.md
packages/core/src/components/table/table-header-cell/table-header-cell.tsx
packages/core/src/components/table/table-header-input-wrapper/table-header-input-wrapper.tsx
packages/core/src/components/table/table-toolbar/readme.md
packages/core/src/components/table/table-toolbar/table-toolbar.tsx
packages/core/src/components/table/table/test/default/table.axe.ts
packages/core/src/components/table/table/test/expandable-row/interaction-1.e2e.ts
packages/core/src/components/table/table/test/expandable-row/interaction-2.e2e.ts
packages/core/src/components/table/table/test/expandable-row/interaction-3.e2e.ts
packages/core/src/components/table/table/test/multiselect/default/table.e2e.ts
packages/core/src/components/table/table/test/multiselect/disabled-rows/table.e2e.ts
packages/core/src/components/table/table/test/sorting/table.e2e.ts

- Editable Table Cells: Pressing Enter after editing a cell saves the value and moves focus to the next cell.
- Semantic Table Structure: The table uses proper semantic elements for screen reader compatibility.
- Sortable Columns: Sorting updates aria-sort dynamically to reflect the current order.
- Expandable Sections: Expanding or collapsing updates aria-expanded and links controls with aria-controls.
- Accessible Toolbar: The toolbar has a proper accessible name via aria-labelledby.
- Descriptive Search Input: The search input includes a clear label using aria-describedby.
- **Jira:** [CDEP-386](https://jira.scania.com/browse/CDEP-386)
For each test scenario it requires the tester to open the amplified link and open the Table component.
_Scenario: …

feat(table): improve accessibility 

---

packages/core/src/components/text-field/text-field.tsx

Adds back the id in the helper text element (was removed in a commit after it was originally added), used by screen readers. Also now added a unique id to make it work correctly when there are multiple text-field elements in one page.
None
1. Go to https://pr-1170.d3fazya28914g3.amplifyapp.com/?path=/story/components-text-field--default&args=helper:Here+is+the+helper+text
2. Activate your screen reader and tab to the text-field element
3. Verify that "Here is the helper text" is announced
None
None

fix(text-field): add id for helper text

---

packages/core/src/components/side-menu/side-menu.tsx

This PR fixes automatic closing of the expanded/dropdown menu from the mobile view of side-menu.
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/1163
1. Go to the current implementation at https://tds-storybook.tegel.scania.com/?path=/story/patterns-navigation--few-navigation-items
2. Make the screen narrow
3. Open the dropdown for the side-menu in the top left corner
4. Make the screen wider 
5. Notice that it doesn't close and it's not possible to close it with the "close" button either
6. Go to the preview of the fixed version in this PR at https://pr-1173.d3fazya28914g3.amplifyapp.com/?path=/story/patterns-navigation--few-navigation-items
7. Repeat steps 2-4
8. Notice that now it closes
None
None

fix(side-menu): hide mobile dropdown on resize

---

packages/core/src/components/accordion/accordion-item/accordion-item.tsx
packages/core/src/components/chip/chip.stories.tsx
packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/dropdown/test/default/dropdown.e2e.ts
packages/core/src/components/dropdown/test/error/dropdown.e2e.ts
packages/core/src/components/dropdown/test/multiselect/dropdown.e2e.ts
packages/core/src/components/message/message.tsx
packages/core/src/components/message/test/basic/message.e2e.ts
packages/core/src/components/message/test/error/message.e2e.ts
packages/core/src/components/stepper/step/step.tsx

Fixing minor a11y issues found in the second a11y audit
1. Go to aws link and test the following new fixes
🟡 **Accordion**: [Chevron Down icon] should not be focusable
🟡 **Chip**: Configured in Storybook correctly for screen reader.
🟡 **Dropdown**: Closing Dropdown with keyboard return focus to main input
🟡 **Dropdown**: When Dropdown is closed. Dropdown option should not be focusable
🟡 **Dropdown**: Screen reader should first read [LABEL], [HELPERTEXT] if it exist.
🟡 **Message**: Icon within message component should not be reachable with screen reader
🟡 **Step**: Making sure the icon is not reachable with screen reader

fix: minor accessibility improvements

---

.husky/pre-push
packages/core/src/components/table/table-component-batch-actions.stories.tsx
packages/core/src/components/table/table-toolbar/readme.md
packages/core/src/components/table/table-toolbar/table-toolbar.scss
packages/core/src/components/table/table-toolbar/table-toolbar.tsx

Adds the slot 'start' for table action bar
- **No issue:** it was not possible to add any item to the left side of table action bar before
1. storybook -> table -> batch action

feat(table): action-bar start slot

---

packages/core/src/components/toast/readme.md

This PR adds accessibility documentation for the Toast component to address screen reader announcement issues. 
When toasts render on initial page load, screen readers often fail to announce their content because they only detect changes in aria-live regions after the page has loaded. The documentation provides a straightforward solution: either render toasts initially hidden and reveal them with showToast() after a brief delay, or create them dynamically when needed. A practical code example demonstrates the proper implementation, helping developers create more inclusive user experiences. 
Read through the documentation and make sure its correct.
I put the documentation above the  comment.
I think this is the way to get around my docs not being overwritten. Please let me know if this is …

docs(toast): add accessibility notes

---

README.md

Environmental variable name update due to changes that occurred with new version of Storybook.
- **No issue:** Noticed it after we merged Storyook 8
1. Test this variable in your local. Make sure to have latest develop "in"
2. Check if there are more mentions of "STORYBOOK_ENV" anywhere
- Amplify is already updated to support both old and new variable. Old one will be removed in a month time.

docs(root-readme): env variable name update

---

packages/core/src/components/checkbox/checkbox.tsx
packages/core/src/components/checkbox/readme.md
packages/core/src/components/datetime/datetime.tsx
packages/core/src/components/datetime/readme.md
packages/core/src/components/radio-button/radio-button.tsx
packages/core/src/components/radio-button/readme.md
packages/core/src/components/textarea/readme.md
packages/core/src/components/textarea/textarea.tsx
packages/core/src/components/toggle/readme.md
packages/core/src/components/toggle/toggle.tsx

Add focus property to text-area and all other focusable input components to allow programmatic focusing. This enhancement helps avoid double clicks on inputs (once to activate edit mode and once to focus).
- **GitHub:**: Related to #961
1. Go to each component that accepts user input (textarea, radio-button, checkbox, toggle, datetime)
2. Open the google console and test to focus on the element.
// For checkbox
document.querySelector('tds-checkbox') && document.querySelector('tds-checkbox').focusElement();
// For radio button
document.querySelector('tds-radio-button') && document.querySelector('tds-radio-button').focusElement();
// For toggle
document.querySelector('tds-toggle') && document.querySelector('tds-toggle').focusElement();
// For datetime …

feat: add focus property to text-area and other input components

---

packages/core/src/components/checkbox/checkbox-vars.scss
packages/core/src/components/checkbox/checkbox.scss

Implementation of new variable tokens for colors
- **Jira:**`feat(checkbox): start using new color & typography token system in CSS files`: [CDEP-748](https://jira.scania.com/browse/CDEP-748)
1. Go to Checkbox in storybook, compare with "live [Checkbox](https://tds-storybook.tegel.scania.com/?path=/story/components-checkbox--default)"
Link to [Figma](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=13865-180378&m=dev) if needed
2. Play with controls
3. Toggle darkmode and change background color in storybook preview
4. Toggle Traton
Right now different SVG:s are imported in CSS as background images, depending on dark/light theme, therefor we need to keep the selectors. This might be for further inspection in a later PR.

fix(checkbox): implement new variable tokens

---

packages/core/src/stories/foundations/icons-gallery.stories.tsx

Icon story was moved from Foundations to Components and had gotten a new path because of it, so this link was broken before. Should work now!
- **Jira:** [CDEP-1046](https://jira.scania.com/browse/CDEP-1046)
- ~**GitHub:** Include issue link~
- ~**No issue:** Describe the problem being solved.~
1. Go to icons gallery in Storybook
2. Click the link inside the description, referring to the icon component page
3. Verify ending up in the correct story without error message

fix(icons-gallery): updated link to icon story

---

.github/workflows/holy-grail.yml

Scheduled (cron) triggers don’t provide workflow inputs like version, which previously caused npm version to silently fail during automated dry runs.
This PR introduces a global env: block to define fallback defaults:
Now, version bumping and related actions use:
`${{ github.event.inputs.version || env.VERSION }}`
This ensures versioning works reliably in both manual and scheduled executions.
1. Go to...
2. Check in...
3. Run ...
_Add any other context or …

fix(holy-grail): ensure npm version bump works in scheduled runs

---

packages/core/src/components/dropdown/dropdown.tsx
packages/core/src/components/dropdown/readme.md

This PR fixes the previously introduced breaking change by adding back the label parameter for the setValue method in dropdown.tsx. I also needed to address some other console warnings when I committed the code.
None
Nothing to test
None
None

fix(dropdown): add label parameter to setValue to revert breaking change

---

build-tokens.mjs
style-dictionary.config.mjs
tokens/scss/traton/color-light.scss

Updated the Style Dictionary configuration to include both base and light mode selectors for Traton brand color tokens. This ensures that color tokens are applied at both the base .traton level and specifically for .traton .tds-mode-light, providing better CSS specificity and flexibility for theme switching.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-1054](https://jira.scania.com/browse/CDEP-1054)
1. Check `tokens/scss/traton/color-light.scss` and see that `.traton `class is added
2. Check the style dictionary file and see if class ".traton" is added there. 
3. Do not run style dictionary as we might get unwanted changes now.

build: support just ".traton" in color tokens

---

packages/core/src/stories/foundations/color/colors.mdx

I have added the yellow color scale to Storybook since its missing. 
- **Jira:** [CDEP-1047](https://jira.scania.com/browse/CDEP-1047)
1. Go to the [color system in Storybook](https://pr-1305.d3fazya28914g3.amplifyapp.com/?path=/docs/foundations-color-system--docs).
3. Make sure the yellow color scale exists amongst the other colors

docs(storybook): add yellow scale to color palette

---

packages/core/.storybook/preview.ts

Currently, Storybook for Tegel components only offers background toggling between light mode and dark mode. However, many Tegel components support additional theming through modeVariant properties such as primary and secondary.
This enhancement request proposes adding primary and secondary mode options under each of the existing background modes (light and dark). This would allow for more accurate component previews in Storybook, matching real-world implementations more closely.
- **Jira:** : [CDEP-1066](https://jira.scania.com/browse/CDEP-1066)
1. Open preview link
2. Go to any component, let's pick dropdown as example
3. Now pick brand, TRATON for example
4. In the toolbar, Switch between primary and secondary mode and notice how the background color of the canvas changes.
5. Switch to …

feat(storybook): add support for primary and secondary mode variants for light and dark themes

---

packages/core/src/components/breadcrumbs/breadcrumb/breadcrumb.scss
packages/core/src/components/breadcrumbs/breadcrumbs-vars.scss
packages/core/src/components/breadcrumbs/breadcrumbs.scss

Breadcrumbs component using new multibrand tokens
- **Jira:** [CDEP-745](https://jira.scania.com/browse/CDEP-745)
1.Go to preview link
2.Compare Breadcrumbs component styles in both Scania and Traton, in both light and dark modes with [Traton UI Kit: Breadcrumbs](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=2703-4931&m=dev)

feat(breadcrumbs): added multibrand tokens

---

packages/core/src/components/datetime/datetime-vars.scss
packages/core/src/components/datetime/datetime.scss

Datetime component using new multibrand tokens
- **Jira:** [CDEP-753](https://jira.scania.com/browse/CDEP-753)
**NOTE! THERE IS NO FIGMA FILE FOR DATETIME, THE COMPONENT USES SAME STYLES AS THE TEXTFIELD COMPONENT**
1.Go to preview link
2.Compare Datetime component styles in both Scania and Traton, in both light and dark modes with [Traton UI Kit: Textfield](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=13499-11330&m=dev)

feat(datetime): added multibrand tokens

---

packages/core/src/components/textarea/textarea-mixins.scss
packages/core/src/components/textarea/textarea-vars.scss
packages/core/src/components/textarea/textarea.scss

Added css multibrand tokens for Textarea
- **Jira:** [CDEP-765](https://jira.scania.com/browse/CDEP-765)
1. Go to textarea in storybook
2. Compare to [Figma](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=26756-59843&p=f&m=dev) and if needed [Prod](https://tds-storybook.tegel.scania.com/?path=/story/components-textarea--default)
3. Check both brands in dark/light mode

fix(textarea): component tokens rebase

---

packages/core/src/components/card/card.scss

Small fix to enable having items in header and subheader in right side of component.
- **No issue:** Came from support channel: [here](https://teams.microsoft.com/l/message/19:5e33f67fe502441f914fbcdc6e2548f5@thread.skype/1752222542385?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1752222542385&teamName=Tegel%20Design%20System&channelName=Development%20support%20-%20Tegel&createdTime=1752222542385)
1. Open branch on your local
2. Modify Card story to use header slot
3. Arrange content so it ends up in right side of header slot. Tip, use flex and justify-content: space-between.

fix(card): make header and subheader are 100% wide

---

packages/core/src/components/divider/divider-vars.scss
packages/core/src/components/divider/divider.scss
packages/core/src/components/divider/divider.stories.tsx
packages/core/src/components/divider/divider.tsx
packages/core/src/components/divider/readme.md

Updating Divider component with new a11y colors and new color variants.
To prevent braking changes "subtle" is chosen as default if user does not selected different variant.
- **Jira:** Add ticket number after `CDEP-`: [CDEP-1086](https://jira.scania.com/browse/CDEP-1086)
1. Open preview link.
2. Check Divider component
3. Open [Figma A11Y: Divider
](https://www.figma.com/design/d8bTgEx7h694MSesi2CTLF/branch/Z96Fk4cDATOIlr3sUcWX2l/Tegel-UI-Library?m=auto&node-id=34149-125001&t=9yxb2kiImPv96roT-1)
4. Compare Figma with Code - they should match

feat(divider): a11y color update and variant prop

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option.tsx

Users get confused by warnings as same one comes from dropdown and dropdown option
- **No issue:** Check conversation from [support channel](https://teams.microsoft.com/l/message/19:5e33f67fe502441f914fbcdc6e2548f5@thread.skype/1753354331038?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1753354331038&teamName=Tegel%20Design%20System&channelName=Development%20support%20-%20Tegel&createdTime=1753354331038).
1. Check if warning message is speaking of correct component so it is not misleading.

fix(dropdown-option): corrected console warning for a11y

---

packages/core/src/components/dropdown/dropdown-button.scss
packages/core/src/components/dropdown/dropdown-filter.scss
packages/core/src/components/dropdown/dropdown.scss
packages/core/src/components/text-field/text-field.scss
packages/core/src/components/textarea/textarea.scss

fixing the overlap issue where box-shadow is not taking up any space on demo pages. Check screenshot to see the issue in angular demo page.
- **No issue:** Check uploaded screenshot
1. Need to be packed, or released in beta to test
2. Go to angular demo
4. Check out `feat/multibrand-test` branch
5.`npm i @scania/tegel@1.34.0-multibrand-beta.5` or latest beta version.
6. set the`VITE_STORYBOOK_ENV`
7. Go to [Forms page](http://localhost:4200/form/simpleform)

fix(form-input-components): compensate for box shadow

---

packages/core/src/components/dropdown/dropdown-filter.scss
packages/core/src/components/dropdown/dropdown-option/dropdown-option.scss

fix disabled option text
- **Jira:** `fix disabled option text` [CDEP-1137](https://jira.scania.com/browse/CDEP-1137)
1. Go to dropdown in storybook
2. Toggle filter
3. Toggle disabled
4. Set a default option
5. The option value should now have the disabled grey color

fix(dropdown-filter): apply disabled option styles correctly

---

packages/core/src/components/footer/footer-group/footer-group.scss

This PR fixes so that the border-bottom is also shown when a footer-group is expanded in mobile view.
- **Jira:** `CDEP-`: [CDEP-1138](https://jira.scania.com/browse/CDEP-1138)
1. Go to https://pr-1371.d3fazya28914g3.amplifyapp.com/?path=/story/components-footer--default
2. Make the screen narrow so that the footer groups are expandable
3. Click e.g. "Title 1"
4. Verify that there's a border between "Title 1" and "Link 1"
None
None

fix(footer-group): show border-bottom also when expanded

---

packages/core/src/components/dropdown/dropdown-option/dropdown-option-vars.scss

Jira ticket description: Hover behavior in the table pagination is not defined in design yet and should be removed for now until we've had time to have a look at it.
What i did in this PR is to make the pagination dropdown hover look have exactly the same behaviour as our normal dropdown hover state does.
- **Jira:** `CDEP-1144`: [CDEP-1144](https://jira.scania.com/browse/CDEP-1144)
1. Open preview link below
2. Open up table/pagination
3. Open up the dropdown from the table footer, right after "rows per page".
4. Compare the hover state to the normal dropdown component (have them open side by side or compare to [Figma design:dropdown](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=26537-59509&p=f&m=dev) ), it should look exactly the same.
5. Try in …

fix(table): remove hover from dropdown pagination

---

packages/core/src/components/stepper/step/step.scss
packages/core/src/components/stepper/stepper-vars.scss

The checkmark or "tick" icon in dark mode is using a white icon but should rather use a dark one. This PR fixes that.
- **Jira:** : [CDEP-1142](https://jira.scania.com/browse/CDEP-1142)
1. Go to the stepper component using the preview link below
2. Switch to dark mode and observe that the "tick" turns dark
3. Switch between both TRATON and Scania to validate.
4. Compare to Figma design [here](https://www.figma.com/design/6osYTOfd4MgDq7LO6BCoUO/TRATON-Component-Library?node-id=26693-59848&p=f&m=dev)

fix(stepper): added color variable for the checkmark/tick in success step.

---

packages/core/src/components/popover-canvas/popover-canvas-vars.scss

This PR updates the color variables for the popover canvas to better align with a11y contrast.
- **Jira:** [CDEP-1128](https://jira.scania.com/browse/CDEP-1128)
1. Go to [the popover canvas in the preview link](https://pr-1363.d3fazya28914g3.amplifyapp.com/?path=/story/components-popover-canvas--default)
2. Compare the popover canvas to [the figma file](https://www.figma.com/design/d8bTgEx7h694MSesi2CTLF/Tegel-UI-Library?node-id=56102-1598&m=dev)

fix(popover-canvas): update color variables for light and dark modes

---

packages/core/src/tegel-light/components/tl-modal/tl-modal.stories.tsx

Buttons on tegel light modal component was looking off, missing a size modifier. 
- **No issue:** 
1. Go to preview link and the tegel light modal component
2. Check that the buttons look OK

fix(tl-modal): add size modifier to buttons

---

packages/core/src/components/button/readme.md
packages/core/src/components/card/card.scss
packages/core/src/components/card/card.stories.tsx
packages/core/src/components/card/card.tsx
packages/core/src/components/card/readme.md
packages/core/src/components/icon/readme.md

The Card component has a design variant that supports an expandable behaviour. This allows users to hide the card content under a dropdown-like interaction, toggled via a chevron icon in the header.
Until now, this functionality existed in design (Figma) but was missing in code. This PR adds that functionality
(I also added two action buttons for demo purpose that alligns with the current figma design)
- **Jira:** `[CDEP-1522](https://jira.scania.com/browse/CDEP-1522)
1. Go to preview link and open up the card component
2. Set the expandable prop to true
3. Click on the chevron that appears on the component and test the expand functionality.
4. Try the expanded prop via storybook control
5. Try having different options on at the same time (eg. body image, stretched etc..)
6. Compare to …

feat(card): added expandable prop

---

packages/core/.storybook/preview.css
packages/core/src/components/link/link.scss

This PR fixes the hover styling so that if the link has an underline it disappears and if it doesn't have one it appears. Also updated the storybook file preview.css to not override the styling in tds-link components to be able to set the font where the link is used.
- **Jira:** [CDEP-1213](https://jira.scania.com/browse/CDEP-1213)
1. Go to https://pr-1473.d3fazya28914g3.amplifyapp.com/?path=/story/components-link--standalone-link
2. Inspect and verify that the standalone link has the Scania Sans Semi Condensed font
3. Toggle the underline setting and verify that, when hovering, when there isn't an underline it appears and when there is one it disappears
None
None

fix(link): font and hover styling

---

.github/CODEOWNERS

Found this feature when researching the `CODEOWNERS` file, could be quite handy when people are joining and leaving the team. Just make sure they have proper access to the group of reviewers (in this case, the `@scania-digital-design-system/developers` group). 
Found it here:
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
_*First and foremost*_ — let me know if you think this is a good idea or not, and we can take it from there! 🤞 
---
- **No issue:** See description above!
1. Go to the file in the branch
2. Check that the file is marked as verified and valid
3. Open a draft PR to confirm that the team is added as reviewers

chore: update to codeowners 
